### ISSUE TITLE
Separator between username and password is not mentioned in documentation

### ISSUE THREAD

**Issue by wjam** [grafana/terraform-provider-grafana#1]
The separator between the username and password is not mentioned in the documentation, although it's implied to be `/`. The actual separator is `:` and should be [in the documentation](https://github.com/terraform-providers/terraform-provider-grafana/blob/master/website/docs/index.html.markdown).

**Comment by mbraku** [comment]
It says "If username/password is used, they are provided in a single string and separated by a colon." in the documentation

**Comment by radeksimko** [comment]
Hi @wjam 
@mbraku is right - the separator is documented on the link you mentioned.

Let us know if there's anything else unclear about this.
