### ISSUE TITLE
Allow anonymous access to Grafana

### ISSUE THREAD

**Issue by bitbrain** [grafana/terraform-provider-grafana#10]
In Grafana it is possible to open access to everyone. By doing so, you don't need to provide an `Authorization` header with your `POST` call.

The `terraform-provider-grafana` does not support this concept yet. The `auth` field must be provided and even when keeping it empty, the provider always sends an `Authorization` header with every request.

Can we make it optional to send the `auth` token or at least give us the option to disable auth completely within the provider?

**Comment by pearkes** [comment]
Would this assume that you have configured your installation to set auth anonymous for administrators?

http://docs.grafana.org/installation/configuration/#auth-anonymous

If so, I agree this would be a good option, given what seems to be the first-class nature of anonymous access.
