### ISSUE TITLE
Improve Terraform parity with features in Grafana

### ISSUE THREAD

**Issue by Hronom** [grafana/terraform-provider-grafana#1006]
Since most of orgs right now use Terraform to manage infra and provision different resources it becomes a major blocker that  [Terraform Grafana provider](https://registry.terraform.io/providers/grafana/grafana/latest/docs) not stay in parity with the most functionality available in Grafana/Grafana Cloud.

Given that [Crossplane Grafana Provider](https://marketplace.upbound.io/providers/grafana/provider-grafana/v0.6.0) is a port of  [Terraform Grafana provider](https://registry.terraform.io/providers/grafana/grafana/latest/docs) users don't have other options and it blocks following infrastructure as code pattern.

It will be good if every feature in Grafana implies add support of it in API and [Terraform Grafana provider](https://registry.terraform.io/providers/grafana/grafana/latest/docs).

Examples:
* https://github.com/grafana/terraform-provider-grafana/issues/1004
* https://github.com/grafana/terraform-provider-grafana/issues/1003
* https://github.com/grafana/terraform-provider-grafana/issues/1002
* https://github.com/grafana/terraform-provider-grafana/issues/995
* https://github.com/grafana/terraform-provider-grafana/issues/993

**Comment by julienduchesne** [comment]
I hear you but I'll close this. This issue is not actionable in any way by maintainers of this repository. We are constantly working on improving immediate support of features in TF
