### ISSUE TITLE
grafana_data_source import documentation error

### ISSUE THREAD

**Issue by jtama** [grafana/terraform-provider-grafana#1023]
### Terraform Version
N/A

### Affected Resource(s)
* grafana_datasource

### Expected Behavior
It would be nice to document how to path organization identifier

### Actual documentation
The documentation says the following import syntax are available : 
```
terraform import grafana_data_source.by_integer_id {{datasource id}}
terraform import grafana_data_source.by_uid {{datasource uid}}
```

**Comment by klemen-df** [comment]
Could you be even more clear, what am I missing?

`terraform import module.grafana_datasources.grafana_data_source.azure_monitor.by_uid {{1:N0KbQRynk}}`

**Comment by julienduchesne** [comment]
No brackets. Should be `terraform import module.grafana_datasources.grafana_data_source.azure_monitor.by_uid 1:N0KbQRynk`

**Comment by jtama** [comment]
In fact almost all import should specify this format

**Comment by jtama** [comment]
@julienduchesne there was alrady a MR for this bug https://github.com/grafana/terraform-provider-grafana/pull/1024. 

Aren't contributions welcome ?

**Comment by klemen-df** [comment]
> No brackets. Should be `terraform import module.grafana_datasources.grafana_data_source.azure_monitor.by_uid 1:N0KbQRynk`

Using terraform 1.2.9, grafana provider 2.3.0

It seems that I don't understand the logic, running this above I get:

```
╷
│ Error: Invalid address
│
│   on <import-address> line 1:
│    1: module.grafana_datasources.grafana_data_source.azure_monitor.by_uid
│
│ Resource instance key must be given in square brackets.
╵

For information on valid syntax, see:
https://www.terraform.io/docs/cli/state/resource-addressing.html
```

**Comment by julienduchesne** [comment]
> It seems that I don't understand the logic, running this above I get:

It tells you that the error is at `module.grafana_datasources.grafana_data_source.azure_monitor.by_uid`. This address is invalid. I don't really understand why. The ID at the end `1:N0KbQRynk` never even comes into play because Terraform fails before going into the provider

**Comment by klemen-df** [comment]
> > It seems that I don't understand the logic, running this above I get:
> 
> It tells you that the error is at `module.grafana_datasources.grafana_data_source.azure_monitor.by_uid`. This address is invalid. I don't really understand why. The ID at the end `1:N0KbQRynk` never even comes into play because Terraform fails before going into the provider

But, I can confirm that this works:
`terraform import module.grafana_datasources.grafana_data_source.azure_monitor 1:N0KbQRynk`
