### ISSUE TITLE
PagerDuty alert notification channel does not set the integration key properly

### ISSUE THREAD

**Issue by ryanisnan** [grafana/terraform-provider-grafana#103]
### Terraform Version
```
Terraform v0.12.26
+ provider.aws v2.45.0
+ provider.grafana v1.5.0
+ provider.newrelic v1.15.1
+ provider.template v2.1.2
```

### Affected Resource(s)
- `grafana_alert_notification`

### Expected Behavior
Pagerduty alert notification should have the integration key set

### Actual Behavior
Pagerduty alert notification does not have the integration key set

### Steps to Reproduce
Sample resource:

```
resource "grafana_alert_notification" "pagerduty_low" {
  name = "PagerDuty - CloudWatch Low Urgency"
  type = "pagerduty"
  is_default = false
  settings = {
    integration_key = "XXX"
    severity = "error"
    auto_resolve = true
  }
}
```

The documentation on the official Terraform site is also pretty lacking with respect to this provider. Specifically, the alert notification types are not explained very much at all, and the documentation that is linked to is also deficient.

**Comment by Tenchi2xh** [comment]
From what I can see [here](https://grafana.com/docs/grafana/latest/administration/provisioning/#supported-settings) and also in the docs example, the settings are in camel case, so `integrationKey` and `autoResolve`.

Also, `integrationKey` should maybe be in `secure_settings` instead

**Comment by julienduchesne** [comment]
`grafana_alert_notification` is now deprecated in favor of the new alerting features. See the [`Alerting` category](https://registry.terraform.io/providers/grafana/grafana/latest/docs/resources/contact_point). So this issue will not be fixed
