### ISSUE TITLE
Alert notification channel returns incorrect ID as output

### ISSUE THREAD

**Issue by ryanisnan** [grafana/terraform-provider-grafana#104]
### Terraform Version
```
Terraform v0.12.26
+ provider.aws v2.45.0
+ provider.grafana v1.5.0
+ provider.newrelic v1.15.1
+ provider.template v2.1.2
```

### Affected Resource(s)
- grafana_alert_notification

### Terraform Configuration Files
```hcl
resource "grafana_alert_notification" "pagerduty_low" {
  name = "PagerDuty - CloudWatch Low Urgency"
  type = "pagerduty"
  is_default = false
  settings = {
    integration_key = "XXX"
    severity = "error"
    auto_resolve = true
  }
}
```

### Expected Behavior
The `id` output property of the resource does not seem to correspond to a usable alert notification ID in Grafana. E.g. I expect something like `j_UyWvkGa`.

### Actual Behavior
The `id` returns something like `1` or `2`. When these IDs are referenced in a panel's JSON, they do not work.

### Steps to Reproduce
1. Provision an alert notification channel of the pagerduty type
2. Use the ID returned by the alert notification channel in a grafana panel alert
3. Inspect via the UI that the notification has not been hooked up properly
4. Manually select the notification channel through the UI
5. Inspect the panel JSON again
6. Notice that the panel JSON includes new configuration referencing the proper alert notification channel ID.

**Comment by eugenekainara** [comment]
@ryanisnan seems that is already fixed by https://github.com/terraform-providers/terraform-provider-grafana/commit/92548cfb464536094489de6d2a812229415ae4f4 
We just need to wait for release

**Comment by eugenekainara** [comment]
@tonglil Is there any dates of plan to release new version?
