### ISSUE TITLE
Add ability to specify org_id for user

### ISSUE THREAD

**Issue by jtama** [grafana/terraform-provider-grafana#1041]
The grafana api allows to specify an org id at user creation, which is currently supported neither by the ressource nor returned by data_source. 

To achieve the same, one has two solutions : 

1. create the users, then to create the organisation attaching the users to it, then go to grafana and remove the user from the default organization. 
2. Just specify the user at organization creation, sepcifying `create_users=true`, but then a random password is generated, which can't be retrieve...
3. add a `local-exec` to remove the user from _Main Org._

**Comment by julienduchesne** [comment]
You could import your main org and manage its users. Specifying user orgs in a bi-directional way (from the org resource and from the user resource) will be troublesome. Won't do this one
