### ISSUE TITLE
Cannot import existent remote object in grafana_rule_group

### ISSUE THREAD

**Issue by sasha-sup** [grafana/terraform-provider-grafana#1054]
Hey, i'm following [doc](https://registry.terraform.io/providers/grafana/grafana/latest/docs/resources/rule_group#import) for import existing resources from Grafana into Terraraform and get error with alert rules while import. 
I tried different ways - import folder first, import by rule UID and always get error. How can I avoid this error? Any suggestions? 

### Terraform Version
* Terraform: v1.5.5
* Terraform Grafana Provider: v2.3.2
* Grafana: v10.0.3

### Affected Resource(s)
* grafana_rule_group

### Terraform Configuration Files
```hcl
resource "grafana_rule_group" "awesome-rule" {}


resource "grafana_folder" "general-alertnig" {
  title = "General Alerting"
  uid   = "d5567abc-4c0c-42bf-802f-6540a8c3cea1"
}
```

### Debug Output
[Debug Output](https://gist.github.com/sasha-sup/0cb68683ba5405d3eb89eb0a97a01354)

### Expected Behavior
`Import successful!`

### Steps to Reproduce
```sh
terraform import grafana_rule_group.awesome-rule d5567abc-4c0c-42bf-802f-6540a8c3cea1;"Team status updates worker"
```

### Actual behavior
```sh
grafana_rule_group.awesome-rule: Importing from ID "d5567abc-4c0c-42bf-802f-6540a8c3cea1"...
grafana_rule_group.awesome-rule: Import prepared!
  Prepared grafana_rule_group for import
grafana_rule_group.awesome-rule: Refreshing state... [id=d5567abc-4c0c-42bf-802f-6540a8c3cea1]
╷
│ Error: Cannot import non-existent remote object
│ ...
╵
Team status updates worker: command not found
```

### Important Factoids
This alert rule imported from Grafana UI in yaml:
```yaml
apiVersion: 1
groups:
    - orgId: 1
      name: Team status updates worker
      folder: General Alerting
      interval: 5m
      rules:
      ...
```

**Comment by julienduchesne** [comment]
Try this:
```
terraform import grafana_rule_group.awesome-rule "d5567abc-4c0c-42bf-802f-6540a8c3cea1;Team status updates worker"
```

**Comment by sasha-sup** [comment]
> Try this:
> 
> ```
> terraform import grafana_rule_group.awesome-rule "d5567abc-4c0c-42bf-802f-6540a8c3cea1;Team status updates worker"
> ```

I feel so dumb.
Thank you man, it worked!
Please update documentation
