### ISSUE TITLE
1.6.0 ETA release

### ISSUE THREAD

**Issue by giuliocalzo** [grafana/terraform-provider-grafana#106]
Hi @tonglil do you have any ETA for 1.6.0 release?

Kind regards

**Comment by teddylear** [comment]
Agreed, 1.6.0 is blocking the release of this PR removing slugs and replacing with uids: https://github.com/terraform-providers/terraform-provider-grafana/pull/84 which would be tagged under 2.0.0 per the comments.

**Comment by giuliocalzo** [comment]
@mlclmj can you help on this?

**Comment by giuliocalzo** [comment]
@tonglil @mlclmj any update?

**Comment by mahsoud** [comment]
any updates? @radeksimko @mlclmj  @paultyng

**Comment by trotttrotttrott** [comment]
1.6.0 was just released! https://registry.terraform.io/providers/grafana/grafana/latest
