### ISSUE TITLE
Documentation outdated and not working – Installing Synthetic Monitoring on a new Grafana Cloud Stack

### ISSUE THREAD

**Issue by AndiDog** [grafana/terraform-provider-grafana#1069]
### Terraform Version
* Terraform: v1.5.7
* Terraform Grafana Provider: v2.3.3
* Grafana: Cloud

### Affected Resource(s)

Getting any synthetic monitoring to work

### Steps to Reproduce

The [forum post](https://community.grafana.com/t/terraform-deployment-of-synthetic-monitoring-installation-which-permissions-are-needed/104562) shows the error when creating the synthetic monitoring stack. Even though I've selected _all_ possible permissions, it still fails. 

So I tried the Terraform module documentation [Installing Synthetic Monitoring on a new Grafana Cloud Stack](https://registry.terraform.io/providers/grafana/grafana/latest/docs#installing-synthetic-monitoring-on-a-new-grafana-cloud-stack) but unfortunately, it's using outdated concepts such as API keys instead of access policies. Whichever way I've tried, the error persists: `cannot get information for grafana instance with ID [...]`.

**Comment by julienduchesne** [comment]
Hey! Just came up with new docs: https://github.com/grafana/terraform-provider-grafana/pull/1098
