### ISSUE TITLE
Add support for AWS-SNS integration for contact point resource 

### ISSUE THREAD

**Issue by lewinkedrs** [grafana/terraform-provider-grafana#1075]
Amazon managed grafana supports and defaults to an [Amazon SNS](https://docs.aws.amazon.com/grafana/latest/userguide/v9-alerting-explore-contacts.html) integration contact point for alerting.

Using the [terraform provider](https://registry.terraform.io/providers/grafana/grafana/latest/docs/resources/contact_point), there is no way to provision or interact with AmazonSNS contact points. It would be nice to be able to integrate these AmazonSNS contact points the same way that other contact points are managed.

**Comment by VermaPriyanka** [comment]
Related to https://github.com/grafana/terraform-provider-grafana/issues/1075

**Comment by justinhauer** [comment]
@julienduchesne is there a way to use the SNS contact point in non-amazon managed grafana instance? I am interested in triggering resources for remediation within AWS with this
