### ISSUE TITLE
add plugin install support

### ISSUE THREAD

**Issue by mikempx** [grafana/terraform-provider-grafana#1078]
A large customer has a use case of spinning up Grafana stacks programmatically and then configuring the stack accordingly, which includes adding plugins.  Today, we need to use gcom to accomplish this - which is a nice workaround - but a bit clunky and less-than-seamless.  Thanks for the consideration!

**Comment by julienduchesne** [comment]
Have you tried this resource? https://registry.terraform.io/providers/grafana/grafana/latest/docs/resources/cloud_plugin_installation
