### ISSUE TITLE
[feature request] add the possibility to use Grafana provisioning capability

### ISSUE THREAD

**Issue by rspechenkin** [grafana/terraform-provider-grafana#108]
Hi there,

According to the [Provisioning Grafana page](https://grafana.com/docs/grafana/latest/administration/provisioning/) tools such Chef, Puppet, Ansible etc. support the usage of the provisioning capability but unfortunately this support is missing in the Terraform Grafana provider

### Affected Resource(s)
- grafana provider
- grafana data source

**Comment by inkel** [comment]
Hi, @rspechenkin, thank you for your interesting and sorry for the long delay in an answer.

I've been reviewing this, and this seems out of the scope of what the provider does. The link you mentioned is for installing and provisioning Grafana, whereas this provider is for configuring existing Grafana installations by interacting with the HTTP API.
