### ISSUE TITLE
[Feature Request] Support Annotations

### ISSUE THREAD

**Issue by mdb** [grafana/terraform-provider-grafana#11]
In current implementation, it appears `terraform-provider-grafana` does not support Grafana [annotations](http://docs.grafana.org/reference/annotations/). It would be great to be able to annotate dashboards from a `terraform apply`, thus empowering Grafana dashboard visualization of events -- such as deployments -- and the events' impact on key metrics.

Note that [apparentlymart/go-grafana-api PR #6](https://github.com/apparentlymart/go-grafana-api/pull/6) seeks to add annotation support to `apparentlymart/go-grafana-api`, such that annotation support could then be addressed here in `terraform-provider-grafana`.

Thanks!

**Comment by julienduchesne** [comment]
There's a typo on this line: https://github.com/nytm/go-grafana-api/blob/master/annotation.go#L41
`"/api/annotation"` should be `"/api/annotations"`. This would need a fix on the client's side

**Comment by julienduchesne** [comment]
Hi @trotttrotttrott, I tried to tackle this but there's a typo here: https://github.com/grafana/grafana-api-golang-client/blob/master/annotation.go#L41. `"/api/annotation"` should be `"/api/annotations"`. However, I saw that that client is deprecated. Is the solution to do a PR to it anyways or is there another client that could be used?

**Comment by mdb** [comment]
@julienduchesne To add a bit more context there, I attempted to fix this `/api/annotation` typo in [PR 57](https://github.com/nytm/go-grafana-api/pull/57/files) of the original `github.com/nytm/go-grafana-api` client package, which I believe was the original home of `github.com/grafana/grafana-api-golang-client`, but that PR was never reviewed or merged.

So, that's just to say, I have the same question: should bug fixes be PR'd against `github.com/grafana/grafana-api-golang-client`, or should `terraform-provider-grafana` use an alternative API client?

**Comment by inkel** [comment]
> However, I saw that that client is deprecated. Is the solution to do a PR to it anyways or is there another client that could be used?

@julienduchesne despite the client being deprecated I'd say please do fix it, we have been adding some small fixes to it nevertheless.

**Comment by mdb** [comment]
> despite the client being deprecated I'd say please do fix it, we have been adding some small fixes to it nevertheless.

@inkel I've created another PR fixing the `GET /api/annotations` URL path here: https://github.com/grafana/grafana-api-golang-client/pull/36

Thanks!
