### ISSUE TITLE
feature: grafana_role to support full role spec

### ISSUE THREAD

**Issue by mhulscher** [grafana/terraform-provider-grafana#1103]
Currently, the `grafana_role` resource does not have feature parity with pre-provisioning of roles through local config files, optionally applied with a sidecar container.

For example, as a user of grafana enterprise, I would like to create custom roles that inherit from existing roles, using the `from:` field in a role spec. This is not possible with the `grafana_role` resource.

Links:
* https://grafana.com/docs/grafana/latest/administration/roles-and-permissions/access-control/rbac-grafana-provisioning/
* https://registry.terraform.io/providers/grafana/grafana/latest/docs/resources/role

**Comment by julienduchesne** [comment]
This would be an issue for the `grafana/grafana` repo. All attributes provided by the grafana API are currently implemented in the provider
