### ISSUE TITLE
bug: `grafana_user.is_admin` can not be modified for external users

### ISSUE THREAD

**Issue by mhulscher** [grafana/terraform-provider-grafana#1104]
The grafana terraform provider refuses to update a user's `is_admin` attribute if that user is flagged as externally provisioned.

In our use-case, we pre-provision grafana users with terraform. Users are assigned to teams and orgs. Users then log in through an external IDP. In our case we use `auth.jwt` . In `grafana.ini` we set `auto_sign_up: false`. Once a user has logged in and is flagged as an external user, we can no longer update their `is_admin` attribute through terraform. However, from the grafana UI it is possible to change this attribute. I would like to continue to reconcile the `is_admin` attribute through terraform. Any non-idempotency introduced by myself by making changes in the UI should be at my own risk. In other words, I believe terraform should continue to reconcile users that are logged in through an IDP, if that is what I configure.

### Terraform Version
* Terraform: 1.5.7
* Terraform Grafana Provider: 2.3.3
* Grafana: 10.1.5 **enterprise**

### Affected Resource(s)
Please list the resources as a list, for example:
* `grafana_user`

### Terraform Configuration Files
```hcl
resource "grafana_user" "this" {
  name     = "John Doe"
  email    = "foo@example.com"
  login    = "foo@example.com"
  password = "example"

  is_admin = true

  lifecycle {
    ignore_changes = [
      name,
      email,
      login,
      password,
    ]
  }
}
```

### Expected Behavior
I should be able to modify whether a user is a grafana admin or not.

### Actual Behavior
```
│ Error: status: 403, body: {"message":"User info cannot be updated for external Users"}
```

### Steps to Reproduce
* Apply user with `is_admin = true`
* Login as this user through an external IDP, in my case this happens with `auth.jwt`
* Apply user again with `is_admin = false`

**Comment by julienduchesne** [comment]
Unless I'm mistaken, it looks like an issue with the Grafana API. Could you open an issue there instead?

**Comment by mhulscher** [comment]
@julienduchesne this is already possible with the grafana API, as far as I understand. When snooping on the traffic in the browser when changing the isAdmin flag, this is the endpoint that is being called:

`PUT /api/admin/users/81/permissions`

with body

```
{"isGrafanaAdmin":false}
```
