### ISSUE TITLE
Regarding updating existing grafana role and some doubts

### ISSUE THREAD

**Issue by kalyangitnew** [grafana/terraform-provider-grafana#1122]
Hello,

I see if created a Grafana role and if we want to update that role Sometimes facing 400 Erros and I see it might terraform provider Issue . grafana custom role block would be better if to add some feature. Datasource permissions bucket specific made also some what better if done.

**Comment by kalyangitnew** [comment]
I see issue sometimes if want to update the existing custom role also it giving some 400 errors.

**Comment by julienduchesne** [comment]
Missing some details for this to be actionable. Can you re-open this as a bug if this is still happening?
