### ISSUE TITLE
Bump 2.3.3 -> 2.4.0 - error reading folder with ID

### ISSUE THREAD

**Issue by andre-lx** [grafana/terraform-provider-grafana#1126]
### Terraform Version
* Terraform: 1.6.3
* Terraform Grafana Provider: 2.3.3
* Grafana: 10.2.0

### Affected Resource(s)
* grafana_folder

### Terraform Configuration Files
```hcl
resource "grafana_folder" "logs_folders" {
  for_each = local.grafana.folders

  title = each.value
  uid   = random_string.logs_folders_uids[each.key].result
}
```

### Debug Output
```hcl
╷
│ Error: error reading folder with ID: Get https://xxxxxx/api/folders: status: 405, body: {error:Incorrect HTTP method for uri [/api/folders] and method [GET], allowed: [POST],status:405}
│ 
│   with module.observability.grafana_folder.logs_folders[dashboards],
│   on modules/observability/grafana.tf line 22, in resource grafana_folder logs_folders:
│   22: resource grafana_folder logs_folders {
│ 
```

The right URL is: `https://xxxxxx/grafana/api/folders` passed on the provider configuration: 
```hcl
provider "grafana" {
  alias = "grafana"

  url  = "${local.base_url}/${local.grafana.base_path}"
}
```

### Actual Behavior
In version 2.3.3 this url is being used correctly and everything works great. From version 2.3.3 looks like the grafana provider is using only the `local.base_url`

**Comment by julienduchesne** [comment]
Will look into this ASAP!
