### ISSUE TITLE
Provider not available in registry.terraform.io

### ISSUE THREAD

**Issue by wjam** [grafana/terraform-provider-grafana#113]
### Terraform Version
0.13

### Affected Resource(s)
terraform-bundle tool (https://github.com/hashicorp/terraform/tree/master/tools/terraform-bundle)

### terraform -bundle Configuration File
```hcl
terraform {
  version = "0.13.0"
}

providers {
  grafana = {
    versions = ["~> 1.0"]
  }
}
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
It should be possible to create a bundle which contains this provider using Terraform 0.13

### Actual Behavior
Tool fails with an error stating that it cannot find a version of the provider in the provider registry at https://registry.terraform.io. Having looked myself, I agree that this provider isn't available from the provider registry and this can be further shown as the documentation for this provider is still hosted under https://www.terraform.io/docs/ rather than from the registry provider.
 
### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. build/run the terraform-bundle tool using the configuration above

### Important Factoids
Documentation for this provider is still on the old site and this provider cannot be found manually in https://registry.terraform.io.

**Comment by trotttrotttrott** [comment]
I suspect this will work for the time being:

```hcl
providers {
  grafana = {
    versions = ["~> 1.0"]
    source = "terraform-providers/grafana"
  }
}
```

My understanding is that `terraform-providers` is intended for temporary support during the move to registry.terraform.io. I just did something similar with 0.13's [`terraform providers mirror`](https://www.terraform.io/docs/commands/providers/mirror.html) command and the following:

```hcl
terraform {
  required_providers {
    grafana = {
      source = "terraform-providers/grafana"
    }
  }
}
```

**Comment by trotttrotttrott** [comment]
Migration has been complete for a while...

```
terraform {
  required_providers {
    grafana = {
      source  = "grafana/grafana"
      version = "0.9.0"
    }
  }
}
```

https://registry.terraform.io/providers/grafana/grafana/latest
