### ISSUE TITLE
Provider does not work when you run grafana on a sub path: example.com/grafana

### ISSUE THREAD

**Issue by abeluck** [grafana/terraform-provider-grafana#1137]
### Terraform Version
* Terraform: 1.5.3
* Terraform Grafana Provider: 2.5.0
* Grafana: 10.2.0

### Affected Resource(s)
Please list the resources as a list, for example:
* All

### Terraform Configuration Files

```hcl
provider "grafana" {
  url  = "https://monitor.example.com/grafana"
  auth = var.grafana_auth
}
resource "grafana_folder" "folder" {
  title = "test"
}
```

### Debug Output
```
    Error: failed to create folder: Post "https://monitor.example.com/api/folders": status: 404, body: <html>
    <head><title>404 Not Found</title></head>
    <body>
    <center><h1>404 Not Found</h1></center>
    <hr><center>nginx/1.25.2</center>
    </body>
    </html>
  
  
      with module.this.grafana_folder.folder,
      on .terraform/modules/this/src/redacted/redacted/redacted/grafana.tf line 1, in resource "grafana_folder" "folder":

```

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior

The folder should be created

### Actual Behavior

An error occurs because the provdier is attempting to talk to the api at `https://monitor.example.com/api/folders` which is invalid. The correct api url is `https://monitor.example.com/grafana/api/folders`

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
n/a

### References
n/a

**Comment by maazamalik** [comment]
I am also having the same issue

**Comment by julienduchesne** [comment]
Strange, we have a test suite that runs all the tests from a subpath. Since this has started happening with the new openapi client, it may be because it doesn't handle redirects the same way. How is your Grafana server configured?

**Comment by julienduchesne** [comment]
Nevermind, I found the error. I will fix it, sorry about that. It's actually my test that's being too permissive. My grafana instance is configured to work with or without the subpath
