### ISSUE TITLE
Silcences are now available through API not yet in the Terraform provider

### ISSUE THREAD

**Issue by luis02lopez** [grafana/terraform-provider-grafana#1153]
Silences are now available in the API: https://grafana.com/docs/grafana/latest/alerting/manage-notifications/create-silence/

But not yet in the provider

**Comment by julienduchesne** [comment]
The provider only manages the Grafana alertmanager and silences are not available for the Grafana alertmanager. From the docs you linked:

> Note that inhibition rules are not supported in the Grafana Alertmanager.

For the Grafana alertmanager, you can use mute timings

**Comment by ivoronin** [comment]
You can use this provider to manage silences: https://github.com/ivoronin/terraform-provider-grafanasilence/
