### ISSUE TITLE
parent_folder_uid isn't work as expected. grafana_folder resource

### ISSUE THREAD

**Issue by m0ps** [grafana/terraform-provider-grafana#1166]
### Terraform Version
Terraform v1.3.10
on darwin_arm64
+ provider registry.terraform.io/grafana/grafana v2.6.1

### Affected Resource(s)
* grafana_folder

### Terraform Configuration Files
```hcl
resource "grafana_folder" "fld1" {
  title = "my-test-fld1"
}

resource "grafana_folder" "fld2" {
  title             = "my-test-fld2"
  parent_folder_uid = grafana_folder.fld1.uid
}

```

### Expected Behavior
It should be possible to create subfolders in the Grafana Cloud instance
### Actual Behavior
A subfolder is created in the root, and during the next apply, it tries to reconfigure it each time tf apply is run

```hcl
  # grafana_folder.fld2 must be replaced
-/+ resource "grafana_folder" "fld2" {
      ~ id                           = "0:100" -> (known after apply)
      - org_id                       = "0" -> null
      + parent_folder_uid            = "dabaa340-ba9a-453c-a634-XXXXXXXXXXXXX" # forces replacement
      ~ uid                          = "f99ff261-6077-4847-8eac-YYYYYYYYYYYY" -> (known after apply)
      ~ url                          = "https://AAAAAAAAA.grafana.net/dashboards/f/f99ff261-6077-4847-8eac-ZZZZZZZZZZZZZZZ/my-test-fld2" -> (known after apply)
        # (2 unchanged attributes hidden)
    }
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- https://github.com/grafana/terraform-provider-grafana/pull/1129

**Comment by julienduchesne** [comment]
It’s probably not enabled on your Grafana instance

**Comment by m0ps** [comment]
Thanks for the clarification. THe feature flag was enabled through a support request, and now it works as expected.

**Comment by nmeser** [comment]
Subfolder/Nested Folder working with provided configuration.
Grafana 11+ , Terraform Grafana Provider 4+

resource "grafana_folder" "fld1" {
  title = "my-test-fld1"
}

resource "grafana_folder" "fld2" {
  title             = "my-test-fld2"
  parent_folder_uid = grafana_folder.fld1.uid
}
