### ISSUE TITLE
feature: add missing attributes of data-sources API

### ISSUE THREAD

**Issue by mhulscher** [grafana/terraform-provider-grafana#1174]
The following attributes exist in the data-sources API, but can not be defined in the `grafana_data_source` resource. I would like to be able to set them.

* `readOnly`
* `typeLogoUrl`

See:
* https://grafana.com/docs/grafana/latest/developers/http_api/data_source/

**Comment by julienduchesne** [comment]
These attributes cannot be set by the API. They can only get read
