### ISSUE TITLE
grafana_synthetic_monitoring_check: target/job combination already exists (HTTPs checks)

### ISSUE THREAD

**Issue by ishworgurung** [grafana/terraform-provider-grafana#1184]
I am using the following resource to create multiple targets with the same job. 
```
resource "grafana_synthetic_monitoring_check" "private_https_check" {
  for_each          = { for index, kv in var.private_https_targets : "${kv.region}-${kv.env}-${kv.url}" => kv }
  provider          = grafana.synthetic_monitoring
  job               = "HTTPs checks"
  target            = each.value.url
  frequency         = each.value.frequency // max: 120000
  enabled           = each.value.enabled
  timeout           = 5000
  alert_sensitivity = each.value.alert_sensitivity
  probe = [/*ignore: picks probe ID based on the env and region*/]

  labels = {
    region    = each.value.region
    env       = each.value.env
    url       = each.value.url
    service   = each.value.service
    component = "synthetic-monitoring"
    type      = "https"
  }
  [ ... ]
}
```

Doing so leads to:
```
Error: check add request: status="409 Conflict", msg="Failed to add check to database", err="target/job combination already exists"
```
Presumably, only (target, job) tuple are accepted as a discriminator.

This use case seems rather limiting in GrafanaCloud as we want to be able to hit the same target from multiple monitoring clusters. And then use the same job name while creating our alert definition discriminating via labels `env`, `region` and `url`. However, SM seems to be rejecting the request.

**Comment by julienduchesne** [comment]
Why does it need to be the same job name? The job name doesn't affect the check itself. In any case, this is an API limitation so it should go in a support request. This is not something we can fix on the Terraform side, and if it were fixed on the API side, Terraform wouldn't require any changes to work

**Comment by ishworgurung** [comment]
> Why does it need to be the same job name? The job name doesn't affect the check itself. 

I just told you why we require it to be the same job name. We create the same job name for a _class_ of synthetic monitoring checks (*DNS Checks*, *HTTPs Checks*, and so on). It is moot to create a new job name for _every_ synthetic monitoring check too - how will it look like if I have 10K checks `x` 200 clusters `x` varying types of checks (ICMP, TLS, HTTP, DNS, etc..)?

Is there a best practice guide telling me we are deviating from it? i.e., use a unique job name for _every_ single job?

I filed enhancement here _because_ [Jeroen](https://github.com/Duologic) recommended opening a GH issue on Slack.

cc @Duologic

**Comment by ishworgurung** [comment]
> In any case, this is an API limitation so it should go in a support request.

If this is an API limitation, tell me that this feature has never been required by _any_ GrafanaCloud users? How sad.

**Comment by ishworgurung** [comment]
Yes, thanks for letting me file a support request. I shall do so now.
