### ISSUE TITLE
[Feature] Create Grafana On Call Schedules without a pre-existing iCal address

### ISSUE THREAD

**Issue by alekhrycaiko** [grafana/terraform-provider-grafana#1202]
Hi there!

I'd like to be able to provision Grafana on call schedules and configure them without having to spin up an iCal address before hand. It appears in the UI that it's possible to create a Grafana on call schedule without any pre-existing calendar links. Is something like this possible to add to the Terraform provider?

**Comment by julienduchesne** [comment]
👋 ICal is not a required attribute: https://registry.terraform.io/providers/grafana/grafana/latest/docs/resources/oncall_schedule

This should work:
```
// Shift based schedule
resource "grafana_oncall_schedule" "example_schedule" {
  name      = "Example Calendar Schadule"
  type      = "calendar"
  time_zone = "America/New_York"
  shifts = [
  ]
}
```

**Comment by alekhrycaiko** [comment]
Got it, thanks! Looks like I missed that detail. Appreciated 🙏
