### ISSUE TITLE
Terraform removes uid from config_json before create dashboard on Grafana

### ISSUE THREAD

**Issue by ghost** [grafana/terraform-provider-grafana#121]
### Terraform Version
```
➜  terraform -v
Terraform v0.13.4
```

### Affected Resource(s)
- grafana_dashboard

### Terraform Configuration Files

**my_dashboard.tpl**
```
➜  tail -5 my_dashboard.tpl
    "timezone":"browser",
    "title":"my dashboard",
    "uid":"JOUdHGZZz",
    "version":1
}
```

**grafana.tf**
```hcl
data "template_file" "dashboard" {
  template = file("${path.module}/templates/my_dashboard.tpl")
  vars = {
    DATASOURCE = var.grafana_datasource
  }
}

resource "grafana_dashboard" "main" {
  folder      = "my_folder"
  config_json = data.template_file.dashboard.rendered
  depends_on  = [data.template_file.dashboard]
}
```

### Debug Output
NA

### Panic Output
NA

### Expected Behavior
Have the same uid (JOUdHGZZz) on Grafana, so URL should be: 
https://abc.company.com/d/JOUdHGZZz/my-dashboard

### Actual Behavior
Grafana shows different uid, the dashboard URL is:
https://abc.company.com/d/dlhHPsFGk/my-dashboard

From Grafana [documentation](https://grafana.com/docs/grafana/latest/administration/provisioning/#dashboards) "_If the dashboard in the json file contains an uid, Grafana will force insert/update on that uid_". So, this mean that somehow Terraform is not sending the uid that I add on tpl (json).

From terraform-provider-grafana ([here](https://github.com/grafana/terraform-provider-grafana/blob/c9213b96af1692f2325bbdb8729a7fd2632d556d/grafana/resource_dashboard.go#L122)) I see that on function _prepareDashboardModel_ both, id and uid, are being removed from json before sending this data to Grafana. This justifies why Grafana is creating new uid..

```
func prepareDashboardModel(configJSON string) map[string]interface{} {
	configMap := map[string]interface{}{}
	err := json.Unmarshal([]byte(configJSON), &configMap)
	if err != nil {
		// The validate function should've taken care of this.
		panic(fmt.Errorf("Invalid JSON got into prepare func"))
	}

	delete(configMap, "id")
	// Only exists in 5.0+
	delete(configMap, "uid")
	configMap["version"] = 0

	return configMap
}
```

Is there any reason why uid is being removed? 

uid is being used for Grafana to build the URL.. any other alternatives? 

### Steps to Reproduce
Send uid on json

### Important Factoids
NA

### References
NA

**Comment by chelomontilla** [comment]
I'm facing same issue also, it's something basic, I can't link one dashboard with another because of this.

**Comment by Arola1982** [comment]
Same issue...

**Comment by trotttrotttrott** [comment]
Resolved in https://github.com/grafana/terraform-provider-grafana/pull/217
