### ISSUE TITLE
Merge notification policy with existing policy

### ISSUE THREAD

**Issue by akselleirv** [grafana/terraform-provider-grafana#1244]
Hello!

I want to add some new policies to an existing notification policy resource which has been created in the UI. But that would not be possible with the provider due to the existing notification policy would have been overridden as described in the [provider resource docs](https://registry.terraform.io/providers/grafana/grafana/latest/docs/resources/notification_policy).

A workaround would be to create a custom script which fetches the existing notification policy which is merged with my new policies. However, it would be nice to define this as a terraform resource.

Is this something that would be accepted by the project?

**Comment by julienduchesne** [comment]
You can import the existing notification policy, then do a terraform plan to see the diff between your definition and what's already there
