### ISSUE TITLE
`for: 0s` in alerts passes `tf plan`, but fails `tf apply` with `Error: unable to parse  as duration`

### ISSUE THREAD

**Issue by mpursley** [grafana/terraform-provider-grafana#1273]
### Terraform Version
* Terraform: latest
* Terraform Grafana Provider: latest
* Grafana: latest

### Affected Resource(s)
Please list the resources as a list, for example:
* grafana_rule_group

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
E.g. https://github.com/grafana/terraform-provider-grafana/issues/1215
```hcl
resource "grafana_rule_group" "example" {
  name             = "Example Rule Group"
  folder_uid       = grafana_folder.example.uid
  org_id           = 1
  interval_seconds = 60

  rule {
    name        = "Example Rule"
    condition   = "C"
    for         = "0s"
    dashboard_uid = "your_dashboard_uid_here"  # New attribute for specifying the dashboard UID

    data {
      ref_id = "A"
      # ... other configurations ...
    }
  }
}
```

### Debug Output
https://gist.github.com/mpursley/865135a58cfd3338e49189304bf4e823

### Panic Output
No.

### Expected Behavior
Seems like `for: 0s` should be ok?   (e.g. "fire immediately", as in https://community.grafana.com/t/grafana-alerting-evaluation/85064/5)

### Actual Behavior
`tf plan` passes, but `tf apply` fails with `Error: unable to parse  as duration`...

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. add an alert yaml file with `for: 0s`
2. `tf plan`, passes
3. `tf apply`, fails with `Error: unable to parse  as duration`

### Important Factoids
No.

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- https://github.com/grafana/terraform-provider-grafana/pull/1200
  - https://github.com/grafana/terraform-provider-grafana/pull/1200/files#diff-3ba89f7e59aad9a808dc7cb5f3cfe3b36171ba77fb28ea494339a24cc201fa39R349 
    - Was: `For:          json["for"].(string),`
    - Now: `For:          common.Ref(strfmt.Duration(forDuration)),`

**Comment by julienduchesne** [comment]
I've added a test with a `for: 0s` and it passes 🤔: https://github.com/grafana/terraform-provider-grafana/pull/1283

The error message: `Error: unable to parse  as duration` indicates that it's trying to parse an empty string but an empty string wouldn't pass the plan validation either

Are you testing with v2.8.1?

**Comment by edwardwu** [comment]
error on v2.8.1 (v2.7.0 and v2.6.0) - it's working fine on v2.5.0 

│ Error: unable to parse  as duration
│ 
│   with grafana_rule_group.my_rule_group,
│   on resources-rule-group.tf line 1, in resource "grafana_rule_group" "my_rule_group":
│    1: resource "grafana_rule_group" "my_rule_group" {

 
 sample ---
 resource "grafana_rule_group" "my_rule_group" {
    name = "My Alert Rules"
    folder_uid = grafana_folder.rule_folder.uid
    interval_seconds = 60
    org_id = 1

    rule {
        name = "My Random Walk Alert"
        condition = "C"
        for = "0s"

        // Query the datasource.
        data {
            ref_id = "A"
            relative_time_range {
                from = 600
                to = 0
            }
            datasource_uid = grafana_data_source.testdata_datasource.uid
            // `model` is a JSON blob that sends datasource-specific data.
            // It's different for every datasource. The alert's query is defined here.
            model = jsonencode({
                intervalMs = 1000
                maxDataPoints = 43200
                refId = "A"
            })
        }
    }

}

**Comment by pacoguzman** [comment]
This is happening to us too. If you need to validate something please let us know.

**Comment by svaraksin-gd** [comment]
Happens to me too
