### ISSUE TITLE
Missing data sources are not removed from state

### ISSUE THREAD

**Issue by normanlenzner5892** [grafana/terraform-provider-grafana#129]
Hi there,

the terraform provider 1.6.0 does not remove grafana data sources from the state and recreate them when they are removed from Grafana manually.

### Terraform Version
Terraform 0.12.26
Grafana Provider 1.6.0

### Affected Resource(s)
- grafana_data_source

### Terraform Configuration Files
```hcl
resource "grafana_data_source" "cloudwatch-live" {
  name = "CloudWatch-live"
  type = "cloudwatch"
  json_data {
    auth_type = "arn"
    default_region = "eu-central-1"
    assume_role_arn = "xxx"
  }
}

```

### Debug Output
https://gist.github.com/normanlenzner5892/5895417f9c7bdbce100953725178496d

### Panic Output
n/a

### Expected Behavior
Terraform removes the data sources from its state and recreates them in Grafana. The behavior is expected to be similiar to dashboards, where it still works.

### Actual Behavior
Terraform exits with an error and prints the HTTP 404 from the Grafana api for each data source:
Error: status: 404, body: {"message":"Data source not found"}

### Steps to Reproduce
1. Define a data grafana_data_source resource (can be reproduced with cloudwatch or prometheus)
2. `terraform apply`
3. Remove the datasource from Grafana manually
4. `terraform apply`

### Important Factoids
Still works with version 1.5.0

### References
n/a

**Comment by trotttrotttrott** [comment]
Thanks for opening this. I believe there's a few resources that behave this way. For the time being, you should be able to use `terraform state rm grafana_data_source.cloudwatch-live` as a workaround.

**Comment by Srokap** [comment]
I am seeing similar behavior for `grafana_alert_notification` resource

> grafana_alert_notification.msteams_alerts: Refreshing state... [id=1]
> (lines removed)
> Error: status: 404, body: {"message":"Alert notification not found"}

Started occurring after recreation of Grafana that wiped out all notification channels.

**Comment by wanieldilson** [comment]
> I am seeing similar behavior for `grafana_alert_notification` resource
> 
> > grafana_alert_notification.msteams_alerts: Refreshing state... [id=1]
> > (lines removed)
> > Error: status: 404, body: {"message":"Alert notification not found"}
> 
> Started occurring after recreation of Grafana that wiped out all notification channels.

Assuming you ran a t`erraform state rm grafana_notification_channel.your_channel_name`

Did you have further issues with dashboards following that?

**Comment by Srokap** [comment]
I did not have further issues after that. It was just unpleasant deviation from usual behavior by other providers that recreate resource if it's missing from target system.

**Comment by fenixcitizen** [comment]
Hi, I came across the same problem. Resolved by removing `grafana_data_source` from TF state manually but given the number of different data sources we might have it might be operational risk. Still works with `1.5.0` as mentioned above. Please prioritize the fix.

**Comment by fatbasstard** [comment]
Having the same issue when running Terraform after (manually) recreating a Grafana instance... Pretty annoying, would be nice if this can be fixed

**Comment by wanieldilson** [comment]
This PR https://github.com/grafana/terraform-provider-grafana/pull/178 is part of the way there...

**Comment by RyanW8** [comment]
Would anyone be able to verify a list of resources this is currently affecting? I can work on a PR to resolve this soon.

**Comment by julienduchesne** [comment]
Duplicate of https://github.com/grafana/terraform-provider-grafana/issues/172
