### ISSUE TITLE
Folder Permissions 400

### ISSUE THREAD

**Issue by JustNZ** [grafana/terraform-provider-grafana#1306]
### Terraform Version
* Terraform: 1.7.0
* Terraform Grafana Provider: 2.9.0
* Grafana: 10.3.1

### Affected Resource(s)
* grafana_folder_permissions

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "grafana_folder" "this" {
  title  = var.environment
  uid    = lower(var.environment)
  org_id = var.org_id
}

resource "grafana_folder_permission" "this" {
  folder_uid = grafana_folder.this.uid
  org_id     = var.org_id
  permissions {
    role       = "Editor"
    permission = "View"
  }
  permissions {
    team_id    = grafana_team.this.team_id
    permission = "View"
  }
  permissions {
    team_id    = var.default_teams["all"].team_id
    permission = "View"
  }
  permissions {
    team_id    = var.default_teams["this"].team_id
    permission = "View"
  }
  permissions {
    team_id    = var.default_teams["that"].team_id
    permission = "View"
  }
}
```

### Expected Behavior
Apply folder permissions

### Actual Behavior
At the beginning the apply of folder permissions works. But after a few of them processed it fails unexpectedly
```
module.grafana.module.env["1"].grafana_folder_permission.this: Creating...
module.grafana.module.env["2"].grafana_folder_permission.this: Creating...
module.grafana.module.env["3"].grafana_folder_permission.this: Creation complete after 2s [id=1:kn17]
module.grafana.module.env["4"].grafana_folder_permission.this: Creation complete after 2s [id=1:us01]
module.grafana.module.env["5"].grafana_folder_permission.this: Creation complete after 2s [id=1:de71]
module.grafana.module.env["6"].grafana_folder_permission.this: Creation complete after 2s [id=1:kn12]
╷
│ Error: [POST /access-control/{resource}/{resourceID}][400] setResourcePermissionsBadRequest  &{Error: Message:0xc00057d070 Status:}
│ 
│   with module.grafana.module.env["7"].grafana_folder_permission.this,
│   on /home/git/terraform/modules/grafana/modules/env/folder.tf line 15, in resource "grafana_folder_permission" "this":
│   15: resource "grafana_folder_permission" "this" {
│ 
╵
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. error during terraform apply

### Important Factoids
The Issue seems to not appear on versions lower than 2.9.0

**Comment by julienduchesne** [comment]
Hey! Can you try again with v2.10.0. It's not going to fix the issue, but the error message should show up now

**Comment by JustNZ** [comment]
Hey @julienduchesne ,
thanks for the fast response in first place.

So indeed there is now a clear message attached to the error but also doesn't say that much

```
 Error: [POST /access-control/{resource}/{resourceID}][400] setResourcePermissionsBadRequest {"message":"failed to set permissions"}
│ 
│   with module.grafana.module.env["7"].grafana_folder_permission.this,
│   on .terraform/modules/grafana/modules/grafana/modules/env/folder.tf line 15, in resource "grafana_folder_permission" "this":
│   15: resource "grafana_folder_permission" "this" {
│ 
```

**Comment by julienduchesne** [comment]
The error should be in your Grafana logs. Do you have access to those?

**Comment by JustNZ** [comment]
ah yeah good point - wasn't thinking about that.

Seems to be more or less with an issue of grafana itself
`msg="failed to set permissions" error="database is locked"`

**Comment by julienduchesne** [comment]
Seems to be an issue with 10.3.1 from what I saw. Using an actual DB (mysql or postgres) fixed it for me

**Comment by JustNZ** [comment]
Yeah seems so. Anyway so it's not a problem with this terraform module and I would close the issue. 

Thanks for your help
