### ISSUE TITLE
Unable to create Data Sources in Grafana Cloud

### ISSUE THREAD

**Issue by BobRoss5027** [grafana/terraform-provider-grafana#1340]
### Terraform Version
* Terraform: v1.5.7
* Terraform Grafana Provider: v2.11.0
* Grafana: v10.4.0

### Affected Resource(s)
Please list the resources as a list, for example:
* grafana_data_source

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
terraform {
  required_version = "~> 1.5"
  required_providers {
    grafana = {
      source = "grafana/grafana"
      version = "~> 2.11.0"
    }
  }
}

provider "grafana" {
  url  = "<URL>"
  auth = "<Service Account Token>"
}

resource "grafana_data_source" "data_source" {
  type = "cloudwatch"
  name = "test"

  json_data_encoded = jsonencode({
    defaultRegion: "eu-west-2",
    authType: "keys",
    assumeRoleArn: "aws_role_arn"
  })
  secure_json_data_encoded = jsonencode({
    accessKey: "accessKey"
    secretKey: "secretKey"
  })
}
```

### Debug Output
https://gist.github.com/BobRoss5027/689fb5e7a5b5d7e44ef66c913bac248d

### Expected Behavior
Deployment of a Data Source

### Actual Behavior
Terraform errors out after apply, showing the following message:
```hcl
╷
│ Error: json: cannot unmarshal array into Go value of type models.AddDataSourceOKBody
│ 
│   with grafana_data_source.data_source,
│   on main.tf line 38, in resource "grafana_data_source" "data_source":
│   38: resource "grafana_data_source" "data_source" {
│ 
╵
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by julienduchesne** [comment]
Strange, I tried with Grafana 10.3.2 locally with an SA and the admin user and on Grafana Cloud (10.4) with an SA and it worked 🤔
