### ISSUE TITLE
Improve documentation for elasticsearch data source

### ISSUE THREAD

**Issue by spuder** [grafana/terraform-provider-grafana#135]
Terraform 0.13

Currently it does not appear to be possible to add an elasticsearch `grafana_data_source` and modify the elasticsearch details

Manually configured details

<img width="842" alt="Screen Shot 2020-11-03 at 12 20 55 PM" src="https://user-images.githubusercontent.com/242382/98031134-5071c080-1dcf-11eb-87aa-afc446fb4470.png">

Terraform configured details

<img width="872" alt="Screen Shot 2020-11-03 at 12 36 50 PM" src="https://user-images.githubusercontent.com/242382/98032527-5ff20900-1dd1-11eb-8fb3-eadef7911af9.png">

|Elasticsearch Name | Terraform Name |
|---|---| 
| Index Name| database_name  |
| Pattern | interval | 
| Time field Name | time_field|
| Version | es_version|
| Min Time Interval | time_interval |

```
resource "grafana_data_source" "foobar" {
  type          = "elasticsearch"
  name          = "foobar"
  url           = "https://logyardro.example.com"
 database_name = "[logstash-]YYYY.MM.DD"
  json_data     {
        interval      = "Daily"
        time_field    = "@timestamp"
        es_version    = "56"
        time_interval = "11s"
  }
}
```

https://registry.terraform.io/providers/grafana/grafana/latest/docs/resources/data_source

It is not clear that `database_name` maps to `index name`. Also when specifying database_name, then `json_data.interval` is not needed.

**Comment by spuder** [comment]
For anyone else running into inconsistencies with `database_name` and `json_data.interval`. I've found it best to ignore the `interval` and just use a wildcard in the `database_name`

```
resource "grafana_data_source" "logyard-qa" {
  type          = "elasticsearch"
  name          = "logyardro.example.com"
  url           = "https://logyardro.example.com"
  database_name = "logstash-*"
  is_default    = false
  json_data     {
        time_field    = "@timestamp"
        es_version    = "5"
        time_interval = "10s"
  }
}
```

**Comment by apr-1985** [comment]
I have raised a PR to fix the interval issue
https://github.com/grafana/grafana-api-golang-client/pull/23
Not sure when/if it will get picked up as the repo is deprecated other than for fixes for the terraform provider (which this is)

**Comment by inkel** [comment]
Thank you all for your interest. While I understand your request, I believe this is actually information that belongs in the [Elasticsearch datasource documentation](https://grafana.com/docs/grafana/latest/datasources/elasticsearch/) and not for this provider. Grafana dozens of [different data sources](https://grafana.com/grafana/plugins/?type=datasource) and not only it would be impractical to list all the different mappings in the Terraform provider documentation but also out of the scope of what this documentation shows.

Thanks for understanding.
