### ISSUE TITLE
500 error after change on SA variable is_disabled

### ISSUE THREAD

**Issue by jsthibault** [grafana/terraform-provider-grafana#1354]
### Terraform Version
* Terraform: v1.2.4
* Terraform Grafana Provider: 2.11.0
* Grafana: grafana cloud

### Affected Resource(s)
Please list the resources as a list, for example:
* grafana_cloud_stack_service_account

### Terraform Configuration Files
```hcl
resource "grafana_cloud_stack_service_account" "cloud_sa" {
  provider     = grafana.cloud
  stack_slug = "xxxxxx"

  name           = "TESTcloud service account"
  role              = "Admin"
  is_disabled = true
}

resource "grafana_cloud_stack_service_account_token" "cloud_sa" {
  provider   = grafana.cloud
  stack_slug = "xxxxxxxx"

  name               = "my_stack cloud_sa key"
  service_account_id = grafana_cloud_stack_service_account.cloud_sa.id
}
```

### Debug Output
https://gist.github.com/jsthibault/439922ae3dd0632a26d7a8e31a57dbe2

### Expected Behavior

I set the is_disabled variable to 'false' after an initial 'apply' to 'true' and it produced a 500 error for me. I expected it to enable my SA

### Actual Behavior
The SA is still disable

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply` with is_disabled to true
2. `terraform apply` with is_disabled to false

**Comment by julienduchesne** [comment]
Did you try more than once?

**Comment by jsthibault** [comment]
Yes, 4 or 5 times

**Comment by julienduchesne** [comment]
👍 . I'll test it out
