### ISSUE TITLE
Add Pyrscope URL and username to grafana_cloud_stack resource attributes

### ISSUE THREAD

**Issue by Alex3k** [grafana/terraform-provider-grafana#1357]
Much like for prometheus_url, prometheus_user, traces_url, traces_user, logs_url and logs_user it would be great to include pyroscopes username and url in the mix also.

**Comment by julienduchesne** [comment]
Already there. Will be in the next release: https://github.com/grafana/terraform-provider-grafana/blob/main/internal/resources/cloud/resource_cloud_stack.go#L136-L139
