### ISSUE TITLE
Add OTLP endpoint to the grafana_cloud_stack resource attributes

### ISSUE THREAD

**Issue by Alex3k** [grafana/terraform-provider-grafana#1358]
Much like for prometheus_url, prometheus_user, traces_url, traces_user, logs_url and logs_user it would be great to include the OTLP endpoint username and url in the mix also.

**Comment by patst** [comment]
@julienduchesne  sorry for commenting on a closed issue.

the issue creator asked for the `username` for otlp as well. As far as I understand that part is still missing. Any idea if it is easy to be added as well?

**Comment by julienduchesne** [comment]
The OTLP username is the stack ID: `grafana_cloud_stack.<name>.id`

**Comment by julienduchesne** [comment]
Documented here: https://github.com/grafana/terraform-provider-grafana/pull/1636

**Comment by patst** [comment]
> Documented here: #1636

thanks for the super fast response and added docs!
