### ISSUE TITLE
Allow Machine Learning to be Initialized from Terraform

### ISSUE THREAD

**Issue by SeamusGrafana** [grafana/terraform-provider-grafana#1363]
Allow Machine Learning to be Initialized from Terraform

Currently, if you deploy a new GrafanaCloud Stack and Machine Learning Resources at the same, the Machine Learning resources will fail to be applied and you get the below;

```
╷
│ Error: status: 400, body: apiKey not set. Have you initialized the ML plugin?
│ 
│   with module.grafana_supportlab_cloud_stack.grafana_machine_learning_job.ml_usage_dashboard_count,
│   on ../../../../as-code/terraform/modules/grafana_supportlab_cloud_stack/ml_grafanacloud_usage.tf line 48, in resource "grafana_machine_learning_job" "ml_usage_dashboard_count":
│   48: resource "grafana_machine_learning_job" "ml_usage_dashboard_count" {
│ 
╵
```

It would be great if there was a Resource to allow Machine Learning to be Initialized, similar to the one for Synthetic Monitoring as currently, this requires manual intervention on an initial stack creation.

**Comment by julienduchesne** [comment]
This now works!
