### ISSUE TITLE
Allow Grafana SLO to be Initialized from Terraform

### ISSUE THREAD

**Issue by SeamusGrafana** [grafana/terraform-provider-grafana#1364]
Allow Grafana SLO to be Initialized from Terraform

Currently, if you deploy a new GrafanaCloud Stack and Grafana SLO Resources at the same, the SLO resources will fail to be applied and you get the below;

```
╷
│ Error: Unable to create SLO - API
│ 
│   with module.grafana_supportlab_cloud_stack.grafana_slo.slo-synthetics-reachability,
│   on ../../../../as-code/terraform/modules/grafana_supportlab_cloud_stack/slo_synthetics.tf line 1, in resource "grafana_slo" "slo-synthetics-reachability":
│    1: resource "grafana_slo" "slo-synthetics-reachability" {
│ 
│ Post "https://srtlabdevnew.grafana.net/api/plugins/grafana-slo-app/resources/v1/slo": POST
│ https://srtlabdevnew.grafana.net/api/plugins/grafana-slo-app/resources/v1/slo giving up after 4 attempt(s)
```

Its not clear that this is because SLO has not yet been initialized, but once its Initialized, it works as expected and the changes applied.

It would be great if there was a Resource to allow SLO to be Initialized, similar to the one for Synthetic Monitoring as currently, this requires manual intervention on an initial stack creation.

**Comment by julienduchesne** [comment]
This now works, with a caveat. The SLOs can be written with TF right after the stack is created but they will only be visible in the UI after the user clicks to initialize the plugin
