### ISSUE TITLE
Issue with Datasource JSON Data that contains HTTP Headers

### ISSUE THREAD

**Issue by SeamusGrafana** [grafana/terraform-provider-grafana#1369]
### Terraform Version
* Terraform: 1.7.3
* Terraform Grafana Provider: 2.11.0
* Grafana: Cloud (V10 and v11)

### Affected Resource(s)
* grafana_data_source

### Terraform Configuration Files
```hcl
resource "grafana_data_source" "ds-influx-influxql" {
  provider = grafana

  type                = "influxdb"
  name                = "InfluxDB v2 + InfluxQL (Demo)"
  basic_auth_enabled  = false
  basic_auth_username = "REDACTED"
  url                 = "REDACTED"
  uid                 = "influx-2-influxql"
  username            = "REDACTED"
  json_data_encoded = jsonencode({
    dbName          = "grafana"
    httpHeaderName1 = "Authorization"
    httpMode        = "GET"
  })
  secure_json_data_encoded = jsonencode({
    basicAuthPassword = var.ds-play-influx-password
    httpHeaderValue1  = var.ds-play-influx-token-in-header
  })
}
```

### Apply / Plan Output

```text
  # module.grafana_supportlab_shared.grafana_data_source.ds-influx-influxql will be updated in-place
  ~ resource "grafana_data_source" "ds-influx-influxql" {
        id                       = "1:65"
      ~ json_data_encoded        = jsonencode(
          ~ {
              + httpHeaderName1 = "Authorization"
                # (2 unchanged attributes hidden)
            }
        )
        name                     = "InfluxDB v2 + InfluxQL (Demo)"
        # (10 unchanged attributes hidden)
    }
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

Grafana Labs internal only for now.

Relevant Snippet;

```
2024-02-23T11:56:23.984Z [WARN]  Provider "registry.terraform.io/grafana/grafana" produced an unexpected new value for module.grafana_supportlab_shared.grafana_data_source.ds-influx-influxql during refresh.
      - .json_data_encoded: was cty.StringVal("{\"dbName\":\"grafana\",\"httpHeaderName1\":\"Authorization\",\"httpMode\":\"GET\"}"), but now cty.StringVal("{\"dbName\":\"grafana\",\"httpMode\":\"GET\"}")
2024-02-23T11:56:23.987Z [WARN]  Provider "registry.terraform.io/grafana/grafana" produced an invalid plan for module.grafana_supportlab_shared.grafana_data_source.ds-influx-influxql, but we are tolerating it because it is using the legacy plugin SDK.
```

### Panic Output

None

### Expected Behavior
What should have happened?

After the initial `terraform apply`, running another `terraform apply` (or `terraform plan`) should not show any changes.

### Actual Behavior
What actually happened?

Everytime I run a `terraform apply` (or `terraform plan`) it shows this as to be changed, even though nothing has changed in the Terraform Configuration and all previous `terraform apply` commands complete sucessfully.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:

1. Create a TF Config with a Datasource
2. Add some `json_data_encoded` block
3. Add a `httpHeaderName1` Key with any string value
4. Run `terraform apply`
5. Run `terraform plan`

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

I can see the JSON (from the Grafana API) and it shows the correct Header Values there;

![image](https://github.com/grafana/terraform-provider-grafana/assets/102023327/1740ac49-c01a-4ebc-847f-85570e59f86d)

Running `terraform apply -auto-approve && terraform plan` shows a successful apply, but in the plan it still show the change to be made.

From my testing this, only happens with the `httpHeaderName1` or `httpHeaderName2` values, everything else works as expected.

The Datasource type has no bearing either, this happens with Discourse, Influx, Infinity and others.

The `json_data_encoded` looks correct in the terraform state file

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:

None

**Comment by julienduchesne** [comment]
Have you tried using the `http_headers` attribute: https://registry.terraform.io/providers/grafana/grafana/latest/docs/resources/data_source#http_header?

We extract the headers in TF because there's no way that most users would figure it out

**Comment by SeamusGrafana** [comment]
Thanks @julienduchesne 

No, I have not tried that, looking at that it says its a map of strings.

Do you have an example of how it would look? Do I need to specify a Header Name and Value for that, then Header Value and Value for that, or is there some other way of doing it.

> We extract the headers in TF because there's no way that most users would figure it out

Thats interesting, do we do anything else like this, as quite often the advice I have given is to view the Datasource API and anything under `jsonData` put there, and same for `secureJsonData` as I agree its not easy for most to figure out. So want to make sure I dont get caught out by other things like this (and dont suggest something that may be wrong).

Also, if we extract it, why does it still successfully add it initially, should it not add it at all?

Thanks

**Comment by julienduchesne** [comment]
> Thats interesting, do we do anything else like this

No. I think that's the only case

> Also, if we extract it, why does it still successfully add it initially, should it not add it at all?

On read, we extract it from the response. On write, we take the http headers from the `http_headers` map and merge that with the jsonData, so it doesn't prevent someone from manually writing some header values in there.

What the resource needs is to either:
- Support either way
- Add validation that no one sets `httpHeaderName...` settings in their TF config json data
