### ISSUE TITLE
Error on upgrade from 2.11.0 to 2.12.0

### ISSUE THREAD

**Issue by jessemyers-lettuce** [grafana/terraform-provider-grafana#1375]
### Terraform Version
* Terraform: `1.7.4`
* Terraform Grafana Provider: `2.11.0`
* Grafana: n/a

### Affected Resource(s)
- provider
 
### Terraform Configuration Files
```hcl
terraform {
  required_providers {
    grafana = {
      source  = "grafana/grafana"
      version = "2.12.0"
    }
  }
}

provider "grafana" {
  auth = var.grafana_cloud_api_key
  url  = var.grafana_cloud_api_url
}
```

### Debug Output

https://gist.github.com/jessemyers-lettuce/55acb4f1285a2673f7b841a945c36987

### Panic Output

n/a/

### Expected Behavior

A plan should be produced.

### Actual Behavior

Terraform errors out with:

```
Planning failed. Terraform encountered an error while generating this plan.
╷
│ Error: Value Conversion Error
│
│   with provider["registry.terraform.io/grafana/grafana"],
│   on providers.tf line 38, in provider "grafana":
│   38: provider "grafana" {
│
│ An unexpected error was encountered trying to convert tftypes.Value into
│ provider.frameworkProviderConfig. This is always an error in the provider.
│ Please report the following to the provider developer:
│
│ mismatch between struct and object: Object defines fields not found in
│ struct: cloud_api_key.
╵
Operation failed: failed running terraform plan (exit 1)
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`

### Important Factoids

We are running through Terraform Cloud.

### References

None that I could find.

**Comment by julienduchesne** [comment]
Fixed in v2.12.1
