### ISSUE TITLE
Unsupported attribute dashboard_id

### ISSUE THREAD

**Issue by dmytro-zhernosiekov-rft** [grafana/terraform-provider-grafana#138]
### Terraform Version
```
$> terraform -v
Terraform v0.13.4
+ provider registry.terraform.io/grafana/grafana v1.6.0
```

### Affected Resource(s)
- Grafana provider
- grafana_dashboard resource

### Terraform Configuration Files
```hcl

data "template_file" "team-dashboard" {
  template = file("${path.module}/templates/team-dashboard.yml.tpl")
  vars = {
    environment       = var.environment
    monitoring_suffix = local.monitoring_suffix
    base_domain       = var.base_domain
    commit_hash       = var.commit_hash
  }
}

resource "grafana_dashboard" "team" {
  config_json = data.template_file.team-dashboard.rendered
}

data "template_file" "main-dashboard" {
  template = file("${path.module}/templates/main-dashboard.yml.tpl")
  vars = {
    environment       = var.environment
    monitoring_suffix = local.monitoring_suffix
    base_domain       = var.base_domain
    commit_hash       = var.commit_hash
    team_dashboard_id = grafana_dashboard.team.dashboard_id
  }
  depends_on = [grafana_dashboard.team]
}

resource "grafana_dashboard" "main" {
  config_json = data.template_file.main-dashboard.rendered
  depends_on = [grafana_dashboard.team]
}

```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
```
Error: Unsupported attribute

  on modules/dashboards/main.tf line 76, in data "template_file" "concourse-main-dashboard":
  76:     team_dashboard_id = grafana_dashboard.team.dashboard_id

This object has no argument, nested block, or exported attribute named
"dashboard_id".
```
### Expected Behavior
Add link to newly created dashboard ID in link section:
```
          "links": [
            {
              "targetBlank": true,
              "title": "Team details",
              "url": "/d/${team_dashboard_id}/team-dashboard-copy?team=$${__data.fields.team}&var-team=$${__data.fields.team}"
            }
```

### Actual Behavior
Terraform produce error:
```
Error: Unsupported attribute

  on modules/dashboards/main.tf line 76, in data "template_file" "concourse-main-dashboard":
  76:     team_dashboard_id = grafana_dashboard.team.dashboard_id

This object has no argument, nested block, or exported attribute named
"dashboard_id".
```
dashboard_id is useless for future usage. Could you please add dashboard UID. UID could be used as link inside one dashboard to another.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan

**Comment by dmytro-zhernosiekov-rft** [comment]
Hello. Did someone check this issue? `dashboard_id` announced in terraform resource documentation:
https://registry.terraform.io/providers/grafana/grafana/latest/docs/resources/dashboard#dashboard_id

**Comment by dmytro-zhernosiekov-rft** [comment]
Hi.
Found that I used stable version ( 1.3.6) and this version does not have `dashboard_id`. I set latest version and this attribute is present, but instead of dashboard uid (for example in Grafana UI it is hsyS1tTGk), `grafana_dashboard.team.dashboard_id` equal to 23

**Comment by dmytro-zhernosiekov-rft** [comment]
Here is my test code and result:
```
resource "grafana_dashboard" "temp" {
  config_json = "${file("temp.json")}"
}


resource "null_resource" "dashboard_id" {
  provisioner "local-exec" {
    command = "echo enabled=${grafana_dashboard.temp.dashboard_id}"
  }
}
```
Then `terrafrom apply`:
```
....
null_resource.dashboard_id (local-exec): Executing: ["/bin/sh" "-c" "echo enabled=43"]
....
```

**Comment by dmytro-zhernosiekov-rft** [comment]
Hi, updated Grafana provider to `1.7.0` and it found `dashboard_id` external attribute, but this is not dashboard **UID**, this is just number of dashboard in Grafana. So if it 1st dashboard - it will be 1, second - 2. UID alway looks like `Uc73nFdiR6`

**Comment by dmytro-zhernosiekov-rft** [comment]
Hi. Updated main text. Dashboard ID is useless, but with UID it's possible to create redirect link inside dashboard. Could you please add UID to Grafana Terraform provider.

**Comment by trotttrotttrott** [comment]
`uid` property added in https://github.com/grafana/terraform-provider-grafana/pull/217
