### ISSUE TITLE
Grafana Datasource Cloudwatch ARN missing attributes

### ISSUE THREAD

**Issue by fotto1** [grafana/terraform-provider-grafana#14]
### Terraform Version
Terraform v0.11.2
+ provider.grafana v1.0.1

### Affected Resource(s)
- grafana_data_source

### Terraform Configuration Files
```hcl
resource "grafana_data_source" "dev_datasourcees" {

  name = "terraform-test"
  type = "cloudwatch"
  url = "arn:aws:iam:::role/myrole"
  access_mode = "proxy"

  basic_auth_enabled = false
  is_default = false

  json_data {
    auth_type = "arn"
    default_region = "eu-central-1"
  }

}
```
The code is working and the grafana datasource will be created but I'm not able to set the following parameters:

- assumeRoleARN - Role which should be used
- orgId - ID of the Organisation in Grafana
- customMetrics - Namespaces of the Custom Metrics

![image](https://user-images.githubusercontent.com/12606402/35581730-fc1a04c2-05ec-11e8-895c-d1a39406cf13.png)

I use a grafana version 4.6.3

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. create a provider with Grafana and credentials
2. `terraform apply`

**Comment by fotto1** [comment]
Any progress?

**Comment by pearkes** [comment]
There is a PR over on #16 that is looking good to resolve this.

**Comment by fotto1** [comment]
Sounds good - I keep that ticket open until PR16 is closed https://github.com/terraform-providers/terraform-provider-grafana/pull/16

**Comment by pearkes** [comment]
This is fixed https://github.com/terraform-providers/terraform-provider-grafana/compare/8f8511728f112dade6fcaf5a97656a2ccdde9b89...master.

**Comment by jsboeve** [comment]
For anyone else who stumbles on this looking for a solution:  json_data was deprecated and replaced with json_data_encoded which seems to require camel case to work properly.

If you want to use assume_role_arn you need to use camel case "assumeRoleArn" within the json_data_encoded field:

`json_data_encoded = jsonencode({
        assumeRoleArn = {arn}})`

**Comment by LuisRodri21** [comment]
I think the documentation is not updated with this change.
