### ISSUE TITLE
Unable to define maximum lines for grafana_data_source type Loki

### ISSUE THREAD

**Issue by tomweston** [grafana/terraform-provider-grafana#144]
Hi,

We have a requirement for multiple Loki datasources to be defined in our Grafana environments. Default Values for the Loki Datasource work but we are not able to specify the number of max lines via the terraform grafana_data_source.

Unable to define maximum lines for grafana_data_source type Loki

### Terraform Version
Terraform v0.12.28

### Affected Resource(s)
- grafana_data_source

There does not appear to be an matching parameter defined in the json_data types:

[ json_data_parameters](https://github.com/grafana/terraform-provider-grafana/blob/master/grafana/resource_data_source.go#L52-L157)

### Terraform Configuration Files
```hcl

resource "grafana_data_source" "prod_loki_stack_5K" {
  type       = "loki"
  name       = "Loki-5K"
  url        = "<loki-url>l:3100"
  json_data {
    <no_available_parameter>= "5000"
  }
}
```

### Expected Behavior
A Loki Datasource should be created with a maximum number of lines configured via the terraform resource

**Comment by julienduchesne** [comment]
This is now supported in v1.20.0
