### ISSUE TITLE
[Bug]: Duplicate PDFs when configuring report formats

### ISSUE THREAD

**Issue by jdgeisler** [grafana/terraform-provider-grafana#1440]
### Terraform Version

1.6.6

### Terraform Grafana Provider Version

2.14.1

### Grafana Version

10.3.1

### Affected Resource(s)

* grafana_report

### Terraform Configuration Files

```hcl 
resource "grafana_report" "report" {
  name          = "report"
  formats       = ["pdf", "image"]
  ...
```

### Expected Behavior

The report should be created in grafana for only `pdf` and `image`. When the report email is sent, it should only attach the pdf of the dashboard once.

### Actual Behavior

In Grafana, you can see that PDF is listed twice as the report format. In the resulting email that is sent, the PDF of the dashboard is attached twice.

![Screenshot 2024-03-22 at 10 27 56 AM](https://github.com/grafana/terraform-provider-grafana/assets/81592430/469ef152-4f68-42ae-bdc0-e92c12c81258)

<img width="571" alt="Screenshot 2024-03-22 at 1 22 31 PM" src="https://github.com/grafana/terraform-provider-grafana/assets/81592430/92ca0399-7481-47d8-a3cd-487ebc8f1157">

### Steps to Reproduce

1. Set `formats` to the following in the `grafana_report` resource
```hcl
formats      = ["pdf", "image"]
```
2. Terraform apply
3. Check the report in Grafana and confirm that `PDF` is set twice
4. Check the email sent from the report and confirm that there are two PDF attachments

**Comment by jdgeisler** [comment]
Awesome, thanks for the quick fix @julienduchesne! Will there be a release for this soon?

**Comment by julienduchesne** [comment]
Next week, got a few things to wrap up that have to be done before a release can be cut
