### ISSUE TITLE
Feature Request: secureFields support for alert_notification resource

### ISSUE THREAD

**Issue by mtanda** [grafana/terraform-provider-grafana#147]
### Terraform Version
```
❯ terraform -v
Terraform v0.14.2
```

### Affected Resource(s)
- grafana_alert_notification

Currently, alert_notification doesn't support secureFields.
https://registry.terraform.io/providers/grafana/grafana/latest/docs/resources/alert_notification

It is important to protect credentials, I think terraform provider support is beneficial for Grafana administrator.
https://github.com/grafana/grafana/issues/25113

**Comment by nouseforaname** [comment]
We wanted this too and added a very basic PR since the Provider and upstream golang client are under construction
https://github.com/grafana/terraform-provider-grafana/pull/161

**Comment by inkel** [comment]
`secureSettings` is now an [optional attribute](https://registry.terraform.io/providers/grafana/grafana/latest/docs/resources/alert_notification#optional) when declaring an `alert_notification`.
