### ISSUE TITLE
[Feature Request]: add the ability to update organizations without importing existing ones

### ISSUE THREAD

**Issue by AkakievKD** [grafana/terraform-provider-grafana#1483]
### Feature Request

add the ability to update existing organizations without importing existing ones in rgrafana_organization (Resource)

**Comment by julienduchesne** [comment]
Can you expand on what you want. How would that look like? What would be the TF definition like? How would Terraform behave?

**Comment by AkakievKD** [comment]
i mean manage existing resource without importing in module or main.tf if it's possible of course

**Comment by julienduchesne** [comment]
You can use an `import { }` block and then you don't have to use `terraform import`. You can just `terraform plan` and `terraform apply`, pointing to an existing organization

Example:
```
resource "grafana_organization" "test" {
  name         = "Test Organization"
}

import {
  to = grafana_organization.test
  id = "123"
}
```

**Comment by AkakievKD** [comment]
thanks
