### ISSUE TITLE
[Bug]: 500 Internal Server Error when `grafana_service_account.role` is omitted

### ISSUE THREAD

**Issue by hertzsprung** [grafana/terraform-provider-grafana#1493]
### Terraform Version

1.6.2

### Terraform Grafana Provider Version

2.17.0

### Grafana Version

11 (Grafana Cloud)

### Affected Resource(s)

* grafana_service_account

### Terraform Configuration Files

```hcl
resource "grafana_service_account" "my_service_account" {
  name = "test"
  lifecycle {
    // ignore_changes = [role] // avoids HTTP 500 error
  }
}
```

### Expected Behavior

No change

### Actual Behavior

Error: status: 500, body: {"error":"Server Error","message":"Internal Server Error - Please try again. If the issue persists please open a support ticket that notes the time in UTC."}

### Steps to Reproduce

`terraform apply` twice, the second time fails

### Important Factoids

On the second `terraform apply`, I would expect to see "None" or "No Basic Role" instead of "Viewer" 
```
resource "grafana_service_account" "annotations" {
        id          = "1:155"
        name        = "test"
      - role        = "Viewer" -> null
        # (2 unchanged attributes hidden)
    }
```

**Comment by hertzsprung** [comment]
Explicitly setting `role = "None"` gives the same 500 error (on Grafana Cloud, which I believe is running Grafana 11 as of April 2024).  So I'm unsure that #1495 will help here.

**Comment by julienduchesne** [comment]
> Explicitly setting `role = "None"` gives the same 500 error (on Grafana Cloud, which I believe is running Grafana 11 as of April 2024). So I'm unsure that #1495 will help here.

Let me test that 👀

**Comment by julienduchesne** [comment]
> Explicitly setting `role = "None"` gives the same 500 error (on Grafana Cloud, which I believe is running Grafana 11 as of April 2024). So I'm unsure that #1495 will help here.

Very strange, is that on a fresh resource or on an update?

**Comment by julienduchesne** [comment]
Found the problem: https://github.com/grafana/terraform-provider-grafana/pull/1503

**Comment by hertzsprung** [comment]
> > Explicitly setting `role = "None"` gives the same 500 error (on Grafana Cloud, which I believe is running Grafana 11 as of April 2024). So I'm unsure that #1495 will help here.
> 
> Very strange, is that on a fresh resource or on an update?

Updating an existing resource (I've not had a chance to try with a fresh resource).
