### ISSUE TITLE
Grafana 5.0 Dashboard Support

### ISSUE THREAD

**Issue by repl-mike-roest** [grafana/terraform-provider-grafana#15]
### Terraform Version
Terraform v0.11.1
### Affected Resource(s)
Please list the resources as a list, for example:
grafana_dashboard
### Terraform Configuration Files
Grafana has added a new uid field in the dashboard JSON spec (http://docs.grafana.org/reference/dashboard/) which is a user specified string id.  If not provided externally the system will generate one.  This causes a dashboard created via terraform to be recreated everytime if it's not provided, a precondition failed error if the value is left in from an export and multiple instances of our module are included, to handle this we've added a random_string resource and used that to provide the uid via a tempalte so that multiple instances of our module still work.

Ideally the behaviour of the UID field would be handled by the provider similar to how id is handled.
https://github.com/terraform-providers/terraform-provider-grafana/blob/master/grafana/resource_dashboard.go#L96
https://github.com/terraform-providers/terraform-provider-grafana/blob/master/grafana/resource_dashboard.go#L124

Thanks

**Comment by pearkes** [comment]
Should be fixed in #17, please take a look!
