### ISSUE TITLE
Repeated updates to uid in 1.8.0

### ISSUE THREAD

**Issue by alekhrycaiko** [grafana/terraform-provider-grafana#151]
Hi there, I've been having repeated updates to my uid value that are not being resolved upon a successful plan/apply cycle. I've added some details below.

### Terraform Version
0.13.5

### Affected Resource(s)
- grafana_dashboard

### Expected Behavior
- No resources should be planned.

### Actual Behavior
- Repeated update to `config_json` in all `grafana_dashboard` resources.
- `uid` repeatedly updated from a random value  to one we've set internally. For example `uid = "cBfIXcfAk" -> "some-internal-name"`
- Regardless of the number of times I apply this update, this issue reoccurs on latest Grafana.

A downgrade from v.1.8.0 to v.1.7.0 resolved the above issue, and no changes occur in my plan.

**Comment by trotttrotttrott** [comment]
@alekhrycaiko thanks for opening this. 1.8.1 was just released with a fix.
