### ISSUE TITLE
[Bug]: tf plan suggests changes in grafana_contact_point in every run after apply

### ISSUE THREAD

**Issue by evertonspader-tomtom** [grafana/terraform-provider-grafana#1525]
### Terraform Version

v1.8.0

### Terraform Grafana Provider Version

v2.18.0

### Affected Resource(s)

* grafana_contact_point

### Terraform Configuration Files

```hcl
resource "grafana_contact_point" "pd_alert" {
  name = "Team - PD"
  pagerduty {
    integration_key = var.pd_key
    settings = {
       # ...
    }
  }
}
```

### Expected Behavior

No changes in `tf plan` output after resources have been provisioned

### Actual Behavior

In every plan run, all `grafana_contact_point` resources are set to have changes be applied:
```hcl
# grafana_contact_point.pd_alert will be updated in-place
  ~ resource "grafana_contact_point" "pd_alert" {
        id                 = "Team - PD"
        name               = "Team - PD"
        # (2 unchanged attributes hidden)

      - pagerduty {
          # At least one attribute in this block is (or was) sensitive,
          # so its contents will not be displayed.
        }
      + pagerduty {
          # At least one attribute in this block is (or was) sensitive,
          # so its contents will not be displayed.
        }
    }
```

### Steps to Reproduce

```shell
terraform plan
terraform apply -auto-approve
```
Then after resources are provisioned, re-run the commands

**Comment by julienduchesne** [comment]
Is this on Grafana Cloud and is this still happening? I've tried to reproduce it on Grafana 10 and 11 (Cloud) and I'm unable to do so

**Comment by julienduchesne** [comment]
Closing because I'm unable to reproduce, and this may be resolved with the new major version. I'd recommend you try that one. Feel free to re-open if this is still happening!
