### ISSUE TITLE
[Feature Request]: Allow defining Folder for SLOs

### ISSUE THREAD

**Issue by domdepasquale** [grafana/terraform-provider-grafana#1527]
### Feature Request

Could the provider be updated to support defining the Folder the SLO dashboard will live in? I see it's currently available in the API Spec https://grafana.com/docs/grafana-cloud/alerting-and-irm/slo/api/slo-api.yaml

Thanks!

**Comment by inikotoran** [comment]
I'm working on this: https://github.com/grafana/terraform-provider-grafana/pull/1553
