### ISSUE TITLE
[Feature Request]: Officially submit provider gpg key to OpenTofu Registry

### ISSUE THREAD

**Issue by jkroepke** [grafana/terraform-provider-grafana#1544]
### Feature Request

Running this provider with opentofu results into a verification warning:

```
Initializing provider plugins...
- Finding grafana/grafana versions matching "2.18.0"...
- Installing grafana/grafana v2.18.0...
- Installed grafana/grafana v2.18.0. Signature validation was skipped due to the registry not containing GPG keys for this provider
```

If possible, please submit the public gpg key to the [opentofu registry](https://github.com/opentofu/registry/).

**Comment by julienduchesne** [comment]
PR submitted here: https://github.com/opentofu/registry/pull/461

**Comment by julienduchesne** [comment]
v2.19.0 and + will be signed

**Comment by julienduchesne** [comment]
hmm, actually it synced all releases. They are all signed!
