### ISSUE TITLE
Error importing folders

### ISSUE THREAD

**Issue by askthedust** [grafana/terraform-provider-grafana#156]
Hi there,

```
Terraform v0.12.28
+ provider.grafana v1.8.1
```

## Resource used
```
provider "grafana" {
  url    = var.url
  org_id = var.org_id
}

resource "grafana_folder" "this" {
  for_each = toset(var.folders)
  title = each.key
}
```
## the error appears when importing a folder:
`terraform import 'module.grafana_org_prod.grafana_folder.this["folder_name"]' 332`

## error:
```
module.grafana_org_prod.grafana_folder.this["folder_name"]: Importing from ID "332"...
module.grafana_org_prod.grafana_folder.this["folder_name"]: Import prepared!
  Prepared grafana_folder for import
module.grafana_org_prod.grafana_folder.this["folder_name"]: Refreshing state... [id=332]

Error: Get "/api/folders/id/332": unsupported protocol scheme ""
```

## trying to apply the plan:
```
# module.grafana_org_prod.grafana_folder.this["folder_name"] will be created
  + resource "grafana_folder" "this" {
      + id    = (known after apply)
      + title = "folder_name"
      + uid   = (known after apply)
    }

Plan: 25 to add, 0 to change, 0 to destroy.
```

If I simply try to apply the plan I see the correct number of folders already present in the org, but I'm starting now to manage them with terraform and I have to import all of them

**Comment by nikosmeds** [comment]
@askthedust is this still an issue?

If so, please provide complete details on how to reproduce (e.g. examples of the variable and module being used).

I attempted to recreate this locally but everything is working correctly:

```
variable "folders" {
  type = list(string)
  default = [
    "Imported1",
    "Imported2",
  ]
}

resource "grafana_folder" "this" {
  for_each = toset(var.folders)
  title = each.key
}
```

I created a few folders on a local Grafana server and was able to successfully import them with the following:

```
$ terraform import 'grafana_folder.this["Imported1"]' 5
$ terraform import 'grafana_folder.this["Imported2"]' 4
```

**Comment by julienduchesne** [comment]
The issue was a missing validation on the Grafana URL: https://github.com/grafana/terraform-provider-grafana/pull/395
