### ISSUE TITLE
[Bug]: 401 unauthorized when using cloud_access_policy_token

### ISSUE THREAD

**Issue by v4de** [grafana/terraform-provider-grafana#1573]
### Terraform Version

1.8.2-1

### Terraform Grafana Provider Version

2.19.0

### Grafana Version

Grafana Cloud

### Affected Resource(s)

* grafana_cloud_stack

### Terraform Configuration Files

```hcl
provider "grafana" {
  alias                     = "cloud"
  cloud_access_policy_token = data.azurerm_key_vault_secret.cloud_sa_token.value
}

data "grafana_cloud_stack" "target" {
  provider = grafana.cloud

  slug     = var.stack_slug
}

provider "grafana" {
  alias = "stack"
  url   = data.grafana_cloud_stack.target.url
  auth  = data.azurerm_key_vault_secret.cloud_sa_token.value
}

resource "grafana_team" "team" {
  provider = grafana.stack

  name     = var.team.name
  email    = var.team.email
  members  = var.team.members
}
```

### Expected Behavior

Expected to retrieve stack datasource object.

### Actual Behavior

I get a 401 Unauthorized error when trying to get a grafana_cloud_stack datasource (Stack ID omitted):

> │ Error: error reading stack with ID`*****`: 401 Unauthorized
> │ 
> │   with data.grafana_cloud_stack.target,
> │   on main.tf line 57, in data "grafana_cloud_stack" "target":
> │   57: data "grafana_cloud_stack" "target" {

### Steps to Reproduce

terraform plan

### Important Factoids

the cloud_access_policy_token I am using has the following permissions and all Realms:
```
Scopes:
accesspolicies:read
accesspolicies:write
accesspolicies:delete
alerts:read
alerts:write
rules:read
rules:write
profiles:read
profiles:write
stack-service-accounts:write
stack-users:read
stacks:read
stacks:write
stacks:delete
```

I am wondering if anyone can let me know what kind of permissions I would need to use this datasource? The docs just mention to create a key but not what the realm or scopes need to be. Please let me know if you need any more information from me.

**Comment by julienduchesne** [comment]
401 means an invalid token, not missing permissions. 

I see that you use the same token for the stack and Grafana Cloud. They are supposed to be different. 

You'd use an access policy token for Grafana Cloud and a cloud stack service account token to manage resources within a stack.
