### ISSUE TITLE
[Bug]: Error: [GET /folders/{folder_uid}][404] getFolderByUidNotFound {"message":"folder not found","status":"not-found"}

### ISSUE THREAD

**Issue by fabio-s-franco** [grafana/terraform-provider-grafana#1574]
### Terraform Version

1.8.3

### Terraform Grafana Provider Version

3.0.0

### Grafana Version

10.4.3

### Affected Resource(s)

grafana_folder
grafana_folder_permission

### Terraform Configuration Files

```hcl
resource "grafana_folder" "default" {
  depends_on = [ null_resource.wait, grafana_organization.myorg]
  
  title  = "Default Dashboards"
  org_id = grafana_organization.myorg.org_id
}

resource "grafana_folder_permission" "read_only" {
  folder_uid = grafana_folder.default.uid
  permissions {
    role       = "Editor"
    permission = "View"
  }
}

```

### Expected Behavior

Folder permissions are applied to the folder

### Actual Behavior

During apply, the provider attempts to find the folder before creating the folder permissions. It fails with the following error:

>  Error: [GET /folders/{folder_uid}][404] getFolderByUidNotFound {"message":"folder not found","status":"not-found"}
│ 
│   with ....grafana_folder_permission.read_only,
│   on folder.tf line 9, in resource "grafana_folder_permission" "read_only":
│    9: resource "grafana_folder_permission" "read_only" {
│ 

I noticed that this call does not have /api prepended to it. And indeed if I try:
`GET /folders/{folder_uid}`
A 404 is returned.
But if I try:
`GET /api/folders/{folder_uid}`
It correctly returns the folder.

So I believe this is just a matter of wrong URL used by the provider.

### Steps to Reproduce

I used this on Grafana OSS. Should work with any setup, all you need is plan and apply with the resources above.

**Comment by julienduchesne** [comment]
orgID needs to be set on every resource if not using the default org

**Comment by fabio-s-franco** [comment]
> orgID needs to be set on every resource if not using the default org

That fixes my issue, but I do believe there is still a bug there as the API reference always has a /api prefix.
There shouldn't be a call to just /folders as the this route will never exist.

According to the [docs](https://grafana.com/docs/grafana-cloud/developer-resources/api-reference/http-api/folder/#get-folder-by-uid), getting by uid should be `GET /api/folders/:uid`

The route used by the provider is still invalid and if the design of the provider is as such, then the validation should account for the scenario as the 404 is a bit misleading.

**Comment by julienduchesne** [comment]
The client has a base path of /api, so it does not log it. It's how the go-swagger lib generates it
