### ISSUE TITLE
[Feature request]: Have the Grafana grafana_dashboard resource return full dashboard URL.

### ISSUE THREAD

**Issue by iidrees** [grafana/terraform-provider-grafana#160]
Hello there,

While working on a recent project, I wanted to dynamically link up dashboards created with this provider using their full Dashboard URL, like this `https://grafana.mydomain.com/d/abcdef-gh/dashboard-slug` however, after the dashboard whose URL is needed is created, the current provider's `grafana_dashboard`  resource returns:
```
...
id: a-random-dashboard-name
slug: a-random-dashboard-name
...
```

Is it possible to add the full URL of the dashboard as part of the returned object?

Affected Resource(s)
grafana_dashboard

**Comment by julienduchesne** [comment]
This was added in [v1.21.0](https://github.com/grafana/terraform-provider-grafana/releases/tag/v1.21.0)

**Comment by iidrees** [comment]
Thanks a lot @julienduchesne
