### ISSUE TITLE
[Bug]: Error: id "<folder UID>;<alert name>" does not match expected format. Should be in the format: folderUID:title

### ISSUE THREAD

**Issue by NadhemHamila** [grafana/terraform-provider-grafana#1607]
### Terraform Version

v1.4.6

### Terraform Grafana Provider Version

1.28.2

### Grafana Version

AWS Managed Grafana

### Affected Resource(s)

grafana_rule_group

### Terraform Configuration Files

I have created a terraform module for alerting to create rule groups with a folder
resource "grafana_folder" "rule_folder" { title = var.grafana_rule_folder_title } 
and a rule group

```
resource "grafana_rule_group" "my_alert_rule" {
  name             = var.grafana_rule_group_name
  folder_uid       = grafana_folder.rule_folder.uid
...
```
This was working weeks ago and I was using Terraform Grafana Provider version = ">= 1.28.2", then I wanted to delete one rule from the rule group so I just omitted the rule from the code that's when I faced the error.

### Expected Behavior

Rerunning the pipeline should not throw an error at the plan level

### Actual Behavior

I wanted to delete one rule from the rule group so I just omitted the rule from the code that's when I faced this error:

`Error: id "xxxxx;rule_group_name" does not match expected format. Should be in the format: folderUID:title not sure why it is a ; instead of : in there (odam06 mentioned he had the same, also in my case I don't have nested folders)`

I also tried to go back to the old code when this worked for me (the exact same without changing anything) but still had the same issue. 

It seems creating new alerts from scratch works but rerunning a pipeline of existing alerts does not.

### Steps to Reproduce

Redo a terraform plan for an existing grafana alert

**Comment by julienduchesne** [comment]
You'll have to give me something more to work with. I have tried reproducing it here: https://github.com/grafana/terraform-provider-grafana/issues/1535#issuecomment-2125409469 and haven't managed to do it

Did you try updating your provider in that way?
