### ISSUE TITLE
[Bug]: "prevent_destroy_if_not_empty" ignores dashboards in child folder

### ISSUE THREAD

**Issue by Sakib37** [grafana/terraform-provider-grafana#1620]
### Terraform Version

Terraform v1.5.5

### Terraform Grafana Provider Version

3.1.0

### Grafana Version

11.1.0

### Affected Resource(s)

* grafana_folder

The [prevent_destroy_if_not_empty](https://registry.terraform.io/providers/grafana/grafana/latest/docs/resources/folder#prevent_destroy_if_not_empty) flag can only protect from unexpected deletion of a folder when there is dashboard inside the parent folder. 

However, with new sub-folder feature, we can create subfolder inside a parent folder. If we have dashboards inside a child folder, the `prevent_destroy_if_not_empty` does not prevent to destroy the parent folder. 

### Expected Behavior

For any folder, `prevent_destroy_if_not_empty` checks if there is any dashboard in the subfolders as well and prevent deletion of a folder in this kind of situation

### Actual Behavior

`prevent_destroy_if_not_empty` cannot detect if there is any dashboard inside a child folder. So folder deletion deletes the parent folder including all this child folders as well as the dashboards inside the child folder.

### Steps to Reproduce

-  Create a folder by terraform and also enable the `prevent_destroy_if_not_empty` parameter.
- Manually create few child folder inside the parent folder 
- Manually create some dashbaords inside the child folders 
- Now try to delete the parent folder via terraform.

**Comment by julienduchesne** [comment]
Fixed here: https://github.com/grafana/terraform-provider-grafana/pull/1635. Will be released by EOW
