### ISSUE TITLE
[Bug]: Error: [DELETE /v1/provisioning/contact-points/{UID}] DeleteContactpoints (status 500): {}

### ISSUE THREAD

**Issue by maximusapen** [grafana/terraform-provider-grafana#1633]
### Terraform Version

2.0.0

### Terraform Grafana Provider Version

3.1.0

### Grafana Version

10.4.3

### Affected Resource(s)

grafana_contact_point
grafana_notification_policies

### Terraform Configuration Files

```
provider "grafana" {
  alias = "asp_grafana"
  url   = local.pagerduty_enabled != null ? "https://${var.mcsp_grafana_hostname}" : " "
  auth  = local.pagerduty_enabled != null ? var.mcsp_grafana_token : " "
}

resource "grafana_contact_point" "asp_grafana_pagerduty" {
  provider = grafana.asp_grafana
  count    = local.pagerduty_enabled ? 1 : 0
  depends_on = [
    pagerduty_service_integration.integration
  ]
  name = var.env_name
  pagerduty {
    integration_key = pagerduty_service_integration.integration[0].integration_key
    component       = var.env_name
    group           = var.env_name
    disable_resolve_message = true
  }
}
```

### Expected Behavior

We're seeing a 500 error when we try to delete contact_points 

<img width="893" alt="Screenshot 2024-06-12 at 10 19 36" src="https://github.com/grafana/terraform-provider-grafana/assets/41734177/c3200d8c-1676-48b7-9dcb-ed9da8b8aa8d">

### References

https://github.com/grafana/terraform-provider-grafana/issues/1606

**Comment by julienduchesne** [comment]
Is this contact point being used in a notification policy? Just trying to pinpoint the issue, the error message is definitely bad

**Comment by maximusapen** [comment]
@julienduchesne  We've figured out why it's throwing that error, we've had to delete the contact_point manually after which Terraform could provision via the API. 
We're good now
