### ISSUE TITLE
[Bug]: SSO for AzureAD not working

### ISSUE THREAD

**Issue by kaiyuanlim-adh** [grafana/terraform-provider-grafana#1654]
### Terraform Version

1.5.7

### Terraform Grafana Provider Version

3.2.0

### Grafana Version

11

### Affected Resource(s)

* Azure AD SSO settings

### Terraform Configuration Files

resource "grafana_sso_settings" "azuread_sso_settings" {
  provider_name = "azuread"
  oauth2_settings {
    name                       = "Azure AD"
    auth_url                   = "https://login.microsoftonline.com/${local.grafana_azuread.TENANT_ID}/oauth2/v2.0/authorize"
    token_url                  = "https://login.microsoftonline.com/${local.grafana_azuread.TENANT_ID}/oauth2/v2.0/token"
    client_id                  = local.grafana_azuread.APPLICATION_ID
    client_secret              = local.grafana_azuread.CLIENT_SECRET
    allow_sign_up              = false
    auto_login                 = false
    scopes                     = "openid email profile"
    allowed_organizations      = local.grafana_azuread.TENANT_ID
    role_attribute_strict      = false
    allow_assign_grafana_admin = false
    skip_org_role_sync         = true
    use_refresh_token          = true
    use_pkce                   = true
  }
}

### Expected Behavior

AzureAD sso created

### Actual Behavior

╷
│ Error: failed to create the SSO settings for provider azuread: [PUT /v1/sso-settings/{key}] updateProviderSettings (status 404): {}
│ 
│   with grafana_sso_settings.azuread_sso_settings,
│   on azureAD.tf line 1, in resource "grafana_sso_settings" "azuread_sso_settings":
│    1: resource "grafana_sso_settings" "azuread_sso_settings" {
│ 
╵

### Steps to Reproduce

Terraform apply

**Comment by julienduchesne** [comment]
Hello, did you set the `ssoSettingsApi` feature toggle on your Grafana instance?

**Comment by kaiyuanlim** [comment]
Where is it in the ini file? https://github.com/grafana/grafana/blob/main/conf/defaults.ini or values.yaml?
https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml

**Comment by kaiyuanlim-adh** [comment]
> Hello, did you set the `ssoSettingsApi` feature toggle on your Grafana instance?

Where is it in the ini file? https://github.com/grafana/grafana/blob/main/conf/defaults.ini or values.yaml?
https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml

**Comment by julienduchesne** [comment]
Here's the docs for it: https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/feature-toggles/. It's in the ini file in the `[feature_toggles]` section: https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#feature_toggles

**Comment by kaiyuanlim-adh** [comment]
thank you, it works!
