### ISSUE TITLE
Which version of provider should I use in Amazon Managed Grafana?

### ISSUE THREAD

**Issue by LideDing** [grafana/terraform-provider-grafana#1655]
The Grafana I use is Amazon Managed Grafana with version v10.4.1, but I was failed to use HCL code that generated by Grafana. I think maybe it was due to provider version? 
So which version should I use? Thanks!

**Comment by julienduchesne** [comment]
I will need more information than that. The latest version (v3) of the provider works with Grafana 10.4. What's the error you're getting?

**Comment by LideDing** [comment]
> I will need more information than that. The latest version (v3) of the provider works with Grafana 10.4. What's the error you're getting?

Thanks for your reply, I tried to export the alert rules group, but the provider couldn't understand some fileds, I thought it might due to the wrong provider version.
![企业微信截图_a9a1e6fd-9579-498a-b4a8-fb199d18ffec](https://github.com/grafana/terraform-provider-grafana/assets/37145239/76372cca-1d88-4d71-a108-9a8adbe3490d)

![企业微信截图_3e8faf92-c66c-47b9-b465-8425202fbb50](https://github.com/grafana/terraform-provider-grafana/assets/37145239/3464ffbc-bfd2-4657-9f00-71aebdca47be)

And the Grafana I used is Amazon Managed Grafana
<img width="1496" alt="企业微信截图_69e15e17-ed83-4d6e-bbb2-26731399dd58" src="https://github.com/grafana/terraform-provider-grafana/assets/37145239/5b5d7596-9542-4e15-8070-e13865e8c9b5">

**Comment by julienduchesne** [comment]
I think that's a bug in the export tool in Grafana. You can replace that attribute with `mute_timings`. I will close this issue but I will look into it on the Grafana side

**Comment by LideDing** [comment]
Thanks, I'll try it
