### ISSUE TITLE
[Bug]: error creating team: [POST /teams] createTeam (status 404)

### ISSUE THREAD

**Issue by max1c** [grafana/terraform-provider-grafana#1658]
### Terraform Version

1.5.7

### Terraform Grafana Provider Version

2.19.2

### Grafana Version

10.2

### Affected Resource(s)

This is happening to all resources I have. Teams, serviceaccounts, datasources, etc. Getting the following 404 error on all of the resource creations:
│ Error: error creating team: [POST /teams] createTeam (status 404): {}
│ 
│   with grafana_team.teams["test"],
│   on teams.tf line 13, in resource "grafana_team" "teams":
│   13: resource "grafana_team" "teams" {

### Expected Behavior

Was working without issues until I upgraded to the 2.19.2. Upgraded because needed to use "grafana_role_assignment_item".

### Actual Behavior

│ Error: error creating team: [POST /teams] createTeam (status 404): {}
│ 
│   with grafana_team.teams["test"],
│   on teams.tf line 13, in resource "grafana_team" "teams":
│   13: resource "grafana_team" "teams" {

**Comment by julienduchesne** [comment]
What version were you on before?

**Comment by max1c** [comment]
> What version were you on before?

Version 1.40.1.

**Comment by julienduchesne** [comment]
How is your provider configured? (provider block). The client changed between these versions. Haven't seen any cases yet where the configuration isn't compatible but there's always edge cases

**Comment by max1c** [comment]
With basic auth:
```
provider "grafana" {
  alias                = "basic_auth"
  url                  = "https://my.grafana.it/"
  auth                 = "${data.vault_generic_secret.grafana_basic_auth.data["username"]}:${data.vault_generic_secret.grafana_basic_auth.data["password"]}"
  insecure_skip_verify = true
}
```
I also figured this was an authentication issues so I've been trying to set this up with the token too but it doesn't seem to be working.

**Comment by max1c** [comment]
Another thing that changed is we've added the enterprise license. And I am wondering if that somehow broke the permissions on the accounts and needs to be changed/updated?

**Comment by julienduchesne** [comment]
Enterprise should work. They're the same URLs. All of the OSS tests can also run on an enterprise instance without issues. 404 is weird 🤔. Is your `grafana_team` resource using the correct provider alias?

**Comment by max1c** [comment]
The code didn't change and was working until this. This isn't only happening with grafana_team, it's happening with everything. Data sources, accounts, folders, etc.

This is how it looks: 
```
data "grafana_users" "all_users" {
  provider = grafana.basic_auth
}
```
Is this incorrect?

**Comment by julienduchesne** [comment]
> Is this incorrect?

it is correct. I'm a bit stumped 🤔

**Comment by max1c** [comment]
Ok, after removing the TF state and explicitly specifying provider = grafana.basic_auth everywhere it started working.
