### ISSUE TITLE
[Bug]: Unable to delete contact points when changing disable_provenance setting

### ISSUE THREAD

**Issue by InGaardWeTrust** [grafana/terraform-provider-grafana#1664]
### Terraform Version

1.9.0

### Terraform Grafana Provider Version

3.2.0

### Affected Resource(s)

* grafana_contact_point
* grafana_rule_group
* grafana_notification_policy

### Terraform Configuration Files

resource "grafana_contact_point" "email" {
  for_each           = { for key, value in local.notifiers : key => value.email if contains(keys(value), "email") }
  name               = each.key
  disable_provenance = true

  email {
    addresses = [each.value.to]
    message   = "{{ template \"default.message\" . }}"
    subject   = "{{ template \"default.title\" . }}"
  }
}

resource "grafana_rule_group" "this" {
   
      ...

      dynamic "notification_settings" {
        for_each = [for cur in rule.value.notifiers : cur if length(rule.value.notifiers) == 1]

        content {
          contact_point = notification_settings.value.slug
          group_by      = try(rule.value.signal_grouping.label_names, [])
          mute_timings  = each.value.mute ? [each.value.groupname] : []
        }
      }

### Expected Behavior

We have provisioned a number of contact points for various platforms using the above format. They are associated with various alert rules directly and through notification policies.

When we switch the `disable_provenance` to `true` the resource wants to recreate the contact_point. We expect that either the `disable_provenance` setting does NOT recreate the resource **or** when the apply happens that the contact points will be removed from the alert rules and notification policies, deleted, recreated with new setting, and re-attached to the correct rule or policy.

### Actual Behavior

The plan completes normally but the actual apply returns a generic 500 error.

`Error: [DELETE /v1/provisioning/contact-points/{UID}] DeleteContactpoints (status 500): {}`

No contact points can be deleted. Contact points that are directly tied to an alert can not be deleted and neither can contact points attached to a notification policy. Kind of makes the setting impossible to use if the contact point is in use. 

### Important Factoids

We have provisioned a number of contact points for various platforms using the above format. We originally created these separately from the alert groups, and disabled UI editing for all of the contact points. Later we decided to attach contact points directly to some alert rules if the alert rule only wanted to notify one contact point. This worked fine for us.

Now we want to enable provenance again, so we update the `disable_provenance` variable to `true`. [This comment ](https://github.com/grafana/grafana/issues/65072#issuecomment-1625678587) suggests that not being able to delete a contact policy that is in "use" is expected behavior.  Though it seems to imply that only a name change should recreate the contact point.

**Comment by julienduchesne** [comment]
Related issue: https://github.com/grafana/terraform-provider-grafana/issues/769

**Comment by julienduchesne** [comment]
I'll actually close it as a duplicate because it's the exact same issue as #769. The fact that it's a "replacement" does not make it easier because that is an information that is exposed in the Terraform functions. Terraform sees it as a standard deletion so we have to find a way to handle this globally
