### ISSUE TITLE
[Bug]: ID and UID are not being saved correctly in Terraform state for MSSQL data source

### ISSUE THREAD

**Issue by ferraroluc** [grafana/terraform-provider-grafana#1679]
### Terraform Version

1.9.1

### Terraform Grafana Provider Version

3.3.0

### Grafana Version

7.2.0

### Affected Resource(s)

grafana_data_source

### Terraform Configuration Files

```hcl
resource "grafana_data_source" "mssql" {
  type          = "mssql"
  name          = "DATABASE1"
  url           = "XXXXXX"
  database_name = "XXXXXX"
  username      = "XXXXXX"
  org_id        = grafana_organization.org.org_id

  json_data_encoded = jsonencode({
    maxOpenConns      = 100
    maxIdleConns      = 100
    maxIdleConnsAuto  = true
    connMaxLifetime   = 14400
    connectionTimeout = 0
    encrypt           = false
  })

  secure_json_data_encoded = jsonencode({
    password = "XXXXXX"
  })
}
```

### Expected Behavior

Create a Microsoft SQL Server data source and manage it through Terraform

### Actual Behavior

The resource is created but cannot be modified or destroyed.

### Steps to Reproduce

- Define a Grafana Provider and add credentials
- Create a Terraform resource for Microsoft SQL Server as data source
- Plan and Apply the changes
- Try to modify or delete the resource

### Important Factoids

It looks like ID and UID are not being saved correctly.

**Error when destroying**
`Error: error reading datasource with ID '8:' : [DELETE /datasources/uid/{uid}] deleteDataSourceByUID (status 400): {}`

**Terraform state**
```json
{
  "mode": "managed",
  "type": "grafana_data_source",
  "name": "mssql",
  "provider": "provider[\"registry.terraform.io/grafana/grafana\"]",
  "instances": [
    {
      "schema_version": 1,
      "attributes": {
        "access_mode": "proxy",
        "basic_auth_enabled": false,
        "basic_auth_username": "",
        "database_name": "XXXXXX",
        "http_headers": null,
        "id": "8:",
        "is_default": false,
        "json_data_encoded": "{\"connMaxLifetime\":14400,\"connectionTimeout\":0,\"encrypt\":false,\"maxIdleConns\":100,\"maxIdleConnsAuto\":true,\"maxOpenConns\":100}",
        "name": "DATABASE1",
        "org_id": "8",
        "secure_json_data_encoded": "{\"password\":\"XXXXXX\"}",
        "type": "mssql",
        "uid": "",
        "url": "XXXXXX",
        "username": "XXXXXX"
      }
    }
  ]
}
```

**Comment by julienduchesne** [comment]
Grafana 7.2 is not supported by that provider version. UIDs did not exist in Grafana 7.2 and they are now the only way to identify datasources (numerical IDs are deprecated)

Grafana 7 is pretty old but the latest v1 provider version should work: https://registry.terraform.io/providers/grafana/grafana/1.43.0/docs/resources/data_source
