### ISSUE TITLE
[Bug]: Unable to change provisioned data source which was imported

### ISSUE THREAD

**Issue by oliviermichaelis** [grafana/terraform-provider-grafana#1682]
### Terraform Version

OpenTofu 1.7.0

### Terraform Grafana Provider Version

3.4.0

### Grafana Version

v11.0.0

### Affected Resource(s)

* `grafana_data_source`

### Terraform Configuration Files

This Prometheus data source was initially provisioned by another data source. I then imported it into another state with the following config:
```hcl
resource "grafana_data_source" "prometheus" {
  name        = "Prometheus"
  type        = "prometheus"
  url         = "http://kube-prometheus-stack-prometheus.kube-prometheus-stack.svc.cluster.local:9090"
  access_mode = "proxy"
}
```

### Expected Behavior

After importing it, I expect to be able to update the data source.

### Actual Behavior

When changing the `grafana_data_source`, for example by changing the `is_default` argument:
```hcl
resource "grafana_data_source" "prometheus" {
  name        = "Prometheus"
  type        = "prometheus"
  url         = "http://kube-prometheus-stack-prometheus.kube-prometheus-stack.svc.cluster.local:9090"
  access_mode = "proxy"
  is_default = true
}
```
and run `tofu apply` I get
```log
grafana_data_source.prometheus: Modifying... [id=1:ABC123]
╷
│ Error: [PUT /datasources/uid/{uid}][403] updateDataSourceByUidForbidden {"message":"Cannot update read-only data source"}
│
│   with grafana_data_source.prometheus,
│   on datasources.tf line 1, in resource "grafana_data_source" "prometheus":
│    1: resource "grafana_data_source" "prometheus" {
│
╵
```

**Comment by oliviermichaelis** [comment]
changed the `read_only` field in the database from `1` to `0` with:
```
UPDATE data_source SET read_only = 0 WHERE uid = ABC123;
```

I would propose that the provider warns or prevents importing a data source that is set to read_only :)

**Comment by julienduchesne** [comment]
Yeah, that's a good idea. In that case, a user should use the datasource (`data.grafana_data_source`) 👍.
