### ISSUE TITLE
[Feature Request]: Add a "Grafana-Terraform-Provider-Version" header to requests

### ISSUE THREAD

**Issue by joeblubaugh** [grafana/terraform-provider-grafana#1694]
### Feature Request

The provider sets a header "Grafana-Terraform-Provider" to "true", similar to using a user agent, so that endpoints it calls can provide special treatment if necessary. It would be nice to know the version of the provider so backends can provide specific messaging based on version, including things like:
* "version is not supported. upgrade to XYZ"
* including or hiding fields or data that cause known breakages in the provider
* structure translation in the API after a migration in the backend that changes structure.

I would suggest one of two approaches:
* Add a new header that includes the version
* Change the value set for "Grafana-Terraform-Provider" to the version of the provider.

Working with a blank slate, I would go for the second approach because it reduces the total number of headers, but if we stop using "true" it's possible that some backends depend on that exact value and would break. So I'd lean towards adding an additional header if this feature request is accepted.

**Comment by julienduchesne** [comment]
Can't hurt to have this information: https://github.com/grafana/terraform-provider-grafana/pull/1700
