### ISSUE TITLE
[Bug]: Error 401: Invalid API key

### ISSUE THREAD

**Issue by alexfedeez** [grafana/terraform-provider-grafana#1696]
### Terraform Version

1.3.7

### Terraform Grafana Provider Version

3.4.0

### Grafana Version

9.5.19

### Affected Resource(s)

* grafana_data_source 
* grafana_folder
* grafana_dashboard

### Terraform Configuration Files

provider "grafana" {
  url  = local.provider_grafana_endpoint
  auth = local.grafana_sa_token
}

resource "grafana_folder" "main" {
  title = var.managed_grafana_folder
}

resource "grafana_data_source" "dataexplorer" {
  type               = "grafana-azure-data-explorer-datasource"
  name               = "ADX Datasource"
  url                = ""
  basic_auth_enabled = false

  json_data_encoded = jsonencode({
    "azureCredentials" : {
      "authType" : "clientsecret",
      "azureCloud" : "AzureCloud",
      "clientId" : "${var.adx_connector_clientid}",
      "tenantId" : "${var.adx_connector_tenantid}",
      "clientSecret" : "${var.adx_connector_clientsecret}"
    },
    "clusterUrl" : "${var.azurerm_kusto_cluster_uri}"
    "dataConsistency" : "strongconsistency",
    "defaultDatabase" : "compliance_db",
    "defaultEditorMode" : "visual"
  })
}

resource "grafana_dashboard" "main" {
  for_each    = fileset("${path.module}/dashboards/main", "*.json")
  config_json = file("${path.module}/dashboards/main/${each.key}")
  folder      = grafana_folder.main.id
  depends_on  = [grafana_data_source.dataexplorer]
}

### Expected Behavior

Back then I used to be able to deploy the workspace for Grafana and after that create the data sources, folders and deploy dashboards. 

### Actual Behavior

This was working in the past, now getting this one for all Grafana-related resources: failed to create folder: [POST /folders][401] createFolderUnauthorized {"message":"invalid API key"}

**Comment by julienduchesne** [comment]
Your `local.grafana_sa_token` must be empty or set to an invalid value. How is it being set?
