### ISSUE TITLE
[Feature]: Tokens data source block for use with Secrets

### ISSUE THREAD

**Issue by jark-AB** [grafana/terraform-provider-grafana#1699]
### Feature Request

Currently there is a [resource](https://registry.terraform.io/providers/grafana/grafana/latest/docs/resources/cloud_stack_service_account_token) block that allows you to manage/bootstrap service account tokens. I'd like to provision a service account token for an access policy, reference the token in a data resource block and write that to AWS SecretManager.

**Comment by julienduchesne** [comment]
It's not possible to get a token without creating it in Terraform. The API doesn't return API tokens except during the initial POST event that actually creates the resource

**Comment by jark-AB** [comment]
> It's not possible to get a token without creating it in Terraform. The API doesn't return API tokens except during the initial POST event that actually creates the resource

@julienduchesne Thanks for the quick response! Yeah that's what I'm also noticing the HTTP API docs, the key is only returned during the initial POST call. So how are customers managing secret tokens that are to be used for Alloy, Tempo, Prom etc.? In the helm [chart](https://github.com/grafana/k8s-monitoring-helm/blob/0f7a57cf90105f6ffc1ecf92bf6c9b6b9acf93d9/charts/k8s-monitoring/values.yaml#L66-L78), you can define the username/password(token) required.

Are customers just creating many tokens for their access policy and manually inputting them into an external secret for use with K8s? (AWS secretManager, external secrets etc.). That seems a bit cumbersome when you start to have many tokens

**Comment by julienduchesne** [comment]
What we do at Grafana Labs is that we use Crossplane. If we provision a token, it is written into a Kubernetes secret which everything (that helm chart included) can consume.

Other users probably use it this way: you can create the token as a Terraform resource and write the output into whatever secretmanager you want

```terraform
resource "grafana_service_account" "test" {
  name = "test-service-account"
  role = "Viewer"
}

resource "grafana_service_account_token" "foo" {
  name               = "key_foo"
  service_account_id = grafana_service_account.test.id
}

resource "my_secret_manager" "foo" {
  name = "key_foo"
  value = grafana_service_account_token.foo.key
}
```
