### ISSUE TITLE
[Bug]: cloudwatch data source unable to connect with cloudwatch

### ISSUE THREAD

**Issue by YuanH** [grafana/terraform-provider-grafana#1701]
### Terraform Version

1.9.2

### Terraform Grafana Provider Version

3.4.0

### Grafana Version

grafana cloud

### Affected Resource(s)

grafana_data_source

### Terraform Configuration Files

I just upgraded our grafana provider version from 1.2.1 to 3.4.0:

Grafana provider 3.4.0:
```
resource "grafana_data_source" "cloudwatch" {

  type = "cloudwatch"
  name = var.account_name

  json_data_encoded = jsonencode({
  default_region            = var.region
  auth_type                 = "keys"
  assume_role_arn           = "arn:aws:iam::${var.CLOUD_ID_TF}:role/grafana-metrics-role"
  custom_metrics_namespaces = try(var.custom_metric_namespace, "")
  })

  secure_json_data_encoded = jsonencode({
    access_key = var.cloudwatch_access_key
    secret_key = var.cloudwatch_secret_key
  })
  }

}
```
The terraform apply was successful, but when I go into the UI and look at the data source settings, I saw none of the credentials were populated:
![image](https://github.com/user-attachments/assets/c7e4eee7-704c-48bb-b79f-e455ee5385b8)

I then reverted the code to grafana provider 1.2.1

```
resource "grafana_data_source" "cloudwatch" {

  type = "cloudwatch"
  name = var.account_name



  json_data {
    default_region            = var.region
    auth_type                 = "keys"
    assume_role_arn           = "arn:aws:iam::${var.CLOUD_ID_TF}:role/grafana-metrics-role"
    custom_metrics_namespaces = try(var.custom_metric_namespace, "")
  }


  secure_json_data {
    access_key = var.cloudwatch_access_key
    secret_key = var.cloudwatch_secret_key
  }

}
```
I now see authentication setting populated and connection details applied:
![image](https://github.com/user-attachments/assets/5a20b25d-c112-41fa-9d4f-c19be776ff9c)

Right now we are reverting back to grafana provider version 1.2.1

### Expected Behavior

![image](https://github.com/user-attachments/assets/5a20b25d-c112-41fa-9d4f-c19be776ff9c)

![image](https://github.com/user-attachments/assets/85299dab-7d10-44e5-8838-d051d86b0044)

### Actual Behavior

The terraform apply was successful, but when I go into the UI and look at the data source settings, I saw none of the credentials were populated:
![image](https://github.com/user-attachments/assets/c7e4eee7-704c-48bb-b79f-e455ee5385b8)

![image](https://github.com/user-attachments/assets/b7b7720f-e2a1-41f6-bb4d-525e053fd29f)

### Steps to Reproduce

1. Using the latest grafana provider version 3.4.0 in the terraform configuration files above
2. here's my provider config: 
```terraform {
  required_providers {
    grafana = {
      source = "grafana/grafana"
      version = ">=3.0.0"
      }
  }
}

provider "grafana" {
  url  = "https://<grafanadomain>.grafana.net/"
  auth = var.grafana_api_key
}
```
3. `terraform apply`
4. the data source is created but could not connect to cloudwatch

### Important Factoids

we are on grafana cloud

**Comment by julienduchesne** [comment]
As documented here: https://registry.terraform.io/providers/grafana/grafana/latest/docs/resources/data_source#json_data_encoded, the keys are the payload that the API expects directly. There is no translation from `snake_case` to `camelCase` because this data is arbitrary

There is an example in the docs page for cloudwatch as well:
```
resource "grafana_data_source" "cloudwatch" {
  type = "cloudwatch"
  name = "cw-example"

  json_data_encoded = jsonencode({
    defaultRegion = "us-east-1"
    authType      = "keys"
  })

  secure_json_data_encoded = jsonencode({
    accessKey = "123"
    secretKey = "456"
  })
}
```
