### ISSUE TITLE
[Feature Request]: Wake-up Grafana instance

### ISSUE THREAD

**Issue by jkroepke** [grafana/terraform-provider-grafana#1725]
### Feature Request

Sometimes, our grafana instance is going to sleep which results into the following error:

> │ Error: error waiting for stack (URL: https://<instance>.grafana.net/api/health) to be ready: stack was not ready in 5m0s. Status code: 404, Body: {"code":"NotFound","message":"We do not recognize the instance URL you're trying to reach."}

Would it be possible, if the provider could wake up the instance? The current workaround is open `https://<instance>.grafana.net/` in a browser.

**Comment by julienduchesne** [comment]
Hmm, that error message is from the resource trying to wake up the instance. Qs:
- Does your error only happen with the `cloud_stack_service_account` and `cloud_stack_service_account_token` resources? 
- Is the URL really `URL: https://.grafana.net/api/health` in the error message, or did you redact the slug?

**Comment by jkroepke** [comment]
> * Does your error only happen with the cloud_stack_service_account and cloud_stack_service_account_token resources?

Yes

> * in the error message, or did you redact the slug?

Yep, markdown hide it. You can see the placeholder, if you click edit on my message: `https://<instance>.grafana.net/api/health`.

```
Acquiring state lock. This may take a few moments...
grafana_cloud_stack.opsstack: Refreshing state... [id=649973]
grafana_cloud_stack_service_account.terraform: Refreshing state... [id=opsstack:85]
grafana_cloud_access_policy.opsstack: Refreshing state... [id=prod-eu-west-3:8deeda39-21da-4b59-b6fc-a9c5d80d5cb1]
grafana_cloud_access_policy_token.opsstack: Refreshing state... [id=prod-eu-west-3:7cc27a17-99eb-405d-85f1-efc2026672e9]

Planning failed. OpenTofu encountered an error while generating this plan.

╷
│ Error: error waiting for stack (URL: https://<instance>.grafana.net/api/health) to be ready: stack was not ready in 5m0s. Status code: 404, Body: {"code":"NotFound","message":"We do not recognize the instance URL you're trying to reach."}
│ 
│ 
│   with grafana_cloud_stack_service_account.terraform,
│   on main.tf line 10, in resource "grafana_cloud_stack_service_account" "terraform":
│   10: resource "grafana_cloud_stack_service_account" "terraform" {
│ 
╵
Releasing state lock. This may take a few moments...
Error: Process completed with exit code 1.
```

If I go to the instance via browser, I could the see the wake up screen. After that, terraform plan just works fine.

We never had to wait 5m until the instance come up.

**Comment by julienduchesne** [comment]
Interesting. It does seem like the `/api/health` endpoint does not trigger the wake-up. We have had another case like this and this explains things. I will fix this ASAP!
