### ISSUE TITLE
[Bug]: Resource ID parser breaking change

### ISSUE THREAD

**Issue by pzmi** [grafana/terraform-provider-grafana#1730]
### Terraform Version

v1.7.4

### Terraform Grafana Provider Version

v2.13.0

### Grafana Version

v11.2.0

### Affected Resource(s)

grafana_cloud_api_key, potentially more resources that use user provided data in resource ids

### Terraform Configuration Files

resource "grafana_cloud_api_key" "test" {
  cloud_org_slug = "myorg"
  name           = "service-a-production-admin"
  role           = "Admin"
}

### Expected Behavior

Plan refreshed without errors.

### Actual Behavior

Refresh plan errored out with the following error: `Error: id "myorg-service-a-production-admin-production" does not match expected format. Should be in the format: orgSlug:apiKeyName`.

### Steps to Reproduce

1. Set grafana provider version to v1.43.0
2. terraform init
3. terraform plan
4. terraform apply
5. Set grafana provider version to v2.13.0

### Important Factoids

Version v2.13.0 introduced the bug through this change: https://github.com/grafana/terraform-provider-grafana/commit/d6e8d1744

The "legacy" id parser introduced in this change is supposed to provide backward compatibility with resource ids created prior to introduction of standardised resource id format. However, the parser splits the id on every occurrence of "-" rather than on the first one, like previous versions did. This result in an id parsing error, number of parts is greater than expected, it should be 2 but in the example `myorg-service-a-production-admin` we get 5. 
This results in a confusing error message, `Error: id "myorg-service-a-production-admin-production" does not match expected format. Should be in the format: orgSlug:apiKeyName`, that related to the standardised id format and does not mention the old one.

**Comment by julienduchesne** [comment]
Have you tried with v2.19.2? All of the known ID issues have been fixed

**Comment by pzmi** [comment]
Hi. I did try v2.19.2, the same result as one described, i.e. `Error: id "myorg-service-a-production-admin-production" does not match expected format. Should be in the format: orgSlug:apiKeyName`

**Comment by julienduchesne** [comment]
👍. I can issue a fix for this in v2. Might have missed this one since it's deprecated (and removed in v3)

**Comment by julienduchesne** [comment]
Can you try 2.19.4 and let me know if it's fixed? https://github.com/grafana/terraform-provider-grafana/releases/tag/v2.19.4

**Comment by pzmi-f3** [comment]
Hi. I confirm that v2.19.4 addressed the issue. Thanks for the quick fix 🙏

**Comment by pzmi** [comment]
Hi! I confirm that 2.19.4 fixed the issue. Thanks for the quick fix 🙏🏻
