### ISSUE TITLE
[Bug]: Not able to create the Grafana dashboard inside a specific Grafana folder

### ISSUE THREAD

**Issue by hkarira1** [grafana/terraform-provider-grafana#1732]
### Terraform Version

Terraform v1.4.5

### Terraform Grafana Provider Version

Grafana Provider Version 3.6.0

### Grafana Version

7.0.0

### Affected Resource(s)

Grafana Dashboard
Grafana Folder

### Terraform Configuration Files

```
resource "grafana_folder" "my_folder" {
  org_id = "1"
  title  = "App-Infra-new"
  uid    = "uid-App-Infra-new"
}

output "grafana_folder_id" {
  value       = grafana_folder.my_folder.id
  description = "The folder id"
}

#Add a new data source
#Add a provision to create dashboard

resource "grafana_data_source" "influxdb" {
  type                = "influxdb"
  name                = "test infra influx"
  url                 = "http://10.2.7.64:8086/"
  basic_auth_enabled  = false
  basic_auth_username = "admin"
  database_name       = "telegraf" // Example: influxdb_database.metrics.name
  json_data_encoded = jsonencode({
    authType          = "default"
    basicAuthPassword = "admin"
  })
}

resource "grafana_dashboard" "test" {
  folder = grafana_folder.my_folder.id
  config_json = file("/Users/harshitkarira/grafana-dac/dashboards/app-infra-dashboard.json")
}
```

### Expected Behavior

The dashboard should be able to create inside the specific folder mentioned (with the help of UID).

### Actual Behavior

I tried creating the grafana dashboard `test` in the grafana folder `my_folder` created above. The dashboard gets created but it does not get pointed/mapped to the folder mentioned. The dashboard gets created in the folder named `General`. This happens when i use the grafana version 7.0.0. However, I am not able to reproduce this issue with Grafana version v11.1.

Please do let me know if this is a grafana version issue. Also, we are running Grafana version 7.0.0 for monitoring our production workloads and want to automate dashboard creation via terraform. I tried searching for the compatibility matrix to see which terraform-grafana-provider is compatible with Grafana 7.0.0 but couldn't find anything. Can you please let me know what would be the stable terraform-grafana-provider version to use along with Grafana 7.0.0 ? 

Is there a workaround for this ? We would not want to upgrade the Grafana version atm.

### Steps to Reproduce

1. terraform init
2. terraform plan
3. terraform apply

### Important Factoids

NA

### References

NA

**Comment by julienduchesne** [comment]
This happens because the latest provider version uses folder UIDs (numerical IDs are deprecated in Grafana 11). Grafana 7 didn't even have UIDs. If you use the latest v1 version of provider, it should work
