### ISSUE TITLE
Strange behaviour with Grafana using Postgres as backend (grafana_organization)

### ISSUE THREAD

**Issue by ytsuhar** [grafana/terraform-provider-grafana#174]
Hi,
- terraform                               - v0.14.7
- grafana                                  - v.7.4.3 (010f20c1c8) grafana/grafana:7.4.3
- terraform-provider-grafana - v1.8.1

simple terraform plan
```
terraform {
  required_providers {
    grafana = {
      source  = "grafana/grafana"
      version = "1.8.1"
    }
  }
}

provider "grafana" {
  url    = "http://localhost:3000/"
  auth   = "emAdmin:emAdmin"
  org_id = 1
}

resource "grafana_organization" "test-org" {
  name         = "Test Organization"
  admin_user   = "emAdmin"
  create_users = true
  editors = [
    "editor-01@example.com",
    "editor-02@example.com"
  ]
  viewers = [
    "viewer-01@example.com",
    "viewer-02@example.com"
  ]
}

```
Result is the next
<img width="966" alt="image" src="https://user-images.githubusercontent.com/79971665/109787005-7476ce80-7c16-11eb-8d36-1b8168d0ccab.png">

Using Grafana with default backend (sqlite) the result as expected
<img width="972" alt="image" src="https://user-images.githubusercontent.com/79971665/109788057-8c028700-7c17-11eb-8040-3f747a34ca89.png">

Debugs are attached
[tf_debug_grafana_postgres.log](https://github.com/grafana/terraform-provider-grafana/files/6075109/tf_debug_grafana_postgres.log)
[tf_debug_grafana_sqlite.log](https://github.com/grafana/terraform-provider-grafana/files/6075110/tf_debug_grafana_sqlite.log)

**Comment by ytsuhar** [comment]
can be closed, behaviour was caused by grafana settings - auto_assign_org = false.

**Comment by nikosmeds** [comment]
> can be closed, behaviour was caused by grafana settings - auto_assign_org = false.

Okay, thanks @ytsuhar. Please re-open if necessary.
