### ISSUE TITLE
[Feature Request]: inside grafana_folder , if you provide nested_folder creation with parameter ignore_folder_exist bool feature

### ISSUE THREAD

**Issue by ponmuthumuniyasamy** [grafana/terraform-provider-grafana#1772]
### Feature Request

Hi Team,

I want to create nested folder structure.
i am using grafana/grafana v3.6.0

below is my sample code 

```
data "grafana_folder" "folder_exist" {
  count = local.folder_name != null ? 1 : 0
  title = local.folder_name
  uid = local.folder_name
}

resource "grafana_folder" "folder" {
  count = can(data.grafana_folder.folder_exist) ? 0 : 1
  title = local.folder_name
  uid = local.folder_name
  org_id = var.organization_id
}
```

in above code when i do plan, 

if folder not exist case data block will throw error 

If i want to explain my problem in one liner. 
mkdir -p "folder1/folder2/folder3" here -p doest exists check , same way.

**Comment by Duologic** [comment]
Can you use this data source? https://registry.terraform.io/providers/grafana/grafana/latest/docs/data-sources/folders 

It lists a set of folders that you can use conditionals on.

**Comment by Duologic** [comment]
I hope above answer resolves this question, closing for now.
