### ISSUE TITLE
darwin/arm64 support

### ISSUE THREAD

**Issue by loafoe** [grafana/terraform-provider-grafana#179]
### Terraform Version
`v0.14.8`

### Affected Resource(s)
N/A

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
N/A

### Debug Output
```shell
Error: Incompatible provider version

Provider registry.terraform.io/grafana/grafana v1.9.0 does not have a package
available for your current platform, darwin_arm64.
```
### Expected Behavior
A `binary for `darwin_arm64` is available from Terraform registry
### Actual Behavior
Terraform fails with above mentioned error

### Steps to Reproduce
On a Macbook Pro M1 with a plan requiring the grafana provider:
1. `terraform apply`

**Comment by loafoe** [comment]
A new build should solve the issue since `goreleaser` supports this out-of-the-box now

**Comment by darrinholst** [comment]
Was able to work around by following these instructions - https://github.com/hashicorp/terraform/issues/27257#issuecomment-825102330

    git clone https://github.com/grafana/terraform-provider-grafana.git
    cd terraform-provider-grafana
    mkdir -p ~/.terraform.d/plugins/registry.terraform.io/grafana/grafana/1.9.0/darwin_arm64
    mv terraform-provider-grafana ~/.terraform.d/plugins/registry.terraform.io/grafana/grafana/1.9.0/darwin_arm64

Would be great if this could be rebuilt and published

**Comment by trotttrotttrott** [comment]
[v1.11.0](https://github.com/grafana/terraform-provider-grafana/releases/tag/v1.11.0) has a darwin_arm64 build.
