### ISSUE TITLE
Documentation doesn't mention resource grafana_alert_notification.uid

### ISSUE THREAD

**Issue by fdw** [grafana/terraform-provider-grafana#182]
The documentation doesn't mention that you can set and get `uid` from a `grafana_alert_notification`.

**Comment by nikosmeds** [comment]
This was resolved in https://github.com/grafana/terraform-provider-grafana/pull/187.

Confirmed `uid` is now included in [docs/resources/alert_notification.md](https://github.com/grafana/terraform-provider-grafana/blob/master/docs/resources/alert_notification.md) 👍
