### ISSUE TITLE
[Bug]: "Invalid probes used for check" when creating a scripted test with more than one probe

### ISSUE THREAD

**Issue by ipiqueras** [grafana/terraform-provider-grafana#1832]
### Terraform Version

1.9.2

### Terraform Grafana Provider Version

3.9.0

### Affected Resource(s)

* Synthetic monitoring Checks (scripted)

### Terraform Configuration Files

```hcl

terraform {
  required_providers {
    grafana = {
      source = "grafana/grafana"
    }
  }
  required_version = ">= 1.4.2"
}

provider "grafana" {
  sm_access_token = "<secret_token>"
  sm_url          = "https://synthetic-monitoring-api.grafana.net"
}

resource "grafana_synthetic_monitoring_check" "scripted" {
  job       = "test job"
  target    = "https://grafana.com/"
  enabled   = true
  probes    = [
    data.grafana_synthetic_monitoring_probes.locations.probes["Amsterdam"],
    data.grafana_synthetic_monitoring_probes.locations.probes["Atlanta"]
  ]
  frequency         = 300 * 1000
  timeout           = 30 * 1000
  alert_sensitivity = "medium"

  settings {
    # also see https://github.com/grafana/terraform-provider-grafana/
    scripted {
      script = file("test.js")
    }
  }
}
```

### Expected Behavior

I would expect the check created to use two probes.

I can create the check with just one probe. Trying to create it with more or adding any other probe with Terraform fails.

### Actual Behavior

`terraform apply` fails with this error:

module.test_1.grafana_synthetic_monitoring_check.scripted: Modifying... [id=1655562]
╷
│ Error: check update request: status="400 Bad Request", msg="Invalid probes used for check", err="bad request"

### Steps to Reproduce

1. `terraform apply`

**Comment by The-9880** [comment]
Hey @ipiqueras ,

Thanks for reporting this! I believe in this case, you may have assigned the scripted check to at least one probe which does not support scripted checks (neither Atlanta or Amsterdam do) - I've put up a change to surface the issue more precisely! 👍

**Comment by ipiqueras** [comment]
Thanks @The-9880 
It would be great if the Documentation includes which probes support scripted checks or to include a more descriptive error. message.
