### ISSUE TITLE
[Feature Request]: ability to trigger an early renew on the grafana_cloud_access_policy_tokens resource

### ISSUE THREAD

**Issue by jwhitcraft** [grafana/terraform-provider-grafana#1840]
### Feature Request

Hello,

Currently, i'm trying to create `grafana_cloud_access_policy_token` resources that expire in one year.  While this can be done like this:

```
resource "time_rotating" "example" {
  rotation_days = 320
}


resource "grafana_cloud_access_policy_token" "this" {
  region           = "us"
  access_policy_id = grafana_cloud_access_policy.this.policy_id
  name             = "${local.cluster_name}-policy-token-${time_rotating.example.year}-${time_rotating.example.day}-${time_rotating.example.month}"
  display_name     = "${local.cluster_name} Policy Token"
  expires_at       = timeadd(time_rotating.example.rotation_rfc3339, "1080h") # add 45 days to the rotation time

  lifecycle {
    create_before_destroy = true
  }
}
```

When the token actually gets rotated, it shows up in terraform as a disposed object, and terraform what to delete it.  I'd like to for it stick around even though it's going to expired on it's own.  

I brought this up to the [OpenTofu team](https://github.com/opentofu/opentofu/issues/1615#issuecomment-2408226644) and they had suggested something like this, which is simular to how the hashicorp/tls provider works

```
resource "grafana_cloud_access_policy_tokens" "this" {
  region           = "us"
  access_policy_id = grafana_cloud_access_policy.this.policy_id
  name_prefix      = "${local.cluster_name}-policy-token-"
  display_name     = "${local.cluster_name} Policy Token"

  # These are what I'm imagining to replace the "expires_at" in the
  # singular grafana_cloud_access_policy_token resource type.
  expires_after = "1080h"
  early_renew   = "120h"

  lifecycle {
    create_before_destroy = true
  }
}

# The hashicorp/tls provider also exports a boolean attribute to
# help with hooking this up to a check block, which isn't necessarily
# required here but is a nice bonus of designing it this way!
#
# You can then run tofu apply -refresh-only periodically to raise
# a warning for yourself once the object enters its early renewal
# period, so it's less likely to be forgotten.
check "token_expiration" {
  assert {
    condition     = !grafana_cloud_access_policy_tokens.this.ready_for_renewal
    error_message = "Grafana access policy token will expire soon."
  }
}
````

Thoughs?

**Comment by Duologic** [comment]
As a workaround I see a [`created_at` field](https://registry.terraform.io/providers/grafana/grafana/latest/docs/resources/cloud_access_policy_token#read-only) being returned, perhaps the boolean can be calculated based on that.

**Comment by jwhitcraft** [comment]
> As a workaround I see a [`created_at` field](https://registry.terraform.io/providers/grafana/grafana/latest/docs/resources/cloud_access_policy_token#read-only) being returned, perhaps the boolean can be calculated based on that.

Very possible, but ideally even if that it doesn't i belive that terraform would still try and remove the old key even before it's expired, thus not giving us enough time to roll out the new key to our infra.

**Comment by volcanonoodle** [comment]
Hi @jwhitcraft ! Sounds very good, thank you 😄  We have a related issue which covers also service account tokens: https://github.com/grafana/terraform-provider-grafana/issues/1705
We could close this issue and use https://github.com/grafana/terraform-provider-grafana/issues/1705 to track this work instead, even if it's just for `grafana_cloud_access_policy_tokens`

**Comment by jwhitcraft** [comment]
@volcanonoodle sounds find to merge.

**Comment by volcanonoodle** [comment]
Closing this one and moving any future talks to https://github.com/grafana/terraform-provider-grafana/issues/1705 :)
