### ISSUE TITLE
[Feature Request]: Allow datasources to be set as readOnly. Currently there is no option to set this

### ISSUE THREAD

**Issue by pauldevlin-smarsh** [grafana/terraform-provider-grafana#1853]
### Feature Request

I would like the ability to set grafana datasources to read only by a variable in the provider (**read_only = true**)
There is currently no ability to do this and setting it within the jsonData does not work:

```
    "isDefault": false,
    "jsonData": {
        "dbName": "default",
        "defaultBucket": "default",
        "httpMode": "POST",
        "organization": "influxdata",
        **"readOnly": true,**
        "timeout": 5,
        "tlsAuth": false,
        "tlsAuthWithCACert": false,
        "version": "Flux"
    },
    "secureJsonFields": {
        "token": true
    },
    "version": 1,
    "readOnly": false,
```

It would be good to have this as a variable.

**Comment by Duologic** [comment]
What are you trying to achieve? What is `readOnly` supposed to mean? Why is it in there twice?

**Comment by Duologic** [comment]
Closing this as the request is not clear. Please reopen with more information.
