### ISSUE TITLE
[Feature Request]: `Grafana Cloud` Add CloudWatch Metric Scraping Enablement

### ISSUE THREAD

**Issue by Benbentwo** [grafana/terraform-provider-grafana#1870]
### Feature Request

On Grafana Cloud it would be incredibly useful to remove the need for ClickOps based work (manual stuff). 

It would be incredibly useful to have a resource and datasource that can manage and read data about setting up the AWS Integration for CloudWatch Metrics. 

Currently we can create the role, but then still have to click through enablement and some additional choices. I'd like to be able to do this all through terraform.

![Image](https://github.com/user-attachments/assets/3a0013ac-f243-4b85-9016-3f8122826e38)

**Comment by Duologic** [comment]
It feels like this is being implemented in https://github.com/grafana/terraform-provider-grafana/pull/1862 @fridgepoet @matthewnolf Can you confirm?

**Comment by matthewnolf** [comment]
#1862 is for a different resource - Metrics Endpoint scrape jobs.
However CloudWatch Metric Scraping is also being worked on independently by @tristanburgess

**Comment by tristanburgess** [comment]
We don't have a PR out to merge our TF provider changes to main yet for CW scrape jobs, but it is actively being worked on. ETA is to have the PR out next week.

**Comment by tristanburgess** [comment]
Hey ya'll! @thepalbi FYI

This should be available now for use with any provider version over `3.13.0` 😃

Some doc links:
https://registry.terraform.io/providers/grafana/grafana/latest/docs#managing-cloud-provider

https://registry.terraform.io/providers/grafana/grafana/latest/docs/resources/cloud_provider_aws_account
https://registry.terraform.io/providers/grafana/grafana/latest/docs/resources/cloud_provider_aws_cloudwatch_scrape_job

There'll be a demo video published to https://grafana.com/docs/grafana-cloud/whats-new/ sometime soon as well. Please do open a new GitHub issue with `cloudprovider` in the title if you run into any issues. Thanks!
