### ISSUE TITLE
Grafana plan suddenly failing with 403 Unlicensed

### ISSUE THREAD

**Issue by NicholasFiorentini** [grafana/terraform-provider-grafana#1906]
### Terraform Version

1.8.3

### Terraform Grafana Provider Version

1.13.1

### Grafana Version

1.4.0-77868

### Affected Resource(s)

*  grafana_team

### Terraform Configuration Files

```hcl
resource "grafana_team" "readers" {
  name    = "Readers"
  members = [
    "user1@domain.com",
    "user2@domain.com",
  ]
  team_sync {
    groups = [ // okta groups
      "group one",
      "group two",
    ]
  }
}
```

### Expected Behavior

The plan should work as it was doing until this week.

### Actual Behavior

The plan fails with the error

```

Error: [GET /teams/{teamId}/groups][403] getTeamGroupsApiForbidden {"message":"Unlicensed"}
with grafana_team.readers
on teams.tf line 107, in resource "grafana_team" "readers":
```

**Comment by Duologic** [comment]
This reads like your enterprise license got expired. 

The docs about this feature say:

> [Team sync](https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-team-sync/) and [active sync](https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/enhanced-ldap/#active-ldap-synchronization) are only available in Grafana Enterprise.

Source: https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/

Are you running on Grafana Cloud or on premise?

**Comment by Duologic** [comment]
I also doubt that the versions you mention are correct. The TF provider is at 3.13.x, 1.x would be horribly out-of-date and be riddled with issuess using against newer Grafana versions. Grafana itself is at 11.3.0, the 1.x versions unlikely had support for Teams and Okta sync. 😇

**Comment by NicholasFiorentini** [comment]
> I also doubt that the versions you mention are correct. The TF provider is at 3.13.x, 1.x would be horribly out-of-date and be riddled with issuess using against newer Grafana versions. Grafana itself is at 11.3.0, the 1.x versions unlikely had support for Teams and Okta sync. 😇

Yeah, sorry a typo. I meant `3.13.1`.

**Comment by NicholasFiorentini** [comment]
> This reads like your enterprise license got expired.
> Are you running on Grafana Cloud or on premise?

Indeed, I'm on Grafana Cloud with a NON-expired Enterprise license. I already opened a ticket with them, and it is likely an issue on Grafana's side.

**Comment by Duologic** [comment]
I'll close this for now but feel free to open it up again if it turns out to be an issue with the TF provider.
