### ISSUE TITLE
sigV4Auth support for prometheus data source

### ISSUE THREAD

**Issue by bmcclory** [grafana/terraform-provider-grafana#193]
Would like to use this provider to provision Amazon Managed Prometheus data sources with sigV4 auth enabled:

https://grafana.com/docs/grafana/latest/datasources/prometheus/#amazon-managed-service-for-prometheus

**Comment by trotttrotttrott** [comment]
Addressed in https://github.com/grafana/terraform-provider-grafana/pull/247, will be released in 1.13.3.
