### ISSUE TITLE
JSON Datasource lack of flexibility

### ISSUE THREAD

**Issue by aymericDD** [grafana/terraform-provider-grafana#197]
Why **json_data** and **json_secure_data** attribute of **datasource** ressource is not managed like **config_json** attribute of **dashboard ressource** ?
When a data source comes from a plugin (like zabbix) we cannot managed it with Terraform and if a datasource has new attributes we have to create a PR to update its Terraform schema.

**Comment by julienduchesne** [comment]
[Grafana 8.4.0 has a full OpenAPI spec](https://grafana.com/docs/grafana/latest/release-notes/release-notes-8-4-0/). So it's very likely we'll switch over to a fully generated client 🔜 . At that point, the datasource will probably be refactored a bit and support arbitrary data

**Comment by FrancoCorleone** [comment]
any news on that? I just hit this limitation with timestream plugin for Managed Grafana Service

**Comment by inkel** [comment]
@FrancoCorleone hi! We still haven't planned the feature for supporting arbitrary data, sorry.

**Comment by FrancoCorleone** [comment]
@inkel any way I can work around this limitation?

**Comment by inkel** [comment]
Not that I know of at the moment, sorry.
