### ISSUE TITLE
Custom HTTP Headers

### ISSUE THREAD

**Issue by matthiasantierens** [grafana/terraform-provider-grafana#202]
Would it be possible to add Custom Http Headers to the grafana_data_source (Resource)?

This would fit perfectly in the json_data.

I am using the simpod-json-datasource. I need this to pass custom headers.

**Comment by matthiasantierens** [comment]
I thought I could add http_headers but that did not work.

**Comment by thorker** [comment]
Duplicate #191 ?

**Comment by matthiasantierens** [comment]
Yes indeed, Will close this issue and following the other one.
