### ISSUE TITLE
InfluxDB Flux support?

### ISSUE THREAD

**Issue by jychen7** [grafana/terraform-provider-grafana#203]
I can create Flux data source manually in Grafana UI.
However, when want to mange it via Terraform, it raises error.

I am following [InfluxDB 2.x for Flux example](https://grafana.com/docs/grafana/latest/datasources/influxdb/provision-influxdb/), trying to set
```
json_data {
  version = "Flux"
  organization = "any"
}

secure_json_data {
  token = "xxx"
}
```

**Expect**
data source is created successfully and have type InfluxDB using Flux language

**Actual**
An argument named "version" is not expected here
An argument named "organization" is not expected here
An argument named "token" is not expected here

**Comment by julienduchesne** [comment]
This is now supported in v1.20.0
