### ISSUE TITLE
New feature: datasource permissions

### ISSUE THREAD

**Issue by ekpdt** [grafana/terraform-provider-grafana#205]
Suggesting a new feature to support managing datasource permissions resources via Terraform.

The existing public API suffices: https://grafana.com/docs/grafana/latest/http_api/datasource_permissions/

Proposed example resource block:

```
resource "grafana_datasource_permission" "fooPermissions" {
  datasource_id = grafana_datasource.foo.id
  permissions {
    team_id    = grafana_team.team.id
    permission = "Query" (optional, default "Query", options: Query)
  }
  permissions {
    user_id    = grafana_user.user.id
  }
}
```

**Comment by ingluife** [comment]
It would be great having this feature.

**Comment by techgnosis** [comment]
I have at least one paying customer and one prospect who really want this feature. Contact me on Slack for details

**Comment by julienduchesne** [comment]
I've started implementing this here:
- https://github.com/grafana/grafana-api-golang-client/pull/37
- https://github.com/grafana/terraform-provider-grafana/pull/289

It is only a draft, I still have to test it more (and have the acceptance tests run in our CI)

**Comment by julienduchesne** [comment]
Implemented by https://github.com/grafana/terraform-provider-grafana/pull/289
