### ISSUE TITLE
CI Should Check if Documentation Has Been Generated

### ISSUE THREAD

**Issue by trotttrotttrott** [grafana/terraform-provider-grafana#229]
Documentation is generated with [terraform-plugin-docs](https://github.com/hashicorp/terraform-plugin-docs) by running `go generate`. This needs to be done every time we add a new resource, data source, change any existing schema descriptions, change a template, or change an example.

The expectation is that PR authors commit the generated files. It's easy to forget to do this so we should have CI check that it's been done.

**Comment by julienduchesne** [comment]
This is done. Didn't see the issue 😄
