### ISSUE TITLE
[Feature Request] Import existing dashboards into terraform

### ISSUE THREAD

**Issue by bljordan** [grafana/terraform-provider-grafana#24]
Hi there,

This is a request to add import functionality to the grafana provider, specifically for the grafana_dashboard resource.

### Terraform Version
Terraform v0.11.7
+ provider.grafana v1.0.2

### Affected Resource(s)
Please list the resources as a list, for example:
- grafana_dashboard

### Expected Behavior
Import existing dashboards into terraform state:
terraform import grafana_dashboard.my_dashboard <slug|id|?>

### Actual Behavior
grafana_dashboard.my_dashboard: Importing from ID "<dashboard_id>"...

Error: grafana_dashboard.my_dashboard (import id: <dashboard_id>): import grafana_dashboard.my_dashboard (id: <dashboard_id>): resource grafana_dashboard doesn't support import

### Steps to Reproduce
terraform import grafana_dashboard.my_dashboard <dashboard-id>

**Comment by AlKapkone** [comment]
any updates ?

**Comment by mlclmj** [comment]
This was added in #52
