### ISSUE TITLE
grafana-provider v1.13.0 + terraform 1.0.2 seems incompatible

### ISSUE THREAD

**Issue by brunodix** [grafana/terraform-provider-grafana#240]
### Terraform Version
* Terraform: 1.0.2 (same error for 1.0.1)
* Terraform Grafana Provider: 1.13.0
* Grafana: v7.0.0-beta3 (84acc77e01)

### Affected Resource(s)
Please list the resources as a list, for example:
* grafana_user
* grafana_alert_notification
* grafana_organization
Seems to affect all resources, tested on 0.15.2 failed only on grafana_alert_notification.

### Terraform Configuration Files
```hcl
terraform {
  required_providers {
    grafana = {
      source = "grafana/grafana"
      version = "1.13.0"
    }
  }
}

provider "grafana" {
  url  = "https://grafana.fluig.app/"
}

variable "google_chats_common_webhook" {
  default = "https://chat.googleapis.com/v1/spaces/bogus/messages"
}

variable "google_chats_thread_key" {
  default = "\u0026threadKey="
}

resource "grafana_user" "testuser" {
  email    = "test@system.com"
  login    = "test.user"
  password = "please-change"
  is_admin = false
}

resource "grafana_alert_notification" "chat-alert-geral-text" {
  name          = "chat-alerts-nocode"
  type          = "googlechat"
  is_default    = false
  send_reminder = true
  frequency     = "20m"
  disable_resolve_message = false

  settings = {
    uploadImage = "false"
    autoResolve = true,
    httpMethod = "POST",
    severity = "critical"
    url = join("", [ var.google_chats_common_webhook, var.google_chats_thread_key, "common-text"])
  }
}
```

### Debug Output
https://gist.github.com/brunodix/da9f6284dd8d8870eff624c95c0d4a82

### Panic Output
No crash.log

### Expected Behavior
Expected to create resources and updates state file.

### Actual Behavior
Resources are created/update but fails to update terraform.tfstate.

### Steps to Reproduce
1. Export auth variable
1. `terraform apply`

### Important Factoids
Problem happened in v0.15.1 but only affected  'grafana_alert_notification', and its worse on v.1.0.+

**Comment by inkel** [comment]
I've downloaded the mentioned Terraform and Grafana provider version:

```
$ ./terraform version
Terraform v1.0.2
on darwin_amd64
+ provider registry.terraform.io/grafana/grafana v1.13.0

Your version of Terraform is out of date! The latest version
is 1.1.2. You can update by downloading from https://www.terraform.io/downloads.html
```

I've been using the following test configuration:

```terraform
terraform {
  required_providers {
    grafana = {
      source  = "grafana/grafana"
      version = "1.13.0"
    }
  }
}

provider "grafana" {
  url = "http://localhost:3000"
}

resource "grafana_user" "testuser" {
  email    = "test@system.com"
  login    = "test.user"
  password = "please-change"
  is_admin = false
}
```

State seems to be properly updated on `terraform.tfstate` file. I've tried to apply several times in a row after the initial `terraform apply` and got the following result:

```
$ ./terraform apply -auto-approve
grafana_user.testuser: Refreshing state... [id=34]

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration and found no differences, so no changes are needed.

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```

Furthermore, dumping the state file shows the resource being there:

```
$ ./terraform show
# grafana_user.testuser:
resource "grafana_user" "testuser" {
    email    = "test@system.com"
    id       = "34"
    is_admin = false
    login    = "test.user"
    password = (sensitive value)
}
```

If the issue persist, please feel free to reopen the issue.
