### ISSUE TITLE
[Feature Request] Manage Grafana playlists through Terraform

### ISSUE THREAD

**Issue by bljordan** [grafana/terraform-provider-grafana#25]
Hi there,

This is a request to add Grafana playlist resource to the provider
http://docs.grafana.org/reference/playlist/

### Terraform Version
Terraform v0.11.7
+ provider.grafana v1.0.2

### Affected Resource(s)
Please list the resources as a list, for example:
- grafana_dashboard

### Expected Behavior
Terraform provider is playlist aware

### Actual Behavior
Terraform managed dashboards are often recreated with a new ID.  Playlists reference dashboards by ID and will lose previously managed dashboards.  If terraform was playlist-aware, the playlist resource could reference a list of dashboards.

A grafana "bug" that has been exposed with this - if a playlist ends up empty (no dashboards attached), it becomes broken/undeletable/uneditable.  To fix this, we've manually editable the database.

**Comment by tonglil** [comment]
The required API has been merged in the library if anyone wants to give this a shot.
