### ISSUE TITLE
Provider should retry on HTTP Error 503

### ISSUE THREAD

**Issue by flokli** [grafana/terraform-provider-grafana#250]
### Terraform Version
* Terraform: v0.12.31
* Terraform Grafana Provider: v1.13.2
* Grafana: N/A

### Affected Resource(s)
Please list the resources as a list, for example:
* grafana_*

We use [Grafana Cloud](https://grafana.com/products/cloud/). It seems they suspend Grafana Dashboards after they haven't been used for some time.

This breaks the provider pretty hard, which immediately fails in the planning phase:

```
Error: status: 503, body: <!doctype html>
<html lang="en-US">
<head>
  <title>Hosted Grafana - Loading</title>
  <meta charset="utf-8"/>
  <link rel="shortcut icon" href="https://grafana.com/img/favicon.ico"/>
  <meta name="viewport" content="width=device-width, initial-scale=1"/>
  
  <meta http-equiv="refresh" content="5"/>
  […]
</head>
<body>
  <div class="page-section">
    <div class="hg-fallback--container">
      […]
        <h2 class="hg-fallback--headline" id="headline">Grafana is loading...</h2>
        <p class="hg-fallback--copy" id="message">
          Your instance is loading, and will be ready shortly.
        </p>
        
        <p class="hg-fallback--copy">
          If you see this message for more than a few minutes, please email <a href="mailto:support@grafana.com">support@grafana.com</a>
        </p>
    </div>
  </div>
  <div class="page-footer">
    <p class="meta">Copyright 2021 &copy; Grafana Labs | contact us: <a href="mailto:hello@grafana.com">hello@grafana.com</a> | <a href="https://grafana.com/trademark-policy">Trademark Policy</a> | cluster: prod-us-central-0</p>
  </div>
</body>
</html>




Error: status: 503, body: <!doctype html>


Releasing state lock. This may take a few moments...
```

I guess the provider shouldn't give up that easily, but retry, using the `Retry-After` HTTP header (if it exists).

**Comment by flokli** [comment]
I opened a PR at https://github.com/grafana/grafana-api-golang-client/pull/32, that'd allow setting `NumRetries` when creating `gapi.Config`, which should fix this:

```
diff --git a/grafana/provider.go b/grafana/provider.go
index bd06baa..cc1ca69 100644
--- a/grafana/provider.go
+++ b/grafana/provider.go
@@ -171,8 +171,9 @@ func configure(version string, p *schema.Provider) func(context.Context, *schema
 
                cli.Transport = logging.NewTransport("Grafana", transport)
                cfg := gapi.Config{
-                       Client: cli,
-                       OrgID:  int64(d.Get("org_id").(int)),
+                       Client:     cli,
+                       NumRetries: 10,
+                       OrgID:      int64(d.Get("org_id").(int)),
                }
                if len(auth) == 2 {
                        cfg.BasicAuth = url.UserPassword(auth[0], auth[1])
```

**Comment by sambacha** [comment]
any status on this @trotttrotttrott ?

**Comment by flokli** [comment]
@rfratto is there a chance to get a review on https://github.com/grafana/grafana-api-golang-client/pull/32, so there's a chance to get this fixed?

**Comment by rfratto** [comment]
@flokli thanks for raising this, and I'm sorry that your PR has been sitting around for a month. I'm not a maintainer of that repo, but I've elevated this internally to find out who can take a look. I'll let you know when I hear something :) 

edit: I've let @trotttrotttrott know about the PR, and he'll take a look at it when he has some time

**Comment by flokli** [comment]
With https://github.com/grafana/grafana-api-golang-client/pull/32 being merged, we would probably need to bump the go.mod and set NumRetries to fix this?

**Comment by julienduchesne** [comment]
> With [grafana/grafana-api-golang-client#32](https://github.com/grafana/grafana-api-golang-client/pull/32) being merged, we would probably need to bump the go.mod and set NumRetries to fix this?

Yes, would you open a PR for this? I'll look at it right away!

**Comment by flokli** [comment]
Sure, it's up at https://github.com/grafana/terraform-provider-grafana/pull/284. Please do verify it does work as expected, though, and maybe that parameter needs to be increased to work with Grafana Cloud.
