### ISSUE TITLE
Upstream Library Ownership

### ISSUE THREAD

**Issue by mlclmj** [grafana/terraform-provider-grafana#26]
Hi there,

I'm interested in adding additional functionality to this provider, and have hit a bit of a roadblock: it isn't clear who the maintaining party of the upstream library is.

From what I can gather, it appears that the library was changed in #16, and @apparentlymart voiced that [he's no longer able to maintain it](https://github.com/apparentlymart/go-grafana-api/pull/6#issuecomment-367135123). 
I haven't had any success reaching out to @teemupo who is the owner of the current fork, and judging by the fact that his [PR](https://github.com/apparentlymart/go-grafana-api/pull/7) remains open, I'd presume he doesn't have a strong interest in maintaining it either.

It appears to me that the upstream library is in need of a more permanent home, any ideas on what would be the best course of action here?

If no one else is in a position to do so, we'd like to offer to take ownership of the upstream library and maintain it, pulling back in contributions that have been made on other forks as well.

cc @sbower @msuterski @tonglil

**Comment by pearkes** [comment]
Hey @mlclmj! I'm maintaining this provider and am supportive of a PR to replace the library with a different fork or different library that can be maintained more actively. Does it make sense -- if @apparentlymart is open to it -- for him to to transfer ownership of his library to you? 

Then you could pull in @teemupo's changes required in #16, and make a PR here to change the library to wherever the namespace is you'll be maintaining it under is.

**Comment by mlclmj** [comment]
Hey @pearkes!
Absolutely, that sounds like a great plan. If @apparentlymart is open to transferring it to me, my team would be more than willing to maintain it from under our organization and getting those outstanding PRs merged in.

**Comment by teemupo** [comment]
Hi @mlclmj! Sorry, have missed these notifications. Like mentioned above, @apparentlymart is the original owner of the library, I was just trying to make a small PR for it (without much luck). Didn't realise my fork of it is now actually used in the provider...

**Comment by mlclmj** [comment]
Hey @teemupo! No worries, that's roughly what we figured had happened. I'm working with @apparentlymart now to find a permanent home for the library (and we'll be able to get your PR merged in as well 😄).

**Comment by mlclmj** [comment]
Thanks to @apparentlymart, the library has been moved and is now living at https://github.com/nytm/go-grafana-api 

I'll be putting in a PR shortly to change the references to the library within the provider. Thanks all!
