### ISSUE TITLE
Difference between grafana provider docs an implementation

### ISSUE THREAD

**Issue by xocasdashdash** [grafana/terraform-provider-grafana#262]
### Terraform Version
* Terraform: 0.14.5
* Terraform Grafana Provider: latest

### Affected Resource(s)
Please list the resources as a list, for example:
* grafana_folder

### Expected Behavior
According to the grafana provider docs for the [grafana_folder](https://registry.terraform.io/providers/grafana/grafana/latest/docs/resources/folder) the resource supports an "id" parameter to force the folder id and getting consistent folder urls. 

### Actual Behavior
The parameter does not exist and it fails to plan. Here https://github.com/grafana/terraform-provider-grafana/blob/master/grafana/resource_folder.go#L29-L42 you can see that the parameter is missing 

One of the two is correct, but i'm not sure which one. I'd rather the docs be because i'm using this feature for dashboards already
and I wanted to start using it for folders.

**Comment by xocasdashdash** [comment]
Checking the client [code](https://github.com/grafana/grafana-api-golang-client/blob/master/folder.go#L39-L55), there's no way to add the UID as a parameter so i'm gonna assume the docs are wrong on this one.

**Comment by inkel** [comment]
@xocasdashdash thank you for reporting this! As you correctly said, sadly, passing the UID (which is the right name) isn't possible.

This is an issue with our documentation and the tool that generates it. This should be addressed once #319 is merged and a new version is released.

**Comment by inkel** [comment]
(Reopening this one because it was closed too early)

With #319 merged the documentation will be fixed once a new version is released.

**Comment by xocasdashdash** [comment]
@inkel is there no way of getting "pretty" urls for folders then ? Also on the PR #319 you're never setting the "id" attribute (d.Set("id", bla bal bal)); So you might as well remove it entirely instead of adding it as a computed attribute

**Comment by inkel** [comment]
@xocasdashdash at the time of writing nope, it is impossible yet to define a slug for the folder. We are working towards defining a roadmap of enhancements for the provider but we haven't yet prioritized doing something like this. Having said that, this is now being tracked in #323.

As for the ID attribute, if we remove it entirely then the document generator tool will again generate misleading documentation telling the user it's possible to pass the ID. Given that this value is [internal and autogenerated](https://grafana.com/docs/grafana/latest/http_api/folder/#identifier-id-vs-unique-identifier-uid), we can define it as a computed attribute which could be useful for `output` blocks while fixing the documentation issue at the same time.

**Comment by julienduchesne** [comment]
`v1.18.0` was released an `id` is now marked as read-only
