### ISSUE TITLE
Library Panels API

### ISSUE THREAD

**Issue by justinTM** [grafana/terraform-provider-grafana#278]
https://github.com/grafana/grafana/pull/39829

**Comment by justinTM** [comment]
so the [grafana golang api](https://github.com/grafana/grafana-api-golang-client) is deprecated which is awesome and cool.

**Comment by fracasula** [comment]
Does the Terraform provider support Library Panels at all at the moment? I had a look at the [docs](https://registry.terraform.io/providers/grafana/grafana/latest/docs/resources/folder) and I can see that folders and dashboards are supported but not library panels? :thinking:

**Comment by fracasula** [comment]
Right, I see that there is a [PR](https://github.com/grafana/terraform-provider-grafana/pull/331), so it's a work in progress.

I'm really looking forward to test this out :+1:

**Comment by justinTM** [comment]
@fracasula resource `grafana_library_panel` has been merged into master! data source for library panel and dashboard -- along with examples for generating a dashboard containing a library panel -- will follow probably this week.

**Comment by justinTM** [comment]
closed with #331

**Comment by julienduchesne** [comment]
This has been released in v1.19.0
