### ISSUE TITLE
Create Team doesn't allow orgId value to be specified

### ISSUE THREAD

**Issue by iamgeef** [grafana/terraform-provider-grafana#279]
The Grafana API for creating a team supports the use of orgId value: https://grafana.com/docs/grafana/latest/http_api/team/#add-team

But it's not available in Terraform Provider: 
```
Error: Unsupported argument

   on grafana.tf line 31, in resource "grafana_team" "phd-viewers":
   31:   OrgId    = grafana_organization.phd.org_id

 An argument named "OrgId" is not expected here.
```

Go API doesn't have support either: https://github.com/grafana/grafana-api-golang-client/blob/master/team.go

Feature will need to go into Go API first then TF provider.

**Comment by bnjns** [comment]
Are teams configured similarly to things like data sources etc, where it uses the `org_id` of the provider configuration?

**Comment by iamgeef** [comment]
It's optional 
![image](https://user-images.githubusercontent.com/10751405/144337961-f4d99619-c751-4f98-84cc-a7a0954ed16f.png)

**Comment by bnjns** [comment]
Yeah, but you can also specify the org_id in the provider config, which is then used for all resources that provider manages? So you may need 1 provider per org, and then use that to configure teams in the correct org. This is how we handle data sources, dashboards, notification channels, etc.

https://registry.terraform.io/providers/grafana/grafana/latest/docs#optional

**Comment by justinTM** [comment]
Pretty sure the Go API is only taking maintenance PR’s and is otherwise deprecated right?
