### ISSUE TITLE
Go panic: interface conversion with secure_settings attribute during grafana_alert_notification ressource creation

### ISSUE THREAD

**Issue by mehdiElma** [grafana/terraform-provider-grafana#280]
### Terraform Version
* Terraform: 0.15.3
* Terraform Grafana Provider: 1.14.0
* Grafana: 7.4.5

### Affected Resource(s)
* grafana_alert_notification

### Terraform Configuration Files
```
terraform {
  required_version = "= 0.15.3"
  required_providers {
    grafana = {
      source = "grafana/grafana"
      version = "=1.14.0"
    }
  }

provider "grafana" {
  url  = var.grafana_url
  auth = "${var.grafana_auth_username}:${var.grafana_auth_password}"
  org_id = var.grafana_org_id
}

resource "grafana_alert_notification" "monitoring" {
  name          = "Monitoring notification channel"
  type          = "email"
  is_default    = false
  send_reminder = true
  frequency     = "24h"
  settings = {
    addresses   = var.grafana_addresses_gitlab_monitoring
    uploadImage = "true"
  }
}

```

### Panic Output
https://gist.github.com/mehdiElma/b4404e4ddb246d0633a33ea851a4bf45

### Expected Behavior
Create grafana_alert_notification with terraform and without any error.

### Actual Behavior
Create grafana_alert_notification with terraform failed because of a Go panic interface conversion error.

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`

I think the issue is due to this line : https://github.com/grafana/terraform-provider-grafana/blob/8eb0a8453d3b6a0c4a8ea579905c77895867d06e/grafana/resource_alert_notification.go#L163

```
for k, v := range alertNotification.SecureFields.(map[string]interface{}) {
		boolVal, ok := v.(bool)
		switch {
		case ok && boolVal:
			secureSettings[k] = "true"
		case ok && !boolVal:
			secureSettings[k] = "false"
		default:
			secureSettings[k] = v
		}
}
```
It tryed to make a range on an attribute, alertNotification.SecureFields, that doesn't exist (nil value), to get data from secure_settings. The makeAlertNotification function return this :  
```
return &gapi.AlertNotification{
		ID:                    id,
		Name:                  d.Get("name").(string),
		Type:                  d.Get("type").(string),
		IsDefault:             d.Get("is_default").(bool),
		DisableResolveMessage: d.Get("disable_resolve_message").(bool),
		UID:                   d.Get("uid").(string),
		SendReminder:          sendReminder,
		Frequency:             frequency,
		Settings:              settings,
		SecureSettings:        secureSettings,
	}, err
```
There is no **SecureFields** attribute on AlertNotification, I think it should be **SecureSettings** instead.

I'm a newby in Go, can you help me please ?

**Comment by inkel** [comment]
Note that the provider version is 3 month updated at least. Please try upgrading to at least 1.17.0 and see if the issue persists. Note that in that version we have #234 open, which was fixed in #322 and should be fixed once we cut a new release.

Feel free to reopen this issue if the problem persists at that time, thanks.
