### ISSUE TITLE
Support creating alert rules

### ISSUE THREAD

**Issue by gsaraf** [grafana/terraform-provider-grafana#281]
I'm a new user of Grafana cloud, and have a bunch of synthetic checks that I defined alert rules on. i.e. if they fail more than X% of the time in the past Y minutes -> alert.

It is quite tedious to define the same rules for multiple hosts, so I am trying to figure out if I can define them using Terraform. AFAICT however, there isn't a Terraform resource for defining alert rules. Is that right? Can one be added?

I'm happy to take a stab at this (though I'm pretty new to Terraform and Grafana).

Thanks!

**Comment by inkel** [comment]
Hi, @gsaraf! Thank you for your interest.

> …there isn't a Terraform resource for defining alert rules. Is that right?

You're correct, currently there's no support for defining alert notifications in the provider.

> Can one be added?
> 
> I'm happy to take a stab at this (though I'm pretty new to Terraform and Grafana).

Yes, it could be added! If you want to take a stab and submit a PR I'll happily review it. I cannot make any promises on what the outcome will be, but I'm confident we might get something going.

**Comment by ahayworth** [comment]
@inkel I was taking a look at implementing at least basic support for this today, but it looks like it'd require changes to `grafana/grafana-api-golang-client`.

Does that match your understanding? If so, would changes to that repo be accepted as well? It's listed as deprecated and I wasn't sure if the right path forward was continuing to extend `grafana/grafana-api-golang-client`, or if we should be consuming the [ngalert openapi definitions](https://github.com/grafana/grafana/blob/main/pkg/services/ngalert/api/tooling/post.json) in this repo instead.

Curious what you think!

**Comment by inkel** [comment]
@ahayworth sorry for the delay!

You are correct, the `grafana/grafana-api-golang-client` is where the changes should be done, even if it's marked as deprecated. Feel free to submit a PR there and assign me as a reviewer, I'll be happy to help.

**Comment by inkel** [comment]
@ahayworth sorry for the delay!

You are correct, the `grafana/grafana-api-golang-client` is where the changes should be done, even if it's marked as deprecated. Feel free to submit a PR there and assign me as a reviewer, I'll be happy to help.

**Comment by julienduchesne** [comment]
Duplicate of https://github.com/grafana/terraform-provider-grafana/issues/57. I'll be working on adding `ngalert` support 🔜
