### ISSUE TITLE
unmarshal JSONData.jsonData.esVersion after clicking in Grafana

### ISSUE THREAD

**Issue by SebastianThorn** [grafana/terraform-provider-grafana#305]
### Terraform Version
* Terraform: v1.1.0
* Terraform Grafana Provider: v1.9.0
* Grafana: Grafana v8.2.5 (b57a137acd)

$ terraform version
Terraform v1.1.0
on linux_amd64
+ provider registry.terraform.io/grafana/grafana v1.9.0
+ provider registry.terraform.io/hashicorp/vault v2.21.0

### Affected Resource(s)
Please list the resources as a list, for example:
* grafana_source

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl

#
# Creating variable for Elasticsearch-datasources
variable "elasticsearch_datasources" {
  description = "Datasources for Elasticsearch"
  type        = set(string)
  default     = [
    "telegraf_logs",
  ]
}

#
# Using variable elasticsearch_datasources
resource "grafana_data_source" "elasticsearch_prd_elastic_datasources_v1" {
  for_each      = var.elasticsearch_datasources
  type          = "elasticsearch"
  name          = "TF elasticsearch_prd_${each.value}_v1"
  url           = "https://p-elastic-01.itp.example.org:9200"
  database_name = "${each.value}*"
  basic_auth_enabled  = true
  basic_auth_username      = data.vault_generic_secret.graylog.data["elastic_admin_username"]
  basic_auth_password      = data.vault_generic_secret.graylog.data["elastic_admin_password"]
  json_data {
    es_version = "60"
    time_field = "timestamp"
  }
}

```

### Debug Output
https://gist.github.com/SebastianThorn/ddaee3fa0e187a3a358a38abed0571ae

### Expected Behavior
Nothing

### Actual Behavior
Complains about `JSONData.jsonData.esVersion`

```Error: json: cannot unmarshal string into Go struct field JSONData.jsonData.esVersion of type int64
│
│   with grafana_data_source.elasticsearch_prd_elastic_datasources_v1["telegraf_logs"],
│   on sources_elastic.tf line 17, in resource "grafana_data_source" "elasticsearch_prd_elastic_datasources_v1":
│   17: resource "grafana_data_source" "elasticsearch_prd_elastic_datasources_v1" {
│
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
2. Press the "Test And Save" button in Grafana
3. `terraform apply`
4. Breaks

### References
I'm guessing this is because of the reasons below.
- https://github.com/grafana/terraform-provider-grafana/issues/243
- https://github.com/grafana/terraform-provider-grafana/pull/267

**Comment by julienduchesne** [comment]
Should be fixed in v1.14.0+
