### ISSUE TITLE
Error: authorization token required

### ISSUE THREAD

**Issue by justinTM** [grafana/terraform-provider-grafana#307]
### Terraform Version
* Terraform: 1.0
* Terraform Grafana Provider: 1.16.0
* Grafana: 8.3.3

### Affected Resource(s)
Please list the resources as a list, for example:
* data grafana_synthetic_monitoring_probes

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl

provider "grafana" {
  url     = var.url
  auth    = var.auth
  org_id = 1
}

data "grafana_synthetic_monitoring_probes" "main" {}
```

### Debug Output
[Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.](https://gist.github.com/justinTM/310c0040bfd84034b64c9fff42782d0a)

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
Authentication from grafana provider should have authenticated with the synthetic monitoring data source, just as it successfully applied for the grafana synthetic monitoring CHECK RESOURCE.

**Comment by julienduchesne** [comment]
Are you setting a synthetic monitoring token: https://registry.terraform.io/providers/grafana/grafana/latest/docs#sm_access_token?

**Comment by justinTM** [comment]
Thanks for sharing that, yeah I found that after posting the issue. However, I can't figure out how to get the following values:
- stackId
- metricsInstanceId
- logsInstanceId

I am using Grafana Cloud.

**Comment by justinTM** [comment]
[2021-12-28-Generating-an-Access-Token-for-Synthetic-Monitoring.pdf](https://github.com/grafana/terraform-provider-grafana/files/7785949/2021-12-28-Generating-an-Access-Token-for-Synthetic-Monitoring.pdf)

**Comment by IppX** [comment]
@justinTM check out https://github.com/grafana/synthetic-monitoring-app/#configuration

**Comment by justinTM** [comment]
thanks, i definitely saw that before posting. found it to not apply for my circumstances, and the instructions were not very helpful.

**Comment by IppX** [comment]
> thanks, i definitely saw that before posting. found it to not apply for my circumstances, and the instructions were not very helpful.

Me too! That's why I submitted a PR that adds this block of information that was merged yesterday:

> Configuration details:
>
>    apiHost expects Synthetic Monitoring API URL, see more details here
>
>    stackId expects an integer and can be found using gcom /instances/<orgSlug>, or by visiting https://grafana.com/orgs/<orgSlug>/stacks and clicking the details button on stack you are connecting to. The id will be in the URL.
>
>   The logs and metrics section are instructing the plugin which datasources it needs to use.
>        The grafanaName needs to exactly match the names specified in your datasource provisioning
>        The hostedId expects an integer and is the same value as the basicAuthUser in your datasource provisioning. The value can also be found from the details page of loki or prometheus at https://grafana.com/orgs/<orgSlug>/stacks.
>
>    publisherToken needs to be a grafana.com api key with a MetricsPublisher role. This is what the probes use to publish metrics to your cloud stack.

Hope it helps!

**Comment by inkel** [comment]
Hi @justinTM, did the instructions in the message above worked for you?

**Comment by justinTM** [comment]
they did indeed thanks @inkel
