### ISSUE TITLE
Support external_id for CloudWatch grafana_data_source

### ISSUE THREAD

**Issue by danil-smirnov** [grafana/terraform-provider-grafana#308]
Hi,

There is `assume_role_arn` parameter for CloudWatch grafana_data_source but there is no `external_id` one, which makes IAM role assuming more secure (see the screenshot).

Are there any plans of adding it?

<img width="811" alt="Screenshot 2021-12-16 at 15 20 27" src="https://user-images.githubusercontent.com/27999539/146379480-07d2c955-8713-4f3a-9a80-1896bc05a876.png">

**Comment by julienduchesne** [comment]
This has been released in v1.19.0
