### ISSUE TITLE
Feature request: allow passing custom UID in `grafana_folder`

### ISSUE THREAD

**Issue by inkel** [grafana/terraform-provider-grafana#323]
As a byproduct of #262 we have identified [it isn't possible](https://github.com/grafana/terraform-provider-grafana/blob/b14d03cb31e8fff24066a61fda8f9531cb78c958/grafana/resource_folder.go#L30-L33) to pass a custom UID for a folder, even when it's [supported by the API](https://grafana.com/docs/grafana/latest/http_api/folder/#identifier-id-vs-unique-identifier-uid).

We should allow users passing this value, provided we add a validation check for their format.

**Comment by justinTM** [comment]
I will be curious to see this. Was confusing myself about setting/getting UID while working on the Library Panels functionality this weekend. Basically curious how Terraform provider Go code handles users specifying the UID. Computed: True, Optional: True?

**Comment by julienduchesne** [comment]
Support for this was released in [v1.21.0](https://github.com/grafana/terraform-provider-grafana/releases/tag/v1.21.0)
