### ISSUE TITLE
:sparkles: Add GitHub as a data source

### ISSUE THREAD

**Issue by Gary-H9** [grafana/terraform-provider-grafana#335]
Forgive me if I am mistaken but I cannot see how to call GitHub as a datasource. I don't think this is currently possible.

Specifically, I need to be able to pass an access token variable to the grafana_data_source resource.

If possible can someone point me to the correct place in the code and I will attempt to add this functionality?

What I would expect the data source to look like eventually:
```
resource "grafana_data_source" "github_data_source" {
  name         = "GitHub"
  type         = "grafana-github-datasource"
  access_token = var.github_access_token
}
```
I think the type should be `grafana-github-datasource` as the below appears in grafana dashboard JSON for dashboards which use the GitHub datasource.
```
    {
      "datasource": {
        "type": "grafana-github-datasource",
        "uid": "8pN6pcO7k"
      },
```

The datasource in grafana:

![image](https://user-images.githubusercontent.com/26419401/149121529-0e256305-4771-42a9-83b4-c2d6f6a8954c.png)

[Grafana Datasource Documentation](https://registry.terraform.io/providers/grafana/grafana/latest/docs/resources/data_source)

**Comment by julienduchesne** [comment]
👋  The Github data source has two settings: 
- `accessToken` which should in the secure data: https://github.com/grafana/grafana-api-golang-client/blob/master/datasource.go#L201
- `githubUrl` which should go in regular json data: https://github.com/grafana/grafana-api-golang-client/blob/master/datasource.go#L75

Once the client is updated, you can add the fields to the provider here: 
- json data: https://github.com/grafana/terraform-provider-grafana/blob/master/grafana/resource_data_source.go#L87 
- secure json data: https://github.com/grafana/terraform-provider-grafana/blob/master/grafana/resource_data_source.go#L305

**Comment by Gary-H9** [comment]
Hi @julienduchesne, thanks for the above information, I didn't really know where to start so this really helped. 

Required elements were added to grafana-api-golang-client in v.0.2.3 as per [this](https://github.com/grafana/grafana-api-golang-client/pull/50). 

I have made, what I think are the correct updates for terraform-provider-grafana, to [this](https://github.com/Gary-H9/terraform-provider-grafana) repository.

**Comment by julienduchesne** [comment]
> Hi @julienduchesne, thanks for the above information, I didn't really know where to start so this really helped.
> 
> Required elements were added to grafana-api-golang-client in v.0.2.3 as per [this](https://github.com/grafana/grafana-api-golang-client/pull/50).
> 
> I have made, what I think are the correct updates for terraform-provider-grafana, to [this](https://github.com/Gary-H9/terraform-provider-grafana) repository.

👍  Please open a pull request from your repo to this one (`grafana/terraform-provider-grafana`) so that I can review the changes

**Comment by Gary-H9** [comment]
Apologies. I've done so now thanks.

**Comment by julienduchesne** [comment]
Implemented here: https://github.com/grafana/terraform-provider-grafana/pull/340. Will be part of next release (v1.19.0)

**Comment by Gary-H9** [comment]
Thanks @julienduchesne. This is my first contribution to an open source project, very exciting!

**Comment by inkel** [comment]
Well done, @Gary-H9!!! 👏🏽 Thanks for choosing this project for your first contribution 😺
