### ISSUE TITLE
Support for opensearch data source plugin

### ISSUE THREAD

**Issue by Fran-Rg** [grafana/terraform-provider-grafana#343]
From: https://grafana.com/grafana/plugins/grafana-opensearch-datasource/

The resource could look like this:
```
resource "grafana_data_source" "envesmonitoring_opensearch" {
    type = "grafana-opensearch-datasource"
    name = "${var.environment}-Opensearch"
    url = "XYZ"
    database_name = "monitoring-*"
    access_mode = "proxy"

    json_data {
         ~ ELASTICSEARCH
    }
}
```

At the moment the above works without the json_data block but the provider then thinks it's a cloudwatch source and restrict the json_data fields that can be set.
The fields supported look to be really similar to the opensearch ones

**Comment by inkel** [comment]
That `~ ELASTICSEARCH` value for `json_data`, is it a placeholder? Can you provide an example with redacted values?

Thank you.

**Comment by llpetkova** [comment]
`resource "grafana_data_source" "envesmonitoring_opensearch" {
    type = "grafana-opensearch-datasource"
    name = "${var.environment}-Opensearch"
    url = "XYZ"
    database_name = "monitoring-*"
    access_mode = "proxy"

    json_data {
         time_field = "timestamp"
    }
}`

The above on apply returns:
`The argument "auth_type" is required, but no definition was found.
  The argument "default_region" is required, but no definition was found.
  An argument named "time_field" is not expected here.`
  
 
  After adding the needed Opensearch details(index name and time field name) manually, the datasource looks like this:
    `{'access': 'proxy',
  'basicAuth': False,
  'database': 'monitoring-*',
  'id': 11,
  'isDefault': False,
  'jsonData': {'database': 'monitoring-*',
               'flavor': 'opensearch',
               'logLevelField': '',
               'logMessageField': '',
               'maxConcurrentShardRequests': 5,
               'pplEnabled': True,
               'timeField': 'timestamp',
               'version': '1.0.0'},
  'name': 'test-Opensearch',
  'orgId': 1,
  'password': '',
  'readOnly': False,
  'type': 'grafana-opensearch-datasource',
  'typeLogoUrl': 'public/plugins/grafana-opensearch-datasource/img/logo.svg',
  'typeName': 'OpenSearch',
  'uid': 'A1BlaBla',
  'url': 'https://XYZ',
  'user': ''}`

**Comment by llpetkova** [comment]
```
resource "grafana_data_source" "envesmonitoring_opensearch" {
    type = "grafana-opensearch-datasource"
    name = "${var.environment}-Opensearch"
    url = "XYZ"
    database_name = "monitoring-*"
    access_mode = "proxy"
    json_data {
           time_field = "timestamp"
    }
}
```

The above on apply returns:

```
The argument "auth_type" is required, but no definition was found.
The argument "default_region" is required, but no definition was found.
An argument named "time_field" is not expected here.
```

And after adding the needed Opensearch details(index name and time field name) manually in Grafana, the datasource configuration looks like this:

```
{'access': 'proxy',
  'basicAuth': False,
  'database': 'monitoring-*',
  'id': 11,
  'isDefault': False,
  'jsonData': {'database': 'monitoring-*',
               'flavor': 'opensearch',
               'logLevelField': '',
               'logMessageField': '',
               'maxConcurrentShardRequests': 5,
               'pplEnabled': True,
               'timeField': 'timestamp',
               'version': '1.0.0'},
  'name': 'test-Opensearch',
  'orgId': 1,
  'password': '',
  'readOnly': False,
  'type': 'grafana-opensearch-datasource',
  'typeLogoUrl': 'public/plugins/grafana-opensearch-datasource/img/logo.svg',
  'typeName': 'OpenSearch',
  'uid': 'A1BlaBla',
  'url': 'https://XYZ',
  'user': ''}
  ```

**Comment by edgargalan-drizly** [comment]
Hello, i have also expressed interesting in trying to add opensearch as a type for the provider to use. is this still on the provider list of desired features? 

Is there a similar provider type that can provide me with what i need or is that a no go?

**Comment by Fran-Rg** [comment]
Use the elastic search provider with version 7.x +. Works in 99% of the cases
