### ISSUE TITLE
Add Support for Sentry Plugin

### ISSUE THREAD

**Issue by DrFaust92** [grafana/terraform-provider-grafana#346]
https://grafana.com/grafana/plugins/grafana-sentry-datasource/

the `json_data` arg is missing `org_slug`
the `secure_json_data` is missing `auth_token`

**Comment by inkel** [comment]
Hi @DrFaust92, I'm not sure what are you referring to, could you please explain it a bit better? Thanks.

**Comment by DrFaust92** [comment]
Hi @inkel,

the [data source resource](https://registry.terraform.io/providers/grafana/grafana/latest/docs/resources/data_source)
[json_data](https://registry.terraform.io/providers/grafana/grafana/latest/docs/resources/data_source#nested-schema-for-json_data) does not support the `org_slug` arg needed to passed to grafana API to define a sentry data source.

same thing for the [secure_json_data](https://registry.terraform.io/providers/grafana/grafana/latest/docs/resources/data_source#nested-schema-for-secure_json_data) with the `auth_token` arg.

Is this clearer now?

**Comment by inkel** [comment]
Sorry for the long delay in responding. Yes, now it is clearer, thanks.

I'll assign this to myself and try and add those attributes.

**Comment by julienduchesne** [comment]
This is now supported in v1.20.0
