### ISSUE TITLE
Resource to control the new style of alerting provided in Grafana 8.X

### ISSUE THREAD

**Issue by logan-bobo** [grafana/terraform-provider-grafana#348]
Currently, the only resource for managing alert notifications is `grafana_alert_notification`. In the newer version of grafana, this provider does not look to have a way to manage contact points - (https://grafana.com/docs/grafana/latest/alerting/unified-alerting/contact-points/). Happy to actually pick this up but may need some initial direction. Would love to contribute.

**Comment by julienduchesne** [comment]
Alerting is tracked in this issue: https://github.com/grafana/terraform-provider-grafana/issues/57
