### ISSUE TITLE
PagerDuty setting for grafana_alert_notification is coerced into an invalid value

### ISSUE THREAD

**Issue by philipcristiano** [grafana/terraform-provider-grafana#35]
While trying to set `grafana_alert_notification`s I ran into a problem with the setting for PagerDuty type setting of `autoResolve` being set to a value that didn't work for Grafana.

### Terraform Version
0.11.7

### Affected Resource(s)
- `grafana_alert_notification`

### Terraform Configuration Files
```
resource "grafana_alert_notification" "pagerduty" {
  name = "${var.service_name} - PagerDuty"
  type = "pagerduty"
  is_default = false

  settings {
    "integrationKey" = "${pagerduty_service_integration.grafana.integration_key}"
    "autoResolve" = true
  }
}
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Expected Behavior
The alert notification should have an enabled `autoResolve`. 

### Actual Behavior
The value in Grafana appears to be a `"1"` even when the HCL has `true`. This results in a defaulted `false` for the behavior. The `"1"` is stored in the Grafana DB (as relayed to me by a Grafana.com staff member. 

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Using hosted grafana.com

### References

I'll add more debug information as I can gain access to it.

**Comment by philipcristiano** [comment]
Thanks! Any info about when this might get a release?

**Comment by mlclmj** [comment]
@philipcristiano Sorry for the delay with this, I'm working on a release at the moment. Will update you here when it's done!

**Comment by philipcristiano** [comment]
Wonderful!

**Comment by mlclmj** [comment]
1.3.0 Should be available now!
