### ISSUE TITLE
Add support for Grafana on call

### ISSUE THREAD

**Issue by alekhrycaiko** [grafana/terraform-provider-grafana#357]
Grafana On Call resources would be something I'd like to define in Terraform for on-call management.

[Currently there is an API available ](https://grafana.com/docs/grafana-cloud/oncall/oncall-api-reference/) and I'm curious whether there's any interest in this provider supporting these resources.

**Comment by ryanisnan** [comment]
Thank you @alekhrycaiko - this would be incredibly useful for us. I found https://github.com/alertmixer/terraform-provider-amixr, but I'm not clear if this is usable as a temporary stand-in compatible with Grafana cloud.

**Comment by landonnewberry** [comment]
+1 this would be very helpful

**Comment by abhinav913** [comment]
yeah this would be huge

**Comment by inkel** [comment]
> I'm curious whether there's any interest in this provider supporting these resources

Hi! Yes, I can confirm that there is interest in supporting these resources. We don't have yet an estimated date of delivery, but I'll post it here as soon as we have it.

Thank you for your interest!

**Comment by alekhrycaiko** [comment]
@inkel I have some interest in contributing a few resources from Grafana on call as I'd like to consume these for on call management. Integrations is of particular interest on my end. 

I'm also curious whether there's any resources/standards this provider has for OS contributions. I haven't come across anything but if there are that'd be stellar to be directed to 🙏

**Comment by julienduchesne** [comment]
> @inkel I have some interest in contributing a few resources from Grafana on call as I'd like to consume these for on call management. Integrations is of particular interest on my end.
> 
> I'm also curious whether there's any resources/standards this provider has for OS contributions. I haven't come across anything but if there are that'd be stellar to be directed to 🙏

We are already currently implementing all of the resources: https://github.com/grafana/terraform-provider-grafana/pull/456

**Comment by alekhrycaiko** [comment]
Oh, amazing! Didn't see that. Much appreciated @julienduchesne

**Comment by inkel** [comment]
Hah! I was coming to say that, it's already in the works!

**Comment by julienduchesne** [comment]
Supported added in https://github.com/grafana/terraform-provider-grafana/pull/456. Released in v1.22.0!
