### ISSUE TITLE
Ability to update group and display name in a grafana_role resource

### ISSUE THREAD

**Issue by vtorosyan** [grafana/terraform-provider-grafana#379]
### Context

Grafana fine-grained access control supports now `group` (used to group roles under one header in the role picker in UI) and `disply_name` (used as a friendly display name in the UI) attributes for the role. 

We should update `grafana_role` resource to include the new attributes.

### Implementation proposal

Both of the fields are optional, but there is a caveat with `display_name`. When display name of the role is not specified, Grafana backend returns a fallback option, which defaults to the `name` of the role. This is a problem for provisioning a resource in idempotent way, since skipping the field in the resource definition will result in out-of-date state in the terraform. 

One suggestion would be to make the display_name a required field in the terraform.

**Comment by inkel** [comment]
> One suggestion would be to make the display_name a required field in the terraform.

This could probably be confusing for users. IIRC the AWS provider does something similar for descriptions, where if you don't provide one it defaults to something like _Managed by Terraform_. We could have the provider using the value of `name` for `display_name` and have it documented in the attribute description.

**Comment by vtorosyan** [comment]
Makes me think, maybe we should just change the backend to resolve the display name on write, not on read. Couple of more bytes in the role, but I can't see any other trade-offs 🤔 

Update: I realized it does not solve the problem, so please ignore me comment.

**Comment by vtorosyan** [comment]
This is resolved no by #495
