### ISSUE TITLE
Documentation missing quote

### ISSUE THREAD

**Issue by zakkg3** [grafana/terraform-provider-grafana#39]
The github MD its ok but in the terraform page there is a missing quote in the test-org's name param.
 
resource "grafana_organization" "test-org" {
    name         = "Test Organization this is missing ->"

https://github.com/terraform-providers/terraform-provider-grafana/blob/master/website/docs/r/organization.html.md

https://www.terraform.io/docs/providers/grafana/r/organization.html

**Comment by mlclmj** [comment]
Hi @zakkg3 -- This was fixed recently in #32 but hasn't been released yet. A new version with this fix will be released shortly. Thanks!
