### ISSUE TITLE
[Feature Request]: Add Grafana Cloud API Keys as resource.

### ISSUE THREAD

**Issue by Skeen** [grafana/terraform-provider-grafana#393]
### Disambiguation

This feature request is regarding Grafana Cloud API Keys, as created by the `https://grafana.com/api/orgs/magenta/api-keys` endpoint.
It does not regard the currently managed Grafana api-keys via the `/api/auth/keys` endpoint.

### Motivation

We manage our infrastructure with Terraform creating new execution environments on a regular basis.
Each execution environment is deployed with Grafana Agent, and thus needs its own metrics publisher api-key.
This leads to a lot of distinct api keys being required.

### Describe the solution you'd like

Add Grafana Cloud API Keys as resource to the provider:
```
resource "grafana_cloud_api_key" "cluster_name" {
  name = "grafana_agent_cluster_name"
  role = "MetricsPublisher"
}
```
To allow for automation of key creation and provider interoperability using Terraform.

### Describe alternatives you've considered

Currently all the api keys we use must be made by hand. This is a lot of manual labor.
An alternative solution, which is probably even worse is api-key reuse.

**Comment by julienduchesne** [comment]
This was added in [v1.21.0](https://github.com/grafana/terraform-provider-grafana/releases/tag/v1.21.0)
