### ISSUE TITLE
Support Unified Alerts

### ISSUE THREAD

**Issue by StefanFW** [grafana/terraform-provider-grafana#394]
Grafana introduced [Unified Alerts](https://grafana.com/docs/grafana/latest/alerting/unified-alerting/) with Version 8.0 but they could not be used with the Terraform provider.

A workaround is to disable the unified alerts and enable the legacy alerts in the config

```
[alerting]
    enabled = true

[unified_alerting]
    enabled = false
```

Maybe you could add this to the documentation of the `grafana_alert_notification` resource till the new feature is implemented.

Are there already plans to integrate the new alerts?

**Comment by mikaello** [comment]
> Are there already plans to integrate the new alerts?

Seems like the answer to this is "Yes", see https://github.com/grafana/terraform-provider-grafana/issues/57#issuecomment-1010185647

**Comment by maestroi** [comment]
I was wondering if there is some progress on the terraform side of Unified Alerts, seems good product to use!

**Comment by julienduchesne** [comment]
There hasn't been any progress on the Terraform side. The API will be finalized and released in Grafana 8.5 (expected to release this month: https://github.com/grafana/grafana/milestone/280), so we can't start yet

**Comment by chad-barensfeld-exa** [comment]
Looking forward to this feature

**Comment by julienduchesne** [comment]
We'll track this here: https://github.com/grafana/terraform-provider-grafana/issues/57
