### ISSUE TITLE
Automatically update the list of Grafana versions

### ISSUE THREAD

**Issue by julienduchesne** [grafana/terraform-provider-grafana#411]
As mentioned here: https://github.com/grafana/terraform-provider-grafana/pull/410#issuecomment-1059223204, the list of Grafana versions maintained here: https://github.com/grafana/terraform-provider-grafana/blob/master/.drone/drone.jsonnet#L1 could be automatically generated so we don't have to look at Grafana release notes to find new releases

**Comment by mdb** [comment]
> could be automatically generated 

@julienduchesne What source of data do you imagine driving the automation? And what are the business rules driving the list? For example, do you imagine using the GitHub releases API to fetch the latest Grafana minor version GitHub release for each major version release? Or are you imagining something else?

**Comment by julienduchesne** [comment]
Following exploration of this issue and possible solutions by @mdb in https://github.com/grafana/terraform-provider-grafana/pull/572, I have decided not to pursue this issue further
