### ISSUE TITLE
Allow skipping TLS verify in datasources

### ISSUE THREAD

**Issue by subesokun** [grafana/terraform-provider-grafana#42]
Please add support for setting the `skip TLS verify` flag via the `grafana_data_source` resource for Prometheus datasources. Our test environment is using LE staging certificates which will cause Grafana to fail fetching data due to an untrusted certificate.

### Affected Resource(s)
Please list the resources as a list, for example:
- grafana_data_source

**Comment by mlclmj** [comment]
Hey @subesokun, it looks like support for that was added to the client library we use so I don't see any reason we couldn't support this in the provider. If you have the opportunity to, feel free to open a PR for it, if not I can take a look at it when I get a chance.

**Comment by ericfourrier** [comment]
+1 for postgres also

**Comment by cwcordell** [comment]
I'd like to contribute to this issue.
In looking at the code from the go-grafana-api repo, there is a TlsSkipVerify property but it is within the JSONData struct. Terraform requires that AuthType and DefaultRegion be populated but for a use case that needs to use the skip_tls_verify property and is not using a cloud provider it is not feasible. 

I'd like to leave the TlsSkipVerify property for compatibility with existing implementations but add a SkipTlsVerify property under DataSource. This would involve making changes to the Grafana datasource, which I'll do, as well. 

Please provide feedback concerning this implementation.

**Comment by cwcordell** [comment]
I've opened a PR for the solution to this issue. https://github.com/terraform-providers/terraform-provider-grafana/pull/68
