### ISSUE TITLE
Sync Terraform state with Grafana backend

### ISSUE THREAD

**Issue by subesokun** [grafana/terraform-provider-grafana#43]
TF will fail updating Grafana data sources and dashboards in case they've been manually deleted.

### Affected Resource(s)
- grafana_dashboard
- grafana_data_source

### Expected Behavior
Grafana provider syncs state with the Grafana backend and detects that the resources have been deleted and re-creates them

### Actual Behavior
Grafana provider fails with a HTTP 404 Not Found error because the resources are gone

**Comment by marcomusso** [comment]
Is there any more context on this? @mlclmj adds the label bug and then the issue get closed without explanation even if it has 7 +1s ?
