### ISSUE TITLE
Error: json: cannot unmarshal number 0.00011808529102399268 into Go struct field for grafana_cloud_stack resource

### ISSUE THREAD

**Issue by sergiojvg** [grafana/terraform-provider-grafana#448]
### Terraform Version
* Terraform: 1.1.7
* Terraform Grafana Provider: 1.21.0
* Grafana: Grafana Cloud

### Affected Resource(s)
Please list the resources as a list, for example:
* grafana_cloud_stack

### Terraform Configuration Files
```hcl
provider "grafana" {
  alias         = "cloud"
  cloud_api_key = data.sops_file.secrets.data["grafana_cloud_org_key"]
}

resource "grafana_cloud_stack" "my_stack" {
  provider    = grafana.cloud
  name        = "teststack"
  slug        = "teststack"
  region_slug = "eu"
}

```

### Error

The resource is properly created, and i can run a plan or apply after, but after some time/a couple of retries I get this error and plan will break. It starts happening randomly (or so I think ATM), but once it happens, will continue to happen. I have only been able to bypass this by removing the resources from my state file, manually destroying the stack on grafana cloud, and applying again

```
╷
│ Error: json: cannot unmarshal number 0.00011808529102399268 into Go struct field Stack.hlInstanceCurrentUsage of type int
│ 
│   with grafana_cloud_stack.my_stack,
│   on providers.tf line 62, in resource "grafana_cloud_stack" "my_stack":
│   62: resource "grafana_cloud_stack" "my_stack" {
│ 

```

**Comment by julienduchesne** [comment]
I released a fix in v1.21.1
