### ISSUE TITLE
Support for multiple template types in Grafana on call integration.

### ISSUE THREAD

**Issue by alekhrycaiko** [grafana/terraform-provider-grafana#466]
I'd like to be able to configure multiple template types, not just Slack, when using the Grafana on call integration resource. 

In my case, I've been manually configuring Grafana On Call's Jinja2 integration to form readable messages to send in alerts. In addition, my custom message format from SNS/Alert Manager is missing the `message` key expected by the defaults right now. It'd be helpful if I could modify the Grafana on call Jinja template in Terraform to fit my payload.

**Comment by ryanisnan** [comment]
This is related to the provider not supporting anything other than Slack in the `grafana_oncall_integration` resource: https://registry.terraform.io/providers/grafana/grafana/latest/docs/resources/oncall_integration#nestedblock--templates

**Comment by dnanaklouvi** [comment]
> This is related to the provider not supporting anything other than Slack in the `grafana_oncall_integration` resource: https://registry.terraform.io/providers/grafana/grafana/latest/docs/resources/oncall_integration#nestedblock--templates

Does this also support Teams? I'm really looking for a solution here.

**Comment by DWebb0** [comment]
@DWebb0 Registering my interest here...

**Comment by wr-nathan** [comment]
Registering our need for this too

**Comment by julienduchesne** [comment]
Implemented here: https://github.com/grafana/terraform-provider-grafana/pull/831
