### ISSUE TITLE
Resources to configure grafana server (installation) configuration?

### ISSUE THREAD

**Issue by daluu** [grafana/terraform-provider-grafana#48]
### Terraform Version

Terraform v0.11.7

* provider.grafana - I'm unaware of the version our org is using at the moment. How to find out?

I looked around the docs for the grafana provider: https://www.terraform.io/docs/providers/grafana/index.html.

I see options to configure dashboards, alert notification channels, data sources, and org stuff. But nothing with respect to SMTP email configuration (needed for the email alert notification channels if creating those) nor external image storage (to s3/webdav) configuration that's also an option for alert notification channels.

Are uses expected to configure those out of band outside of the grafana provider using alternate means?

Would be nice if the provider in the future had ways to configure those options. I'm referring to these:

* http://docs.grafana.org/installation/configuration/#smtp
* http://docs.grafana.org/installation/configuration/#external-image-storage
* http://docs.grafana.org/alerting/notifications/#configure-the-link-back-to-grafana-from-alert-notifications
* http://docs.grafana.org/installation/configuration/#domain

**Comment by seboudry** [comment]
I'd don't think this provider can handle these configurations as they are not modifiable from Grafana API.
You should configure SMTP on Grafana instance level.

**Comment by mlclmj** [comment]
As @seboudry said, none of these appear to be configurable through the API; anything configured through Grafana's ini files is generally beyond what this provider is capable of. Closing this for now
