### ISSUE TITLE
Add grafana_organization datasource

### ISSUE THREAD

**Issue by adkinsjd** [grafana/terraform-provider-grafana#480]
It would be helpful to have a datasource which mirrors the grafana_organization resource.

**Comment by wywywywy** [comment]
I've created a new PR that you might be interested in https://github.com/grafana/terraform-provider-grafana/pull/482

**Comment by inkel** [comment]
PR #482 has been merged, thanks @wywywywy for creating it! This will be included in the next version of the provider, I'll let you know once that's done.

**Comment by adkinsjd** [comment]
This is great! Ideally I would also be able to get a list of users (similar to the admins, editors, and viewers list in the resource). It looks like it wouldn't be too difficult to add; maybe I'll have time to give it a shot later in the week.

**Comment by mdb** [comment]
> Ideally I would also be able to get a list of users (similar to the admins, editors, and viewers list in the resource).

@adkinsjd Does PR #551 address this issue in your mind?

**Comment by adkinsjd** [comment]
Yes it does!
