### ISSUE TITLE
Add grafana_organization_preferences resource

### ISSUE THREAD

**Issue by adkinsjd** [grafana/terraform-provider-grafana#481]
This would allow the provisioning of a home dashboard, timezone and theme for a new organization.

**Comment by mdb** [comment]
If I understand correctly, I believe https://github.com/grafana/grafana-api-golang-client/pull/102 is a pre-requisite to a `grafana_organaization_preferences` resource.

**Comment by jesusheredia-consensys** [comment]
I am interested in that as well. 

Someone is working on this?

**Comment by julienduchesne** [comment]
Implemented and released in v1.30.0
