### ISSUE TITLE
Grafana Managed alerts

### ISSUE THREAD

**Issue by datsabk** [grafana/terraform-provider-grafana#490]
The provider currently provides ways to define Alert notification channels using [this](https://registry.terraform.io/providers/grafana/grafana/latest/docs/resources/alert_notification). However, it lacks the ability to create Alert rules using Terraform. 

In a Cloud native deployment, it is important to have Alerts defined either as Kubernetes ConfigMaps or via Terraform. Hereby, Proposing to have a Terraform resource for the same - Happy to take it up myself.

**Comment by julienduchesne** [comment]
Tracking it here: https://github.com/grafana/terraform-provider-grafana/issues/57
