### ISSUE TITLE
Multiple plan and applies for grafana_oncall_integration to complete

### ISSUE THREAD

**Issue by alekhrycaiko** [grafana/terraform-provider-grafana#491]
### Terraform Version
* Terraform: 1.x
* Terraform Grafana Provider: 1.22.x
* Grafana: Grafana Cloud

### Affected Resource(s)
- grafana_oncall_integration

### Expected Behavior

Single plan and apply should fully create the resource.

### Actual Behavior

Applying the default resource takes two plans and applies. Second plan/apply will create the slack channel and link to the escalation and first one will exclude these without any failures.

**Comment by julienduchesne** [comment]
Should be fixed by https://github.com/grafana/terraform-provider-grafana/pull/546
