### ISSUE TITLE
Integrate Grafana 8 Alerting API

### ISSUE THREAD

**Issue by wesley000** [grafana/terraform-provider-grafana#492]
https://editor.swagger.io/?url=https://raw.githubusercontent.com/grafana/grafana/main/pkg/services/ngalert/api/tooling/post.json

Grafana 8 already supports managing Grafana 8 alerting rules with HTTP API. I want to know is there a plan to integrate this HTTP API to manage Grafana 8 alerting rules?

**Comment by julienduchesne** [comment]
Tracking this here: https://github.com/grafana/terraform-provider-grafana/issues/57
