### ISSUE TITLE
Prometheus Datasource scrape_interval

### ISSUE THREAD

**Issue by Darren-Vine** [grafana/terraform-provider-grafana#498]
It is not possible to set the scrape_interval on the datasource.  It would be pretty useful for us as it defaults to 5 seconds.

**Comment by julienduchesne** [comment]
👋 This is actually called `time_interval` in the datasource (and in Grafana): https://registry.terraform.io/providers/grafana/grafana/latest/docs/resources/data_source#time_interval. I'll add this to the description
