### ISSUE TITLE
[Feature Request] Support teams, admin users, users 

### ISSUE THREAD

**Issue by alexgdmx** [grafana/terraform-provider-grafana#51]
In current implementation, it appears terraform-provider-grafana does not support Grafana  teams, admin users, users . It would be great to be able to create them

/api/org/users PATCH to add native admin not role
/api/admin/users
/api/users
/api/teams

**Comment by peimanja** [comment]
Any thoughts on this one? can be really useful for us maintaining teams/users and permissions there

**Comment by brycefisher** [comment]
I'm also pretty interested in this feature. Ultimately, I'd want to be able to set permissions on dashboards by team. That's when this would be super valuable for me.

To me, this is the functionality I'd like to see:

- Create/delete/update teams
- Assign dashboard permissions per team
- Add/remove users from a team

I'd be willing to contribute a PR to that end. @mlclmj would you be interested in receiving a PR (or series of PRs) like this?

**Comment by mlclmj** [comment]
Hey @brycefisher for sure! This sounds like a great addition if you're willing to build it out. A series of smaller PRs is always encouraged since they're easier to review 🙂

I'm guessing this probably requires changes to the `go-grafana-api` library as well--feel free to request a review from me in either and I'll do my best to get to them.

**Comment by brycefisher** [comment]
Yay!
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by tonglil** [comment]
Some of the required APIs asked for have been merged in the library if anyone wants to give this a shot.

Folder permissions: https://github.com/nytm/go-grafana-api/pull/36
Team: https://github.com/nytm/go-grafana-api/pull/37

There is also an open but stale PR with the implementation of some other APIs.
As @mlclmj said, smaller PRs are much easier to review if anyone wants to break out those changes and try implementing their corresponding Terraform resources.

**Comment by trotttrotttrott** [comment]
Hi, I'd like to work on this if no one has started yet. @tonglil feel free to assign to me if you'd like.

**Comment by jonathan-dorsey** [comment]
PR https://github.com/grafana/terraform-provider-grafana/pull/120 submitted to add Team/Team Member functionality to the provider.

**Comment by pascal-hofmann** [comment]
PR #150 submitted to add dashboard permission functionality to the provider.

**Comment by julienduchesne** [comment]
Teams and users (admin or not) are fully supported
