### ISSUE TITLE
Invalid CA

### ISSUE THREAD

**Issue by ivandal77** [grafana/terraform-provider-grafana#53]
Dear,
trying to apply I get the error below. 
But the certificate and CA is valid.
How to add this CA or skip the CA test??
Thanks

`Error: Error applying plan:

1 error(s) occurred:

* grafana_dashboard.metrics: 1 error(s) occurred:

* grafana_dashboard.metrics: Post https://xxxxxx/grafana/api/dashboards/db: x509: certificate signed by unknown authority

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.`

**Comment by dionitas** [comment]
hi @ivandal77, did you find any solution or workround ?

**Comment by iosdal** [comment]
No solution.

**Comment by ivandal77** [comment]
No solution until now.... somebody can help us?
thanks

**Comment by ivandal77** [comment]
Solved adding CA to /etc/ssl....

**Comment by abrekhov** [comment]
Could you add flag to provider to skip CA check? Have the same issue...

**Comment by ghost** [comment]
No, simple copy your CA in /etc/ssl/certs. No flag to skip this check.

**Comment by mlclmj** [comment]
The provider could support this if accompanied by a library change as well
