### ISSUE TITLE
Add Flux as Query language

### ISSUE THREAD

**Issue by rajeevsh990** [grafana/terraform-provider-grafana#533]
While creating the data source the default query language is applied which is - InfluxQL. I'm using InfluxCloud for which I still need to be dependent on Influxdb plugin which actually shows two options (InfluxQL and Flux) to be selected. But there's no supported attribute in the schema of this provider. Please check.

**Comment by adbias** [comment]
You can define that setting with the `version` parameter inside `json_data`.

**Comment by rajeevsh990** [comment]
Thank you for the response. I tested the the provider with `version` parameter and it worked. But, I'm having challenge while setting up the token for InfluxDB Cloud datasource. I've almost used all the attributes in block `secure_json_data` and `json_data` but no avail. Document seems bit fuzzy to me. 

Even, I can create the datasource with token using REST APIs as follows but couldn't get it worked with equivalent data in provider. 

```
        -d '{   "orgId":"'''$GRAFANA_ORG_ID'''",
                "name":"'''$DATASOURCE_NAME'''",
                "type":"influxdb",
                "url":"'''$INFLUX_URL'''",
                "basicAuth":false,
                "access":"proxy",
                "jsonData": {
                        "httpMode": "POST",
                        "organization": "'''$INFLUX_ORG_ID'''",
                        "version": "Flux"
                        },
                "secureJsonData": {
                        "token":"'''$INFLUX_AUTH_TOKEN'''"
                }
        }'
```

**Comment by adbias** [comment]
The only way I could make this work is adding a header through the `http_headers` parameter:
```
resource "grafana_data_source" "influxdb" {
  ...
  json_data {
  ...
  }
  http_headers = {
    Authorization = "Token <token>"
  }
}
```

**Comment by rajeevsh990** [comment]
@adbias Thank you for the reference. It's working fine with above settings.
