### ISSUE TITLE
[Feature Request] Support setting version for Elasticsearch datasource

### ISSUE THREAD

**Issue by mattrussell-sonocent** [grafana/terraform-provider-grafana#54]
It'd be great to be able to configure the version of Elasticsearch (and potentially other configurable properties of the data source):

![image](https://user-images.githubusercontent.com/45822724/54931268-933f9700-4f10-11e9-89f8-4b0567ee9edd.png)

### Affected Resource(s)
- grafana_data_source

**Comment by jmanuelortizn** [comment]
same here

**Comment by tonglil** [comment]
Done in https://github.com/terraform-providers/terraform-provider-grafana/pull/90
