### ISSUE TITLE
grafana_report error 500 when running terraform apply

### ISSUE THREAD

**Issue by kaiyuanlim-adh** [grafana/terraform-provider-grafana#549]
### Terraform Version
* Terraform: 1.1.4
* Terraform Grafana Provider: ...
* Grafana: 1.24.0

### Affected Resource(s)
* grafana_report

### Terraform Configuration Files
```hcl
resource "grafana_report" "resource_consumption_report" {
  name              = "Resource Consumption Report"
  dashboard_id      = data.grafana_dashboard.resource_consumption.dashboard_id
  recipients        = var.recipients
  include_table_csv = true
  message           = "Here is the resource consumption report for ${var.environment}"
  schedule {
    frequency = "daily"
  }
  time_range {
    from = "now-1d"
    to   = "now"
  }
}
```

### Expected Behavior
Terraform apply should work correctly

### Actual Behavior
* Terraform apply results in error 500
```
│ Error: status: 500, body: {"message":"body json marshal","traceID":"00000000000000000000000000000000"}
│ 
│   with grafana_report.resource_consumption_report,
│   on reports.tf line 1, in resource "grafana_report" "resource_consumption_report":
│    1: resource "grafana_report" "resource_consumption_report" 
```

### Steps to Reproduce
1. Setup grafana with persistence using postgres. 
2. Run `terraform apply`

**Comment by julienduchesne** [comment]
There was a bug in Grafana that caused this recently. Can you try this again with Grafana 9.1.1 or 9.0.7?

**Comment by kaiyuanlim-adh** [comment]
Thank you for the update. What version of the provider that I should use?

**Comment by kaiyuanlim-adh** [comment]
I tried it with Grafana version 9.0.7 with TF Grafana Provider version 1.27.0 and it is still the same error.

I would like to try it out with Grafana version 9.1.1 but that will be next week probably.

**Comment by kaiyuanlim-adh** [comment]
Okay, managed to test with 9.1.1 and it works!
