### ISSUE TITLE
Toggle to skip saving dashboard JSON to Terraform state 

### ISSUE THREAD

**Issue by eitah** [grafana/terraform-provider-grafana#553]
We request a toggle on `resource_dashboard` to bypass saving dashboard JSON to state. At $CURRENT_JOB we often skip providing specific metadata fields in our dashboard definitions to keep the Cue we use lightweight. Instead, we rely on Grafana's API to complete metadata for us. Unfortunately, a permanent diff is produced in our Terraform because the Dashboard JSON is [saved to Terraform state]. Terraform plans see that the JSON doesn't match and keeps trying to revert what Grafana's done.

We counteract that at $CURRENT_JOB with a private fork of the `terraform-provider-grafana` that still saves necessary metadata - dashboard id, folder, slug, and the like while relying on Grafana to be the source of truth over this single attribute `config_json`. The fork has run successfully for over a year. Now we want to backport our changes to the provider so that others can benefit.

I recognize you have other initiatives that affect the configuring of dashboards - the use of discrete Terraform arguments comes to mind (https://github.com/grafana/terraform-provider-grafana/issues/299). This toggle would be a stopgap for us as you work to make maintainable configuration simpler and cleaner.

As one of the maintainers of the fork at my company, I would be happy to PR something. Do let me know your thoughts. Thanks!

[saved to Terraform state]: https://github.com/grafana/terraform-provider-grafana/blob/master/grafana/resource_dashboard.go#L234-L252[](url)

**Comment by julienduchesne** [comment]
A feature was added for that purpose here: https://github.com/grafana/terraform-provider-grafana/pull/222

**Comment by julienduchesne** [comment]
If you mean that you want to ignore changes to the attribute, then Terraform's ignore_changes should do the trick: https://www.terraform.io/language/meta-arguments/lifecycle#ignore_changes

**Comment by justinTM** [comment]
@eitah I'd be very curious to see how you're using CUE to make the dashboards, as we have a quite complex solution using Terraform and JSON templates, if you're willing to share.

**Comment by eitah** [comment]
Hey @julienduchesne thanks for your comment! We moved to sha256sum as an alternative to the fork, so that will work for now and I am closing the enhancement request, thanks!

@justinTM happy to share what we can. It took a bit of work because `terraform-provider-cue` (https://github.com/xinau/terraform-provider-cue) is still an alpha. We ended up forking the provider. That said, if you could find a way to compile the cue into JSON every terraform run, the  cue is just some inputs (here title, projectIds and tags) and a bunch of extensible template and panel definitions that we maintain. It'll be interesting to see what happens to the cue as Grafana moves away from that roadmap for the product.

```
#title:      string @tag(title)
#projectIds: string @tag(project_ids)
#tags:       string @tag(tags)

grafana.Dashboard & {
	title: #title
	tags:  strings.Fields(#tags)

	templating: list: #templates

	panels: [
		for index, panel in #panels {id: index, panel.panel},
	]
}

#templates: [
	#templatePrometheus,
	#templateProjectID,
	#templateInstanceId,
]

#panels: [
	#rowOverall,
	#panelInstanceUptime,
	#panelConnectedBlockedClients,
	#panelMemoryUsageRatio,
	#panelMemoryUsageMaxMemory,
	#rowCalls,
	#panelCalls,
	#panelCacheHitRatio,
	#panelTotalTimeOfCalls,
	#rowKeys,
	#panelKeysInDatabase,
	#panelEvictedExpiredKeys,
]
```
