### ISSUE TITLE
Expose Graphite and Tempo metadata for grafana_cloud_stack resource

### ISSUE THREAD

**Issue by Shvadchak** [grafana/terraform-provider-grafana#566]
We are using the [grafana_cloud_stack](https://registry.terraform.io/providers/grafana/grafana/latest/docs/resources/cloud_stack) resource to automate Grafana Cloud Stack provisioning. In our organization, we need to provision multiple Grafana Cloud Stacks that should be queried within a single Grafana Cloud instance. So after creating a new Grafana Cloud stack, the stack's datasources should be provisioned into a centralized Grafana Cloud instance.

Currently, each Grafana Cloud Stack includes the following components:
* Prometheus
* Alertmanager
* Loki
* Tempo
* Graphite

But [grafana_cloud_stack](https://registry.terraform.io/providers/grafana/grafana/latest/docs/resources/cloud_stack) doesn't expose any metadata for Graphite and Tempo components. While other components' URLs and usernames are exposed like read-only outputs(for example [prometheus_remote_endpoint](https://registry.terraform.io/providers/grafana/grafana/latest/docs/resources/cloud_stack#prometheus_remote_endpoint) and [prometheus_user_id](https://registry.terraform.io/providers/grafana/grafana/latest/docs/resources/cloud_stack#prometheus_user_id).

It would be nice to expose Tempo and Graphite metadata as well, so the datasource provisioning can be fully automated.

**Comment by day4me** [comment]
+1
