### ISSUE TITLE
[Feature Request] Support Alerts as separate resource

### ISSUE THREAD

**Issue by sethbacon** [grafana/terraform-provider-grafana#57]
Support adding alerts with terraform as a separate resource through the alerts api.
/api/alerts/

**Comment by mlclmj** [comment]
Hey @sethbacon unless I'm missing something I don't think we'd be able to add this as a resource since the endpoint seems to only be able to read Alerts that are contained within dashboards, though I guess it would be feasible to add as a data source. Is that what you had in mind?

**Comment by sethbacon** [comment]
Yeah, I'm cool with that.

**Comment by sammit-kambi** [comment]
Hi there, Is there any timeline when the addition of Alerts feature will get introduced ? or may be a version for which it is scheduled to get released with.

**Comment by julienduchesne** [comment]
I will be working on adding support for Unified Alerting in the following weeks

**Comment by julienduchesne** [comment]
I've been informed that the Unified Alerting API will go through some refactoring (to be released in 8.5). Terraform support will be a main target of this refactor

**Comment by chad-barensfeld-exa** [comment]
Looking forward to this feature

**Comment by cjs226** [comment]
@julienduchesne being that [8.5 has been released](https://github.com/grafana/grafana/blob/main/CHANGELOG.md), do you have an idea of an ETA for this feature?

**Comment by julienduchesne** [comment]
Some alerting API features are waiting for Grafana 9 unfortunately. We can't really start now and re-do everything in a month

**Comment by chad-barensfeld-exa** [comment]
> Some alerting API features are waiting for Grafana 9 unfortunately. We can't really start now and re-do everything in a month

Thanks for the update. Do you have a rough ETA once 9 is released? Currently migrating to GC.

**Comment by armandgrillet** [comment]
Grafana 9 will be released mid-June 2022 and the new provisioning API will be included in it (see [this comment](https://github.com/grafana/grafana/issues/36153#issuecomment-1087597922) for a detailed task breakdown). An update of the Terraform provider will then be needed, it will be worked on as soon as the API is ready to be used.

**Comment by dalvizu** [comment]
It looks like this Grafana 9 was released on [June 14th](https://github.com/grafana/grafana/releases/tag/v9.0.0) and that [unified alert api is now the default](https://grafana.com/docs/grafana/latest/whatsnew/whats-new-in-v9-0/#unified-alerting-is-the-default-in-grafana-9)

Docs:

* https://grafana.com/docs/grafana/next/developers/http_api/alerting_provisioning/
* https://grafana.com/docs/grafana/next/developers/http_api/alerting_notification_channels/

I'm happy to test any implementation against Grafana cloud

**Comment by stevenbrichards** [comment]
@julienduchesne is there an implementation yet for this? would be happy to contribute myself if possible.

edit: made a quick PR to add AlertRule to the go-api https://github.com/grafana/grafana-api-golang-client/pull/91

**Comment by aavileli** [comment]
any update when this feature will be available. we want to provision alert rules using custom resource in k8s

**Comment by alexweav** [comment]
Happy to announce that this is now supported as of today: https://github.com/grafana/terraform-provider-grafana/releases/tag/v1.27.0

All unified alerting resources are now available in Terraform. (alert rules, contact points, notification policies, mute timings, message templates)
