### ISSUE TITLE
a new version release

### ISSUE THREAD

**Issue by 1mr** [grafana/terraform-provider-grafana#570]
Is there any chance to release a new version? 🤔 

There are a lot of [changes](https://github.com/grafana/terraform-provider-grafana/compare/011e2f470a5e7dc040f6567149f953eca2cab62f..master) compared to the latest available version 1.24.0 `48 changed files with 1093 additions and 209 deletions.` It would be cool just to use the latest one, w/o the need to build it locally.

Thanks in advance!

**Comment by julienduchesne** [comment]
Hey! I'll create one this week!

**Comment by julienduchesne** [comment]
👋 1.25.0 was released
