### ISSUE TITLE
Updating probe_ids to checks cause 409 cannot update database

### ISSUE THREAD

**Issue by anhdle14** [grafana/terraform-provider-grafana#580]
### Terraform Version
* Terraform: 1.26.0
* Terraform Grafana Provider: 1.24.0
* Grafana: 9.0+

### Affected Resource(s)
Please list the resources as a list, for example:
* `grafana_synthetic_monitoring_checks`

### Terraform Configuration Files
```hcl
probe_ids = [ ] # values updated here

resource "grafana_synthetic_monitoring_check" "this" {
  job               = "This"
  target            = "https://google.com"
  enabled           = true
  probes            = var.probe_ids
  alert_sensitivity = "high"
  labels            = var.labels

  settings {
    http {
      method              = "GET"
      fail_if_not_ssl     = true
      fail_if_ssl         = false
      ip_version          = "V4"
      no_follow_redirects = false
      valid_status_codes = [
        200,
      ]

      tls_config {}
    }
  }
}
```

### Debug Output
N/A

### Panic Output
N/A

### Expected Behavior
Probes updated successfully.

### Actual Behavior
```
│ Error: check update request: status="409 Conflict", msg="cannot update database", err="updating check: updating probes for check 338183: expecting a sorted slice of new probes"
│ 
│   with module.arene_ai_checks.grafana_synthetic_monitoring_check.this,
│   on checks/arene_ai/checks.tf line 1, in resource "grafana_synthetic_monitoring_check" "this":
│    1: resource "grafana_synthetic_monitoring_check" "this" {
│ 
╵
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
N/A

### References
N/A

**Comment by totomz** [comment]
This error also happens when creating new resources

```
│ Error: check add request: status="409 Conflict", msg="Failed to add check to database", err="inserting probes for check 18843: expecting a sorted slice of new probes"
│
│   with grafana_synthetic_monitoring_check.http3,
│   on alarms.tf line 19, in resource "grafana_synthetic_monitoring_check" "http3":
│   19: resource "grafana_synthetic_monitoring_check" "http3" {
│
```

Both create and update work if I declare only 1 probe. I can create this sm check, and I can change the probes if I keep their number to 1
```
resource "grafana_synthetic_monitoring_check" "http" {
  provider = grafana.sm
  job     = "HTTP Defaults"
  target  = "https://grafana.com"
  enabled = true
  probes  = [
    4 # <-- can update this but can't add more than 1 probe
  ]
 
  settings {
    http {

    }
  }
}
```

**Comment by alexweav** [comment]
There are also tests in this codebase that are broken in a similar way. Most PR builds seem to be failing with the same error. https://drone.grafana.net/grafana/terraform-provider-grafana/1456/5/3

**Comment by alexweav** [comment]
Hi, this seemed to be a compatibility issue in the synthetic monitoring API itself, not just the provider. I reached out and it appears this is fixed and deployed now, so this issue should no longer happen.

Sure enough, this error no longer happens when running tests, so the build is now passing too. Please let us know if you run into this again, but it should be fixed!
