### ISSUE TITLE
Support for defining alarms

### ISSUE THREAD

**Issue by xocasdashdash** [grafana/terraform-provider-grafana#616]
Hi there!

Seems like the [client](https://github.com/grafana/grafana-api-golang-client/blob/master/alerting_alert_rule.go) supports defining alerts and such. 

Is there any plan/roadmap on adding support for this resource here?

**Comment by julienduchesne** [comment]
I believe that would be a rule group: https://registry.terraform.io/providers/grafana/grafana/latest/docs/resources/rule_group
Right @alexweav?

**Comment by alexweav** [comment]
Exactly @julienduchesne! Rules must be provisioned through groups.

**Comment by julienduchesne** [comment]
Closing this, feel free to reopen if you try alert rule groups and they do not work as expected!

**Comment by xocasdashdash** [comment]
thank you :) I looked for: alert, alarm in the provider and nothing popped up, and from disussions with other people more people have that idea
