### ISSUE TITLE
grafana_oncall_integration notification to slack is disabled when provisioned

### ISSUE THREAD

**Issue by alekhrycaiko** [grafana/terraform-provider-grafana#618]
### Terraform Version
* Terraform: 1.1.6
* Terraform Grafana Provider: 1.27
* Grafana: Cloud

### Affected Resource(s)
- grafana_oncall_integration
- grafana_oncall_route

### Expected Behavior
When building a new `grafana_oncall_integration` with a default block set to a Slack channel, the `post to channel` option should be enabled, as I've specified I want my integrations default route posting to Slack.

When building a new grafana on call route, and specifying a Slack channel, I expect the 'post to channel' option to be enabled. 

### Actual Behavior
New integration or route built with a default route to Slack, has `post to channel` disabled. A user needs to go in and manually enable messages to be sent to Slack in the integration to override this.

**Comment by julienduchesne** [comment]
Implemented in https://github.com/grafana/terraform-provider-grafana/pull/621
