### ISSUE TITLE
[feature request] Support "sendReminder" and "frequency" options in the alert notification resource

### ISSUE THREAD

**Issue by ko-da-k** [grafana/terraform-provider-grafana#62]
Hi there,

This is a request to support `sendReminder` and `Frequency` options in the alert notification resource.
I hope all options are supported in this resource.

![スクリーンショット 2019-05-29 12 14 47](https://user-images.githubusercontent.com/17734711/58527421-80e22200-820d-11e9-93fa-3d21b29697bb.png)

### Affected Resource(s)
- grafana_alert_notification

### References
- [grafana/pkg/models/alert_notifications.go](https://github.com/grafana/grafana/blob/54c1bf0cc985ccca38cdb16a31d1c763833ff4c8/pkg/models/alert_notifications.go#L41-L53)

**Comment by quinont** [comment]
hi,
I created a PR for the library that this provider uses, adding these options
https://github.com/nytm/go-grafana-api/pull/24

**Comment by quinont** [comment]
maybe this is a solution https://github.com/terraform-providers/terraform-provider-grafana/pull/72
