### ISSUE TITLE
Contact Point Resource Not Working

### ISSUE THREAD

**Issue by jdomantay** [grafana/terraform-provider-grafana#623]
### Terraform Version
* Terraform:  v1.2.8
* Terraform Grafana Provider:  v1.27.0
* Grafana: Grafana v8.3.5 (a53fcac7b1)

### Affected Resource(s)
Please list the resources as a list, for example:
* grafana_contact_point

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
variable "name"{
    description = "Contact Point Name"
    default = "test"
}

variable "integration_key"{
    description = "PagerDuty Integration Key "
    type = string
    default = "REMOVED"
}

variable "auth"{
    default = "REMOVED"
}

provider "grafana"{
    url = "https://sf-devops.grafana.cpln.io"
    auth = var.auth
}

terraform {
    required_providers {
        grafana = {
            source = "grafana/grafana"
            version = "1.27.0"
        }
    }
}

resource "grafana_contact_point" "contact_point"{
    name = var.name
/*     pagerduty {
        integration_key = var.integration_key
     } */

     email {
        addresses = ["john@safehealth.me"]
        message = "test"
        subject = "test"
        single_email = true
        disable_resolve_message = false
     }
}
```

### Debug Output
https://gist.github.com/jdomantay/fdfc91174210155e2d545b905659b55e

### Panic Output
N/A

### Expected Behavior
Contact Point Should be Created

### Actual Behavior
Receiving 400 error on both pagerduty and email contact points 

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
None

### References
None

**Comment by julienduchesne** [comment]
You need Grafana 9.1+ for alerting features
