### ISSUE TITLE
Configuring Azure data sources

### ISSUE THREAD

**Issue by GarraPeters** [grafana/terraform-provider-grafana#636]
When using the the "grafana-azure-data-explorer-datasource" data source type in a "grafana_data_source" resource. THere doesn't appear to be anyway to set values for "Cluster URL" and "Default Database". Has this not been implemented or is it just not documented?

### Affected Resource(s)
Please list the resources as a list, for example:
* grafana_data_source 

### Expected Behavior
The "Cluster URL" and "Default Database" are configurable when using the "grafana-azure-data-explorer-datasource" type

### Actual Behavior
The datasource resource gets created without errors but there doesn't appear to be a way to configure the "Cluster URL" and "Default Database" parameters

**Comment by julienduchesne** [comment]
It's all supported through the `json_data_encoded` field: https://registry.terraform.io/providers/grafana/grafana/latest/docs/resources/data_source#json_data_encoded

The best way to know what to put in those fields is to configure a datasource manually and then inspect the payload from your browser's network tab. Example:
![image](https://user-images.githubusercontent.com/29210090/188641215-5b10d57d-b21a-4d31-8562-2ed46beebdc6.png)

I don't have an Azure account so I don't know what the default database field is but for the Cluster URL, it's `clusterUrl`. Let me know if that helps!

**Comment by GarraPeters** [comment]
this doesn't appear to work. it throws an  "Unsupported argument" error, as says that "json_data_encoded" isn't a valid argument
`An argument named "json_data_encoded" is not expected here.`
