### ISSUE TITLE
Adding new notification policy removes existing policies

### ISSUE THREAD

**Issue by sammit20** [grafana/terraform-provider-grafana#642]
### Terraform Version
* Terraform: 1.2.8
* Terraform Grafana Provider: 1.28.0
* Grafana: 9.1.3-5

### Affected Resource(s)
Please list the resources as a list, for example:
* grafana_notification_policy

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
Should have added a new notification policy on top of the existing ones.

### Actual Behavior
Removed all the policies set before manually and created the one added via terraform

**Comment by NickLarsenNZ** [comment]
This is really strange behaviour. There's no warning, no safety :/
