### ISSUE TITLE
Renaming Contact Point Corrupts Alert Manager

### ISSUE THREAD

**Issue by NickAdolf** [grafana/terraform-provider-grafana#648]
TF: v1.2.3
Grafana Provider Version: v1.27.0

### Affected Resource(s)
* grafana_contact_point
* grafana_notification_policy

### Terraform Configuration Files
I have a rather complex setup of dynamically built contact points being referenced in nested notification policies coming from a set of configs mashing together numerous `matches`. This generates a valid notification policy, which works, but when needing to change the name of an existing contact point the `apply` fails and it ends up corrupting the alert manager instance due to the notification policy trying to reference a contact point that no longer exists. The TF plan includes updating the notification policy with the new name, but the instance is corrupted before this is applied.

```
Error: status: 500, body: {"message":"failed to deserialize alertmanager configuration: unexpected receiver ("Old Contact Point Name") is undefined","traceID":"4163ba82e4aebf55"}
```
I see updates were made in v1.28. and v1.28.1 around contact points but I don't believe this particular issue was addressed. 

### Expected Behavior
Update contact point and notification policy, or, at worst, fail gracefully.

### Actual Behavior
The alert manager instance is corrupted. (Requiring a support ticket to revert if in Grafana Cloud)

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by chrisdetsicas** [comment]
I ran into the same issue last week. I am told that this PR https://github.com/grafana/grafana/pull/54896 should fix the issue once it rolls out to Grafana Cloud.

**Comment by chrisdetsicas** [comment]
I ran into the same issue last week. Hoping that https://github.com/grafana/grafana/pull/54896 fixes it.

**Comment by alexweav** [comment]
Hi, now that 9.1.5 is out and the above PR is released, could you please retry against that version? This was a bug in the Grafana API's PUT endpoint, rather than the provider.
