### ISSUE TITLE
Alert rules gets created in tfstate but dosen't show up in GUI> Alert rules

### ISSUE THREAD

**Issue by sammit20** [grafana/terraform-provider-grafana#654]
### Terraform Version
* Terraform: 1.2.8
* Terraform Grafana Provider: 1.28.1
* Grafana: Grafana Cloud 9.1.3

### Affected Resource(s)
Please list the resources as a list, for example:
* grafana_rule_group

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
resource "grafana_rule_group" "testing_alert" {
    name = "testing alert"
    folder_uid = "test-new"
    interval_seconds = 240
    org_id = 1
    rule {
        name = "test_rule"
        for = "2m"
        condition = "B"
        no_data_state = "NoData"
        exec_err_state = "Alerting"
        annotations = {
            "summary" = "testing"
            "runbook" = "testing"
        }
        labels = {
            "team" = "newteam"
            "severity" = "medium"
        }
        data {
            ref_id = "A"
            query_type = "count(kube_pod_container_status_running{namespace=\"prometheus\",kubernetes_cluster=~\".+\"})"
            relative_time_range {
                from = 600
                to = 0
            }
            datasource_uid = "grafanacloud-prometheus"
            model = jsonencode({
                hide = false
                intervalMs = 1000
                maxDataPoints = 43200
                refId = "A"
            })
        }
        data {
            ref_id = "expressions"
            query_type = ""
            relative_time_range {
                from = 600
                to = 0
            }
            datasource_uid = "-100"
            model = <<EOT
{
    "conditions": [
        {
        "evaluator": {
            "params": [
            3
            ],
            "type": "gt"
        },
        "operator": {
            "type": "and"
        },
        "query": {
            "params": [
            "A"
            ]
        },
        "reducer": {
            "params": [],
            "type": "min"
        },
        "type": "query"
        }
    ],
    "datasource": {
        "type": "__expr__",
        "uid": "-100"
    },
    "hide": false,
    "intervalMs": 1000,
    "maxDataPoints": 43200,
    "refId": "B",
    "type": "classic_conditions"
}
EOT
        }
    }
}

### Debug Output
It does show that the resource is created when checked in tfstate but the alert is not displayed in GUI > Alert rules

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
The alerts should be shown in GUI

### Actual Behavior
The alerts don't show up in GUI

### Steps to Reproduce
1. Add folder via tf template
2. Add the alert rule via tf template
3. Check in grafana UI

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-1234

**Comment by alexweav** [comment]
Hi there! :wave: Thanks for reporting this.

It looks like `folder_uid` needs to point to the UID of an existing folder rather than the name. Try creating a folder:
```
resource "grafana_folder" "my_folder" {
    title = "My Rule Folder for Testing"
}
```

Then, pass that folder's auto-populated UID to your `folder_uid` in the rule group:
```
folder_uid = grafana_folder.my_folder.uid
```

After making this change, the rule appeared in the UI, under the folder:

![2022-09-14-162534_799x169_scrot](https://user-images.githubusercontent.com/8410871/190265490-d0eb8eeb-3453-47a7-a1ed-de8671f4bd6d.png)

We allow alert rules to exist outside of folders today, but it looks like they don't properly show up in the UI at all. The rule did exist and was being evaluated correctly, it just did not show up. I've asked our frontend team if this is intended, if not we'll file an issue on the grafana/grafana repository.

Please let me know if this works!

**Comment by alexweav** [comment]
Moved this issue to grafana/grafana: https://github.com/grafana/grafana/issues/55202

**Comment by sammit20** [comment]
Thanks Alex
