### ISSUE TITLE
Importing alert rules doesn't work

### ISSUE THREAD

**Issue by sammit20** [grafana/terraform-provider-grafana#655]
### Terraform Version
* Terraform: 1.2.8
* Terraform Grafana Provider: 1.28.1
* Grafana: Grafana Cloud 9.1.3

### Affected Resource(s)
Please list the resources as a list, for example:
* grafana_rule_group

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
terraform import -var-file=test.tfvars grafana_rule_group.test-new "folderUID;ruleGroup"
```

### Debug Output
Error: Get "https://xxxxxxxxxx.net/api/v1/provisioning/folder/{{folderUID}}/rule-groups/{{ruleGroup}}": x509: certificate signed by unknown authority

### Expected Behavior
Alert should have got imported successfully.

### Actual Behavior
What actually happened?

Error: Get "https://xxxxxxxxxx.net/api/v1/provisioning/folder/{{folderUID}}/rule-groups/{{ruleGroup}}": x509: certificate signed by unknown authority

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. terraform import -var-file=test.tfvars grafana_rule_group.test-new "folderUID;ruleGroup"

**Comment by mentos1386** [comment]
I believe this was caused by the Grafana Cloud incident https://status.grafana.com/incidents/y887lr6hqs0d

**Comment by sammit20** [comment]
Right, the issue was due to the incident. Closing this bug
