### ISSUE TITLE
Error Creating grafana_rule_group resource

### ISSUE THREAD

**Issue by houserx-jinoa** [grafana/terraform-provider-grafana#659]
### Terraform Version
* Terraform: v1.2.6
* Terraform Grafana Provider: 1.28.2
* Grafana: 9.0.3

### Affected Resource(s)
Please list the resources as a list, for example:
* grafana_rule_group

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
################################################################################
# The folder of where the Elastic Beanstalk Alerts are organized in
# and the alert rule groups to alert against platform elastic beanstalk metrics
################################################################################
resource "grafana_folder" "elastic_beanstalk" {
  title = "Elastic Beanstalk Alerts"
}

resource "grafana_rule_group" "testing_alert" {
  name             = "staging_platformapi_environmentdegradeds"
  folder_uid       = grafana_folder.elastic_beanstalk.uid
  interval_seconds = 240
  org_id           = 1
  rule {
    name      = "Staging Environment Health"
    condition = "api-staging-envhealth"
    data {
      ref_id = "api-staging-upper"
      relative_time_range {
        from = 420
        to   = 0
      }
      datasource_uid = "P8B6ABB9F670BFAF3"
      model          = <<EOT
{
          "dimensions": {
            "EnvironmentName": "api-staging"
          },
          "expression": "",
          "hide": false,
          "id": "",
          "intervalMs": 1000,
          "label": "",
          "matchExact": true,
          "maxDataPoints": 43200,
          "metricEditorMode": 0,
          "metricName": "EnvironmentHealth",
          "metricQueryType": 0,
          "namespace": "AWS/ElasticBeanstalk",
          "period": "",
          "queryMode": "Metrics",
          "refId": "api-staging-upper",
          "region": "default",
          "sql": {
            "from": {
              "property": {
                "name": "AWS/ElasticBeanstalk",
                "type": "string"
              },
              "type": "property"
            },
            "select": {
              "name": "MAX",
              "parameters": [
                {
                  "name": "EnvironmentHealth",
                  "type": "functionParameter"
                }
              ],
              "type": "function"
            },
            "where": {
              "expressions": [
                {
                  "operator": {
                    "name": "=",
                    "value": "api-staging"
                  },
                  "property": {
                    "name": "EnvironmentName",
                    "type": "string"
                  },
                  "type": "operator"
                }
              ],
              "type": "and"
            }
          },
          "sqlExpression": "SELECT MAX(EnvironmentHealth) FROM \"AWS/ElasticBeanstalk\" WHERE EnvironmentName = 'api-staging'",
          "statistic": "Maximum"
        }
EOT
    }
  }
}

```

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
A new alert to be created.

### Actual Behavior
Error from TF
`│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to grafana_rule_group.testing_alert, provider
│ "provider[\"registry.terraform.io/grafana/grafana\"]" produced an unexpected new value: Root resource was
│ present, but now absent.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.`

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by alexweav** [comment]
Hi :wave:

I applied the .tf logic above verbatim and I did not see an error against the latest version of Grafana. They applied successfully. I believe if you upgrade the version of Grafana to the latest, you should no longer see this error.

The new alerting features only claim support for grafana 9.1 or later. Some of the endpoints that the provider relies on were added in Grafana 9.1, and do not exist in 9.0.

I'll add this note to each of the individual resource doc pages.

**Comment by alexweav** [comment]
I created a PR to make sure that this is noted in the docs clearly: https://github.com/grafana/terraform-provider-grafana/pull/662

It's noted in our main provisioning docs for Grafana, but those are still a few days out from being published unfortunately.

Along with the validation that @julienduchesne suggested above, I believe that should prevent versioning issues going forward.

**Comment by houserx-jinoa** [comment]
Thank you!
