### ISSUE TITLE
[feature request] allow to insecure ssl connections

### ISSUE THREAD

**Issue by xelite** [grafana/terraform-provider-grafana#67]
Hi there,

### Terraform Version
0.12

### Affected Resource(s)
provider grafana

### Expected Behavior
Connect to grafana api

### Actual Behavior
Error x509: certificate signed by unknown authority

**Comment by mlclmj** [comment]
This is something we could support in the provider, though would require an upstream library change to support this as well.

**Comment by joernkleinbub** [comment]
Hi,
for me, the issue is a blocker for using this provider. Is the solution to rovide an own transport instead of the RoundTrip the upstream library is providing?

**Comment by mlclmj** [comment]
Yes, I believe it would be necessary to modify the transport used by the upstream library in this case.

**Comment by Srokap** [comment]
Had similar problem, it was missing intermediate certificate in my case. After including intermediate cert in webserver configuration the problem disappeared.

**Comment by julienduchesne** [comment]
Support for this was added here: https://github.com/grafana/terraform-provider-grafana/commit/369494e470b48671014cf165efb8b7c8e11d6226

Through the `insecure_skip_verify` provider config
