### ISSUE TITLE
Expired aws_grafana_workspace_api_key doesn't renew

### ISSUE THREAD

**Issue by algojack** [grafana/terraform-provider-grafana#678]
### Terraform Version
* Terraform: v1.3.0
* Terraform Grafana Provider: v1.29.0
* Grafana: v8.4.7

### Affected Resource(s)
Please list the resources as a list, for example:
* aws_grafana_workspace_api_key
* grafana provider

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.
- I don't think this is core

### Terraform Configuration Files
```hcl
provider "aws" {
  region = "us-west-1"
}

provider "grafana" {
  alias = "my_grafana"
  url   = "https://${aws_grafana_workspace.my_aws_grafana.endpoint}"
  auth  = aws_grafana_workspace_api_key.my_aws_grafana_key.key
}

resource "aws_grafana_workspace" "my_aws_grafana" {
  // timestamp needed to work around duplicate workspace bug in aws managed grafana
  // https://stackoverflow.com/a/73411011/20103507
  description              = "My grafana ${formatdate("YYYYMMDDhhmmss", timestamp())}"
  account_access_type      = "CURRENT_ACCOUNT"
  authentication_providers = ["SAML"]
  permission_type          = "SERVICE_MANAGED"
  role_arn                 = "<replaced role arn here>"
  data_sources             = ["PROMETHEUS"]
}

resource "aws_grafana_workspace_api_key" "my_aws_grafana_key" {
  key_name        = "config-key"
  key_role        = "ADMIN"
  seconds_to_live = 3600
  workspace_id    = aws_grafana_workspace.my_aws_grafana.id
}

resource "grafana_data_source" "prometheus" {
...
}
```

### Expected Behavior
New key is created and terraform shows plan

### Actual Behavior
```
│ Error: Invalid provider configuration
│ 
│ Provider "registry.terraform.io/grafana/grafana" requires explicit configuration. Add a provider block to the root module and configure the provider's required arguments as described in the provider
│ documentation.
│ 
╵
╷
│ Error: Missing required argument
│ 
│   with provider["registry.terraform.io/grafana/grafana"],
│   on <empty> line 0:
│   (source code not available)
│ 
│ "auth": one of `auth,cloud_api_key,oncall_access_token,sm_access_token` must be specified
```
Or if i have the grafana_data_source block also:
```
│ Error: the Grafana client is required for `grafana_data_source`. Set the auth and url provider attributes
│ 
│   with grafana_data_source.prometheus,
│   on main.tf line 50, in resource "grafana_data_source" "prometheus":
│   50: resource "grafana_data_source" "prometheus" {
│ 
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`

### Important Factoids
Are there anything atypical about your accounts that we should know?
I'm using terraform to create aws_managed_grafana, and then creating an api key there that has to have an expiration date. Once it expires, the grafana provider that i'm trying to use to configure this aws_managed_grafana instance, stops working. The whole plan stops working.

**Comment by algojack** [comment]
Apologies if this is posted in the wrong place, please let me know where to post if so.

The only work around I found is to remove the old expired key, rename, and create new one:
1. `terraform state rm 'aws_grafana_workspace_api_key.my_aws_grafana_key'`
2. change name of the key
3. `terraform plan -out=tfplan -target=aws_grafana_workspace_api_key.my_aws_grafana_key
4. `terraform apply "tfplan"`

**Comment by algojack** [comment]
The whole problem can be summarized in:
When aws_grafana_workspace_api_key expires (required field seconds_to_live) it stops grafana provider from working completely.

**Comment by algojack** [comment]
created an issue on hashicorp, since i'm not sure if this would fall under their or your purview. https://github.com/hashicorp/terraform-provider-aws/issues/27123

**Comment by julienduchesne** [comment]
Yeah, that would be an issue for the aws provider, indeed. Going to close this one
