### ISSUE TITLE
Cannot create (alert-manager) grafana_contact_point - error 500 : "no secrets configured for type 'prometheus-alertmanager'"

### ISSUE THREAD

**Issue by subkryl** [grafana/terraform-provider-grafana#679]
### Terraform Version
* Terraform: v1.3.1
* Terraform Grafana Provider: 1.29.0
* Grafana: v9.0.2

### Affected Resource(s)
Please list the resources as a list, for example:
* grafana_contact_point

### Terraform Configuration Files
```hcl

resource "grafana_contact_point" "receiver_types" {
  name = "test0"

  alertmanager {
    url = "http://prometheus-alertmanager.monitoring.svc.cluster.local"
    basic_auth_user = ""
    basic_auth_password = ""
  }
}

# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

Actually using grafana helm chart :

resource "helm_release" "grafana" {
  name       = "grafana"
  repository = "https://grafana.github.io/helm-charts"
  chart      = "grafana"
  version    = "6.32.2"
  namespace  = "monitoring"
 ...
}

GIST URL : https://gist.github.com/subkryl/0b591c0493b4573dd97cccde2a8968ca

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
What should have happened?

Install contact point through grafana API

### Actual Behavior
What actually happened?

Error 500, asking for password but there is no password enabled.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

Others contact points methods should work.

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- https://github.com/grafana/terraform-provider-grafana/issues/630

**Comment by alexweav** [comment]
This is a case of this bug, on the Grafana side: https://github.com/grafana/grafana/issues/55139

Basically, there is a bug inside Grafana with how it treats the notifier config, and explicit empty strings cause strange problems. It cannot distinguish between empty string and missing altogether in certain cases.

You can see there are many PRs attached to this issue: it's something we are actively working on, but it requires us to touch each notifier one-by-one. Some of the notifiers have been fixed, `alertmanager` notifier has not yet received this fix.

**Comment by alexweav** [comment]
I'll close this now, as it's not an issue in the provider itself and does not require a code change here. It's still tracked as part of the issue above in the main Grafana repo. Please let me know if you have any other issues, or feel this should be re-opened. Thank you for reporting this!
