### ISSUE TITLE
Add Example Usage for grafana_role_assignment

### ISSUE THREAD

**Issue by SeamusGrafana** [grafana/terraform-provider-grafana#682]
Hello,

Please could we add an Example Usage for `grafana_role_assignment` to the [Docs page](https://registry.terraform.io/providers/grafana/grafana/latest/docs/resources/role_assignment#example-usage) and also to the [Examples folder](https://github.com/grafana/terraform-provider-grafana/tree/master/examples/resources) to help better understand how to use this resource.

It looks like in one of the test files, there is an example fo this ([here](https://github.com/grafana/terraform-provider-grafana/blob/f487ec3ab555effea25bc6de92cedffb0509e72b/grafana/resource_role_assignment_test.go#L101-L105)) that this could be based on.

Thanks

**Comment by julienduchesne** [comment]
Addressed by https://github.com/grafana/terraform-provider-grafana/pull/701. Docs will be updated on next release!
