### ISSUE TITLE
Better dynamic environments/stacks support. TF as first-class citizen.

### ISSUE THREAD

**Issue by ekostjuk** [grafana/terraform-provider-grafana#689]
Feature request for bettter end-to-end stack provisioning lifecycle support. 

Would like to be able to provision stack/s from ground zero, enable and configure all aspects of it, including extra grafana features and 3rd party plugins, in a reliable and idempotent manner with a single apply pass, then be able to tear it down.

Use case: multi-tenancy within a single account or  multiple environments (like having staging vs prod grafana).

This is likely epic level, since its not a single individual issue to fix:
- Internal/external plugin support and config. ("enabling" features)
- API parallelism/stability. State reset/"flicker" on throttling.
- Multiple authentication levels on single provider declaration and lacking docs.
- Loose provisioning order resulting in having to re-run apply.
- Lack of termination protection override flags on folders.
- Bleeding of some ops internals into automation code. (Like US vs EU links for Synthetic Monitoring)

**Comment by julienduchesne** [comment]
Please re-open specific issues for these. ~Half of the items in this list have been fixed since you opened this issue
