### ISSUE TITLE
Adding Token as a parameter for Flux query language version for influxdb

### ISSUE THREAD

**Issue by arielpardomartin** [grafana/terraform-provider-grafana#691]
Actually, the only way to integrate with influxdb is with username and password using influxQL query language. To allow Flux version for query language is necessary add Token as a parameter.

**Comment by arielpardomartin** [comment]
[PR to add token as a parameter for Flux version](https://github.com/grafana/terraform-provider-grafana/pull/690)

**Comment by julienduchesne** [comment]
You can specify your datasource this way:

```terraform
resource "grafana_data_source" "influxdb" {
  type = "influxdb"
  name = "my-ds"
  url  = "http://influxdb.example.net:8086/"
  json_data_encoded = jsonencode({
    defaultBucket     = "my-bucket"
    httpMode          = "POST"
    organization      = "my-org"
    timeout           = 5
    tlsAuth           = false
    tlsAuthWithCACert = false
    version           = "Flux"
  })
  secure_json_data_encoded = jsonencode({
    token = "test-token"
  })
}
```

The way to figure out the fields is by checking out the influxDB plugin docs: https://grafana.com/docs/grafana/latest/datasources/influxdb/ or more easily by saving a datasource in Grafana and inspecting it 
![image](https://user-images.githubusercontent.com/29210090/201245109-33fc3802-5302-42f2-a76f-56ea55187c08.png)
