### ISSUE TITLE
Service Account permissions.

### ISSUE THREAD

**Issue by marioanton** [grafana/terraform-provider-grafana#699]
- Managing service account permissions.

**Comment by geoffmore** [comment]
Can you clarify what you're looking for here? I see permissions for [Grafana OSS](https://registry.terraform.io/providers/grafana/grafana/latest/docs/resources/service_account) and [Grafana Enterprise](https://registry.terraform.io/providers/grafana/grafana/latest/docs/resources/role) in the Terraform provider.

**Comment by marioanton** [comment]
I can't assing a team permissions to a service account and would like to do it so.
https://registry.terraform.io/providers/grafana/grafana/latest/docs/resources/data_source_permission.
THis is a similar permissions i can use for datasources but not in this case.

**Comment by julienduchesne** [comment]
This was added in v1.31.0: https://github.com/grafana/terraform-provider-grafana/pull/708
