### ISSUE TITLE
Create Grafana Role return 403 or Get Fixed Role via data "grafana_role"

### ISSUE THREAD

**Issue by DingGGu** [grafana/terraform-provider-grafana#700]
I try to grant datasource explorer permission to team.
In my case, DataSource permission already granted with TeamSync `grafana_team_external_group` and `data_source_permission`.
> There are problem that data_source_permission cannot handle default permission via terraoform, I hope this issue was resolve in https://github.com/grafana/terraform-provider-grafana/pull/692.

I have a two options:
1. Get Fixed DataSource Explorer uid and assignment.
It needs `data "grafana_role"` for get uid of [FixedRole](https://grafana.com/docs/grafana/latest/administration/roles-and-permissions/access-control/#fixed-roles)
Using with this [API](https://grafana.com/docs/grafana/latest/developers/http_api/access_control/#get-a-role) will matched our purpose.

2. Create new grafana_role for fixed:datasources:explorer
I attached message, it returns 403.
I create sa for admin, but I don't have any ideas for 403

```
resource "grafana_role" "explorer" {
  name        = "Explorer"
  description = "Only Allow Explorer for Team Sync"
  uid         = "explorer"
  version     = 1
  global      = true


  permissions {
    action = "fixed:datasources:explorer"
  }
}
```

```
╷
│ Error: status: 403, body: {"message":"Forbidden","traceID":""}
│
│   with module.grafana.grafana_role.explorer,
│   on ../src/teams.tf line 30, in resource "grafana_role" "explorer":
│   30: resource "grafana_role" "explorer" {
│
╵
```

**Comment by NickAdolf** [comment]
I'd like to do this from cloud, so I believe I'd need option 1? Or custom roles in cloud 👍

**Comment by mhassan-pplus** [comment]
Were you able to resolve this issue or find a good workaround? 
I'm running into this same exact problem

**Comment by julienduchesne** [comment]
A datasource was added for this!
