### ISSUE TITLE
Support adding users to Grafana Cloud

### ISSUE THREAD

**Issue by JackLuo0826** [grafana/terraform-provider-grafana#709]
When adding users with grafana_user and basic auth, after terraform plan, it always display error message saying username or password is not correct. Tried on several different Grafana instances/stacks and admin accounts, none of them worked.

### Terraform Version
* Terraform: 1.3.2
* Terraform Grafana Provider: 1.30.0
* Grafana: v9.2.2-eb6f0ffe76 (eb6f0ffe76)

### Affected Resource(s)
Please list the resources as a list, for example:
* grafana_user

### Terraform Configuration Files
{
  "grafana-access": [
    {
      "team": "PP",
      "users": [
        "jack.luo@gmail.com",
        "jack.luo@qq.com"
      ]
    }
  ]
}

### Expected Behavior
New users should be added to Grafana Cloud.

### Actual Behavior
Displayed error saying incorrect username or password using basic auth.

### Steps to Reproduce
1. Use grafana_user with basic auth
2. terraform apply

**Comment by julienduchesne** [comment]
You can’t add users to Cloud with the provider yet

**Comment by JackLuo0826** [comment]
Hi Julien,

Thanks for the timely reply.

Is there any plan to add this feature? If so, where can we track the
progress? We are very keen to add it to our module when it is available.
Thank you very much!

Kind Regards,
Jack

**Comment by julienduchesne** [comment]
There is no issue for this yet. I think it's a good feature request. I'd have to check if the users API is publicly accessible

**Comment by JackLuo0826** [comment]
Thank you, Julien.

This feature will save us a lot of time manually adding/inviting new users.
Please double-check regarding the API and let us know of any updates. :)

Kind Regards,
Jack

**Comment by julienduchesne** [comment]
Blocked. Waiting on official API support: https://grafana.com/docs/grafana-cloud/api-reference/cloud-api/
