### ISSUE TITLE
`access_key` and `secret_key` not being configured for cloudwatch data source

### ISSUE THREAD

**Issue by aliabbasjaffri** [grafana/terraform-provider-grafana#715]
### Terraform Version
* Terraform: 1.3.0
* Terraform Grafana Provider: 1.30.0
* Grafana: v9.2.3-997144b7

### Affected Resource(s)
Please list the resources as a list, for example:
* grafana_data_source

### Terraform Configuration Files
```hcl
grafana_data_sources = {
  "cloudwatch" = {
    type = "cloudwatch"
    name = "cloudwatch_datasource"
    json_data_encoded = {
      default_region = "us-west-2"
      auth_type = "keys"
    }
    secure_json_data = {
      access_key = REDACTED
      secret_key = REDACTED
    }
  }
}
```

### Expected Behavior
Cloudwatch data source should have been configured in Grafana with credentials

### Actual Behavior
Cloudwatch data source is not being configured in Grafana with credentials

<img width="1498" alt="Screenshot 2022-11-10 at 09 18 23" src="https://user-images.githubusercontent.com/4748985/201037802-b5d23381-7f3f-49f2-bbd4-55ecdb5fc149.png">

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by julienduchesne** [comment]
Same thing as https://github.com/grafana/terraform-provider-grafana/issues/714#issuecomment-1311037274. The attributes should be `accessKey` and `secretKey`

**Comment by aliabbasjaffri** [comment]
Just verified! this works too! Thanks @julienduchesne
