### ISSUE TITLE
Unable to apply grafana_oncall_on_call_shift

### ISSUE THREAD

**Issue by mentos1386** [grafana/terraform-provider-grafana#733]
### Terraform Version
* Terraform: 1.3.5
* Terraform Grafana Provider: v1.31.1
* Grafana: Grafana Cloud

### Affected Resource(s)
* grafana_oncall_on_call_shift

### Terraform Configuration Files
Inspiered by the example https://registry.terraform.io/providers/grafana/grafana/latest/docs/resources/oncall_on_call_shift.
```hcl
resource "grafana_oncall_on_call_shift" "workday-slo" {
  team_id    = data.grafana_oncall_team.backend.id
  name       = "SLO Workday Shift"
  type       = "rolling_users"
  start      = "2022-11-21T09:00:00"
  duration   = 60 * 60 * 8 // 8H
  frequency  = "daily"
  by_day     = ["MO", "TU", "WE", "TH", "FR"]
  week_start = "MO"
  time_zone  = "Europe/Ljubljana"

  rolling_users = [for k in flatten([
    local.teams_map_of_user_id.backend,
  ]) : [k]]
}
```

### Debug Output
https://gist.github.com/mentos1386/ee9f23757d16f9fbb612f49fee91492f

### Panic Output
N/A

### Expected Behavior
What should have happened?

The resource to apply successfully.

### Actual Behavior
What actually happened?

Failure.

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
N/A

### References
N/A

**Comment by Konstantinov-Innokentii** [comment]
@mentos1386 thanks for the reporting, looks like a bug on OnCall server side

**Comment by julienduchesne** [comment]
This was fixed on the API side
