### ISSUE TITLE
I try to create a user in Grafana OSS by using API Token with admin permission but getting 503 status code 

### ISSUE THREAD

**Issue by Myasnik2000** [grafana/terraform-provider-grafana#737]
### Terraform Version
* Terraform: 1.3.5.
* Terraform Grafana Provider: 1.30.0
* Grafana: v9.2.4 
here is my terraform resource code 
resource "grafana_user" "test" {
  email    = "test.datasource@example.com"
  name     = "Testing Datasource"
  login    = "test-datasource"
  password = "my-password"
  is_admin = false
}

and provider 
provider "grafana" {
  url  = "http://url/"
  auth = "key"
}

And also I have one more question:
Can we create a user by using only email address (SSO) ?

**Comment by julienduchesne** [comment]
As the docs say: https://registry.terraform.io/providers/grafana/grafana/latest/docs/resources/user, you have to use basic auth to create another user. It's a Grafana limitation, unfortunately

**Comment by Myasnik2000** [comment]
@julienduchesne thanks so much !
