### ISSUE TITLE
[Documentation] format json_data fields for data_source are incorrect

### ISSUE THREAD

**Issue by basvdl** [grafana/terraform-provider-grafana#742]
### Terraform Version
* Terraform: v1.1.2
* Provider: registry.terraform.io/grafana/grafana v1.31.1
* Grafana: v9.2.7

### Affected Resource(s)
* data_source

In the [docs](https://registry.terraform.io/providers/grafana/grafana/latest/docs/resources/data_source#nested-schema-for-json_data) the format of the `json_data` arguments is `snake_case`. However this is not working.

From the output of the Developer tools it is clearly using `camelCase`. The same goes for the arguments in the documents under [secure_json_data](https://registry.terraform.io/providers/grafana/grafana/latest/docs/resources/data_source#nested-schema-for-secure_json_data)

Working:
```
resource "grafana_data_source" "prometheus" {
  provider = grafana.my_stack

  type = "prometheus"
  name = "robustperception"
  url  = "http://demo.robustperception.io"

  json_data_encoded = jsonencode({
    tlsSkipVerify = true
  })
}
```

Broken:
```
resource "grafana_data_source" "prometheus" {
  provider = grafana.my_stack

  type = "prometheus"
  name = "robustperception"
  url  = "http://demo.robustperception.io"

  json_data_encoded = jsonencode({
    tls_skip_verify = true
  })
}
```

**Comment by julienduchesne** [comment]
It's more of a documentation problem. All of the `json_data` attributes are deprecated and I wish I could hide them. If you look at `json_data_encoded` in the examples, it's all camelCase

**Comment by basvdl** [comment]
Could we add a note under the headers ([here](https://registry.terraform.io/providers/grafana/grafana/latest/docs/resources/data_source#nested-schema-for-json_data) and [here](https://registry.terraform.io/providers/grafana/grafana/latest/docs/resources/data_source#nested-schema-for-secure_json_data)) to make users aware that the correct way is camelCase.
