### ISSUE TITLE
create contact point error 404 not found 

### ISSUE THREAD

**Issue by ouichka** [grafana/terraform-provider-grafana#752]
### Terraform Version
* Terraform: v1.0.3
* Terraform Grafana Provider: v1.32.0
* Grafana: ...

### Affected Resource(s)
Please list the resources as a list, for example:
* grafana_contact_point

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "grafana_contact_point" "jira_contact_point" {
  name = "Jira"
  webhook {
    url               = "http://grafana-webhook/api/v1/grafana/dump"
    
  }
}
```

### Expected Behavior
Create contact_point in grafana

### Actual Behavior
Error: status: 404, body: {"message":"Not found"}

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

https://github.com/grafana/terraform-provider-grafana/issues/752#tasklist-block-610d5092-4fb6-4d7e-b273-1bf8969c257b

Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-1234

**Comment by hasindum** [comment]
Seems it comes with Grafana version < 9.1.0

**Comment by julienduchesne** [comment]
The alerting feature was added in 9.1.0
