### ISSUE TITLE
Unable to use provider with Let's Encrypt certificate

### ISSUE THREAD

**Issue by KevinGimbel** [grafana/terraform-provider-grafana#76]
### Terraform Version

```
Terraform v0.12.16
+ provider.aws v2.38.0
+ provider.grafana v1.5.0
+ provider.local v1.4.0
+ provider.mongodbatlas v0.3.1
+ provider.null v2.1.2
+ provider.random v2.2.1
+ provider.template v2.1.2
```

### Affected Resource(s)
- grafana_*

Basically all grafana resources are affected because nothing works due to SSL Certificate issues.

### Terraform Configuration Files
```hcl
resource "grafana_folder" "project_folder" {
  title = "${var.customer}"
}

resource "grafana_dashboard" "konekti" {
  provider = grafana.customer
  
  folder = grafana_folder.project_folder.id
  config_json = templatefile("grafana/dashboard.json", {
      traefik_url = local.traefik_url,
      customer_name = var.customer,
      env = local.env
  })
}
```

### Expected Behavior
I expect the terraform provider to accept Let's Encrypt certificates 

### Actual Behavior

I am unable to use any grafana resource because it always ends with this error:

```
Error: Post https://grafana.xxx.xxx/api/folders: x509: certificate signed by unknown authority
```

My computer (Mac) in trusts Let's Encrypt certificates and when I connect to Grafana using my browser or curl I also see no issues. Running the following command with a valid token works perfectly fine.

```
curl -H "Authorization: Bearer my-token-here" https://grafana.xxx.xxx/api/dashboards/home
```

### Steps to Reproduce

Run provider against a grafana instance using by Let's Encrypt certs.

### References

- #42 
- #53 
- #34

**Comment by mlclmj** [comment]
Hm, this is an interesting issue. I'm not sure off the top of my head why this provider wouldn't work with Let's Encrypt certificates--though I'll need to try to recreate it to find out

**Comment by KevinGimbel** [comment]
@mlclmj If I can assist you please let me know! The Grafana still exists on our end so I can try to reproduce the issue or test potential fixes.

**Comment by tonglil** [comment]
Related to #67.

**Comment by ruby232** [comment]
I have the same problem
I have a terraform project running with docker, with a "docker-compose.yml" with the following content:
```yml
version: "3.1"
services:
  dev:
    image: hashicorp/terraform:0.13.0
    working_dir: /workspace
    volumes:
      - .:/workspace
    env_file:
      - dev/vars.env
```
A "main.tf" file with the following content:
```tf
terraform {
  required_providers {
    k8s = {
      source  = "banzaicloud/k8s"
      version = "0.8.2"
    }
  }
  required_version = ">= 0.13"
}
provider "k8s" {
  config_path = var.kubeconfig_path
}
resource "k8s_manifest" "ingressroute" {
  provider = k8s
  content   = data.template_file.ingressroute.rendered
  namespace = var.namespace
}
```
When executing the command "terraform apply" it throws the error:
```
Error: Post "https://my-rancher.com/k8s/clusters/r-3gw5q/api/v1/namespaces/test/configmaps": x509: certificate signed by unknown authority
```
What I have tried:
1. Add the "ca-certificates" package to the official image and run the "update-ca-certificates" command.
2. Create your own image with Ubuntu.
3. Copy my "ca-certificates.crt" to "/ etc / ssl / certs /"
4. Verify the certificate in my configuration with OpenSSL

**NOTE:** Excuse me, my mistake is with another provider, I leave you the information in case it helps you, if it bothers you, let me know and I remove it.

**Comment by Srokap** [comment]
Had similar problem where it worked in browser but failed when trying to connect with Linux version of grafana provider. Web server was missing intermediate certificate in my case. Adding the certificate fixed the issue.

**Comment by julienduchesne** [comment]
Custom certs can be used now https://github.com/grafana/terraform-provider-grafana/commit/369494e470b48671014cf165efb8b7c8e11d6226
