### ISSUE TITLE
datadog datasource not fully supported

### ISSUE THREAD

**Issue by fatbasstard** [grafana/terraform-provider-grafana#766]
Datasources of type `Datadog` are not (fully) supported. More details on the plugin (making the Datasource available):

- https://grafana.com/grafana/plugins/grafana-datadog-datasource/
- https://grafana.com/docs/plugins/grafana-datadog-datasource/latest/

Fields that need to be supported in the json:

```
      api_key: API Key
      app_key: Application Key
      logApiRateLimits: false
      disableDataLinks: false
```

Can this be supported?      

### Terraform Version
* Terraform: 1.3.7
* Terraform Grafana Provider: 1.32.0
* Grafana: 8.5.15

### Affected Resource(s)
Please list the resources as a list, for example:
* grafana_datasource

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "grafana_data_source" "datadog" {
  type  = "grafana-datadog-datasource"
  name  = "DataDog"
  url   = "https://api.datadoghq.com"

  secure_json_data_encoded = jsonencode({
    api_key = xxx
    app_key = yyy
  })
}
```

### Debug Output
Even though I've set `TF_LOG=debug`, the Grafana provider gives no insights whatsover on what is actually sent to Grafana:

```2023-01-05T14:04:18.728Z [WARN]  Provider "registry.terraform.io/grafana/grafana" produced an invalid plan for module.xxx.grafana_data_source.datadog[0], but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .access_mode: planned value cty.StringVal("proxy") for a non-computed attribute
      - .basic_auth_enabled: planned value cty.False for a non-computed attribute
      - .is_default: planned value cty.False for a non-computed attribute
{"@level":"info","@message":"module.xxx.grafana_data_source.datadog[0]: Creating...","@module":"terraform.ui","@timestamp":"2023-01-05T14:04:18.728758Z","hook":{"resource":{"addr":"module.xxx.grafana_data_source.datadog[0]","module":"module.xxx","resource":"grafana_data_source.datadog[0]","implied_provider":"grafana","resource_type":"grafana_data_source","resource_name":"datadog","resource_key":0},"action":"create"},"type":"apply_start"}
2023-01-05T14:04:18.728Z [INFO]  Starting apply for module.xxx.grafana_data_source.datadog[0]
2023-01-05T14:04:18.729Z [DEBUG] module.xxx.grafana_data_source.datadog[0]: applying the planned Create change
```

### Expected Behavior
At first I assumed the JSON data would be "parsed" and communicated to Grafana anyway. So if the values would have been unsupported I'd expect the provider to give me an error or a warning.

### Actual Behavior
Datasource is created in Grafana, just without configuration

**Comment by julienduchesne** [comment]
Seems like the docs are wrong. I just tried it in my cloud instance. This is what the payload looks like: 
```
{
...
  "name": "Datadog",
  "type": "grafana-datadog-datasource",
...
  "secureJsonData": {
    "apiKey": "test1",
    "appKey": "test2"
  }
}
```

**Comment by fatbasstard** [comment]
Ha @julienduchesne,

Just checked your example and this indeed works!

I got confused by the documentation indeed, but also by the facts that these fields are not configured (Didn't saw it documented in https://github.com/grafana/terraform-provider-grafana/blob/master/grafana/resource_data_source.go#L472)
