### ISSUE TITLE
Provider cannot connect to Grafana instance, throws 401 Unauthorized

### ISSUE THREAD

**Issue by neocorp** [grafana/terraform-provider-grafana#77]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v0.12.16
+ provider.aws v2.39.0
+ provider.grafana v1.4.0
+ provider.null v2.1.2
+ provider.random v2.2.1

### Affected Resource(s)
- grafana_data_source

Issue seems to be with Grafana provider itself, it cannot seem to authenticate.

### Terraform Configuration Files
```hcl
provider "grafana" {
  url = "https://grafana.${var.platform_domain_name}"
  auth = "${var.grafana_admin_username};${var.grafana_admin_password}"
  version = "1.4"
}

resource "grafana_data_source" "staging" {
  name                = "Staging"
  type                = "cloudwatch"

  json_data {
    auth_type       = "arn"
    default_region  = var.region
    assume_role_arn = "arn:aws:iam::${lookup(var.aws_account_ids, "staging")}:role/grafana"
  }
}

resource "grafana_data_source" "qa" {
  name                = "QA"
  type                = "cloudwatch"

  json_data {
    auth_type       = "arn"
    default_region  = var.region
    assume_role_arn = "arn:aws:iam::${lookup(var.aws_account_ids, "qa")}:role/grafana"
  }
}
```

### Debug Output
https://gist.github.com/neocorp/72468d6c33c34dafabc6c97f6cc662cf

### Panic Output
N/A

### Expected Behavior
Grafana provider should be able to connect to Grafana and create the data sources.

### Actual Behavior
Terraform throws 401 Unauthorized error. Using username/password combination or API Token from Grafana doesn't make a difference, produces the same error.

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`

### Important Factoids
Grafana instance is running on ECS Fargate and accessible for terraform environment.
Issue can also be reproduced with 1.5 Grafana provider version.

**Comment by charlottemach** [comment]
You have a semicolon between your username and password `;`, instead of them being [separated by a colon ](https://www.terraform.io/docs/providers/grafana/)`:`, might make a difference.

**Comment by chorne-togetherwork** [comment]
Same issue, and as @neocorp said, using the API Token doesn't work either, and that does not require a colon or semicolon.

**Comment by shalyng** [comment]
Do you have basic_auth enabled? It seems username/password combo only works with basic_auth enabled.https://grafana.com/docs/grafana/latest/http_api/auth/#basic-auth

**Comment by chorne-togetherwork** [comment]
Mine was as simple as updating the url to use https, it seems. The semicolon may be part of the original issue, but v1.5 of the provider is also available, so I'm not sure if that would make a difference.

**Comment by neocorp** [comment]
I've tried with colon, semicolon, added basic_auth_enabled flag and almost every possible combination but no luck. Mine is on https already and also tried with v1.5 of the provider, still no luck. Any help is really appreciated, I'd rather implement these datasources and dashboards with Terraform.

**Comment by pascal-hofmann** [comment]
Maybe some of you are running into this issue: https://github.com/nytm/go-grafana-api/pull/41

Took me a while to figure out, that colons (`:`) in passwords are not supported right now…

**Comment by mlclmj** [comment]
The colons-in-passwords issue was patched upstream (thanks @pascal-hofmann!) and will be included in the next release.

401 errors typically aren't the fault of the provider itself, though if there's other issues with how we're parsing/passing credentials that'd definitely be something to address

**Comment by tonglil** [comment]
This should be fixed when a release of the provided is cut (see #97).

**Comment by Ezward** [comment]
I get this error as well.  Neither the username nor password has a colon in them.  I'm separating them with a colon.  I can log into the grafana instance with that username and password pair.  I can configure that same prometheus data source in the grafana UI, so it is not a networking issue.  But that does bring to mind; If I had a datasource source already with that name, would I get a 401 (I would not expect that) or some other error code?  This is what I get;
```
1 error occurred:
	* module.grafana.grafana_data_source.prometheus: 1 error occurred:
	* grafana_data_source.prometheus: 401 Unauthorized
```

**Comment by inkel** [comment]
Hi! Thank you for reporting this, and sorry for the long delay it took us to get back in touch.

After careful consideration we're going to close this one, as it refers to outdated versions of both the Grafana provider and Terraform itself.

If you continue to experience this issue please try again with the latest versions of both tools mentioned above, and otherwise reopen this issue.

Thanks for understanding.
