### ISSUE TITLE
Provider tries to modify user's login on each apply to null value

### ISSUE THREAD

**Issue by Vimao** [grafana/terraform-provider-grafana#783]
### Terraform Version
* Terraform: 0.15.5
* Terraform Grafana Provider: 1.31.1
* Grafana: 9.3.0

### Affected Resource(s)
Please list the resources as a list, for example:
* grafana_user

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "grafana_user" "user" {
  email    = var.user_email
  name     = var.user_name
  login    = var.user_name
  password = random_password.user_password.result
  is_admin = var.user_is_admin
}

resource "random_password" "user_password" {
  length           = 16
  special          = true
  override_special = "!#$%&*()-_=+[]{}<>:?"
}
```

### Debug Output
Due to nature on the environment on which the issue occurs, i can't really send the debug without proprietary information

### Expected Behavior
Existing user who did not change his login should not be shown during plan

### Actual Behavior
Existing user is shown during plan as login being modified from current value to null. After apply login is unchanged
![image](https://user-images.githubusercontent.com/47415312/212048657-a7c5e486-2958-46ec-8594-de243c3676af.png)

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
2. `terraform apply` again

**Comment by julienduchesne** [comment]
Are you 100% sure that you haven't changed the `user_name` variable value? When you `terraform plan` or look at the plan of an apply, what you see in the expected changes is exactly what is in your definition. The provider doesn't act in any way on that expected value in this case

Can you try it out with static values rather than variables?

**Comment by Vimao** [comment]
Sorry, i checked my work and it was actually a broken try expression on my side. Sorry for wasting your time.

**Comment by julienduchesne** [comment]
> Sorry, i checked my work and it was actually a broken try expression on my side. Sorry for wasting your time.

No worries! Thanks for confirming 👍
