### ISSUE TITLE
Creating grafana_contact_point with no destination results in `Root resource was present, but now absent.`

### ISSUE THREAD

**Issue by vCra** [grafana/terraform-provider-grafana#797]
### Terraform Version
* Terraform: 1.2.9
* Terraform Grafana Provider: 1.34.0
* Grafana: 9.3.2

### Affected Resource(s)
* grafana_contact_point

### Terraform Configuration Files

```hcl
resource "grafana_contact_point" "dev_null" {
  name = "empty-test"
}
```

### Debug Output

https://gist.github.com/vCra/59b7cc52d8cf278f921a45457962363c#file-grafana-contact-point-error

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
What should have happened?

A contact point with no destination should be created

### Actual Behavior
What actually happened?

│ Error: Provider produced inconsistent result after apply
│
│ When applying changes to grafana_contact_point.empty_test, provider "provider[\"registry.terraform.io/grafana/grafana\"]" produced an unexpected new value: Root resource was present, but now absent.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.

### Steps to Reproduce

1. `terraform apply`

**Comment by alexweav** [comment]
The API that terraform uses does not support this unfortunately - a contact point with no receivers cannot be created through other provisioning methods to Grafana either. The API works at the level of individual contact points and not the entire group.

This is a reasonable feature request in the grafana/grafana repo, IMO, you might want to try creating this there.

The error message you're getting is definitely a bug - the message should instead be something that explains that at least one receiver is required in the object, but in the very short term this still won't be possible from the provider without a corresponding change in Grafana.
