### ISSUE TITLE
[Elastic Data Source] Terraformed alert and UI alert values mismatch

### ISSUE THREAD

**Issue by SergioBernabe96** [grafana/terraform-provider-grafana#800]
Hi.

We have an alert group with one rule which we want to terraform. The rule is based on an Elastic Data Source. We created a simple query which returns the number of documents in Elastic, and when compared with Kibana, both return the same values. 

However, when we decided to terraform it, once applied it is returning slightly different values which affect our alert system. If we check the values in the Alert Group tab, and then we click in the "View in Explore" button, it opens a graph which does return the expected values. 

Everything looks exactly the same in both alerts, the terraformed one and the one created trough the UI. The one created trough the UI does match de datasource, the terraformed one doesn't.

Why is this mismatch happening? 

Screenshot with the values returned in the terraformed alert:
![Screenshot 2023-02-01 at 11 38 27](https://user-images.githubusercontent.com/76034973/216020766-570e38fa-4625-4916-8c3d-9b74768f7363.png)

Screenshot with the values returned clicking in the "View in Explore" button:
![Screenshot 2023-02-01 at 11 38 19](https://user-images.githubusercontent.com/76034973/216020873-81389db4-3ced-43aa-838c-7a47008e7373.png)

### Terraform Version
* Terraform: 1.29
* Terraform Grafana Provider: 1.34.0
* Grafana: 9.3

### Affected Resource(s)
Please list the resources as a list, for example:
* grafana_rule_group

### Expected Behavior
What should have happened?
The terraformed alert group should retrieve the same information than the Elastic datasource.

### Actual Behavior
What actually happened?
The terraformed alert group is retrieving slightly different values from the datasource.

**Comment by julienduchesne** [comment]
Hello, is this still happening? Alerting has changed a lot since that issue was opened. It doesn't seem like TF issue to me
