### ISSUE TITLE
[Feature Request] Support Bigquery datasource

### ISSUE THREAD

**Issue by bkamin29** [grafana/terraform-provider-grafana#81]
Hello,

It will'd be great to be able to use configure the version `grafana_data_source` to create a new doitintl-bigquery-datasource.
Today it's possible to create it but it's not possible to add the JSON key of the GCP Service account to use.

**Affected Resource(s)**

- grafana_data_source

**Comment by mlclmj** [comment]
Hey @benesis002--I agree! Feel free to open a PR for this if you'd like. Note this also will require an upstream library change to support it.

I'm working my way through the backlog that's built up but have been tackling data sources recently so would be happy to review another update here.

**Comment by DrFaust92** [comment]
i was able to create it like this:

```
resource "grafana_data_source" "bigque" {
  type = "doitintl-bigquery-datasource"
  name = "bigquery-test"
  json_data {
    token_uri = "https://oauth2.googleapis.com/token"
    authentication_type = "jwt"
    default_project = "project"
    client_email = "sa-name@project-name.iam.gserviceaccount.com" // full SA name
  }
  secure_json_data {
    private_key = "-----BEGIN PRIVATE KEY-----\nprivate-key\n-----END PRIVATE KEY-----\n" // sa private key
  }
}
```
