### ISSUE TITLE
Terraform: Creating multiple resources (investigate for SAs) makes APIs non-responsive

### ISSUE THREAD

**Issue by eleijonmarck** [grafana/terraform-provider-grafana#827]
**what/why**
We have users provision service accounts via terraform when creating multiple resources of service accounts ~20 the APIs get non-responsive, and terraform creates a loop of trying to create the SAs.

This results in a invalid state between grafana and terraform. Which can only be solved by `terraform import` each resource. This is a time consuming and yields creation of multiple resources hard to use in terraform.

**DoD**
- [x] investigate why API calls for creating ~20 service accounts through terraform is not successful
- [ ] investigate if this is consistent with creating any resource or only service accounts

**investigation**
- locally I can create 20 service accounts without problem
- cloud is consistent that the API deems unresponsive when creating multiple SAs at the same time
- 
**note**
This might not be specific to service accounts, should be tested also with creating users

the specific terraform that can be used to try this out:
```tf
terraform {
  required_providers {
    grafana = {
      source  = "grafana/grafana"
    }
  }
}

# Declaring the first provider to be only used for creating the cloud-stack
provider "grafana" {
  alias = "first"

  cloud_api_key = "<API-Key>" 
}

resource "grafana_cloud_stack" "eleijonmarck" {
  provider = grafana.first

  name        = "eleijonmarck.grafana.net"
  slug        = "eleijonmarck"
  region_slug = "eu" # Example “us”,”eu” etc
}

# Creating an API key in Grafana instance to be used for creating resources in Grafana instance
resource "grafana_api_key" "cloud_api_key" {
  provider = grafana.first

  cloud_stack_slug = grafana_cloud_stack.eleijonmarck.slug
  name             = "cloud_api_key"
  role             = "Admin" 
}

# Declaring the second provider to be used for creating resources in Grafana        
provider "grafana" {
  alias = "second"

  url  = grafana_cloud_stack.eleijonmarck.url
  auth = grafana_api_key.cloud_api_key.key
}

# Creating a service account in Grafana instance to be used as auth
resource "grafana_service_account" "eleijonmarck_service_account" {
  provider = grafana.second

  name             = "eleijonmarck-sa"
  role             = "Admin"
  is_disabled = false
}

# Creating a service account token in Grafana instance to be used for creating resources in Grafana instance
resource "grafana_service_account_token" "eleijonmarck_service-account_token" {
  provider = grafana.second

  name               = "eleijonmarck-sa-token"
  service_account_id = grafana_service_account.eleijonmarck_service_account.id
}

locals {
  merged_teams = {
    "admin-3" = { name = "admin-1-name", role = "Admin" },
    "admin-4" = { name = "admin-2-name", role = "Viewer" },
    "admin-5" = { name = "admin-2-name", role = "Viewer" },
    "admin-6" = { name = "admin-2-name", role = "Viewer" },
    "admin-7" = { name = "admin-2-name", role = "Viewer" },
    "admin-8" = { name = "admin-2-name", role = "Viewer" },
    "admin-9" = { name = "admin-2-name", role = "Viewer" },
    "admin-10" = { name = "admin-2-name", role = "Viewer" },
    "admin-11" = { name = "admin-2-name", role = "Viewer" },
    "admin-12" = { name = "admin-2-name", role = "Viewer" },
    "admin-14" = { name = "admin-2-name", role = "Viewer" },
    "admin-15" = { name = "admin-2-name", role = "Viewer" },
    "admin-16" = { name = "admin-2-name", role = "Viewer" },
    "admin-17" = { name = "admin-2-name", role = "Viewer" },
    "admin-18" = { name = "admin-2-name", role = "Viewer" },
    "admin-19" = { name = "admin-2-name", role = "Viewer" },
    "admin-20" = { name = "admin-2-name", role = "Viewer" },
  }
}

resource "grafana_service_account" "service_account" {
  provider = grafana.second

  for_each    = local.merged_teams
  name        = format("%s-sa-default", lower(replace(each.key, "/\\W/", "-")))
  is_disabled = false
  role        = each.value.role
  lifecycle {
    ignore_changes = [
      name,
      is_disabled,
    ]
  }
}
```

**Comment by eleijonmarck** [comment]
investigated this further by using a bash script for calling the same API on local and in cloud and that works just fine.

```bash
#!/bin/bash

# Grafana API endpoint
GRAFANA_API="https://eleijonmarck.grafana.net/api/serviceaccounts/"
# GRAFANA_API="http://localhost:3000/api/serviceaccounts/"

# Bearer token authorization
BEARER_TOKEN="<>"
# BEARER_TOKEN="<>"

# Loop through 20 different names and create a service account for each
for i in {1..20}
do
    # JSON payload for creating a service account
    JSON_PAYLOAD='{
    	"name": "<>",
    	"role": "Admin"
    }'

    # Generate a unique name for the service account
    NAME="service-account-$i"
    
    # Print the name to the console
    echo $NAME + "\n"

    # Replace the placeholder in the JSON payload with the unique name
    JSON_PAYLOAD=$(echo $JSON_PAYLOAD | sed "s/<>/$NAME/g")
    
    # Print the JSON payload to the console
    echo $JSON_PAYLOAD + "\n"

    # Call the Grafana API to create the service account
    curl -H "Authorization: Bearer $BEARER_TOKEN" -H "Content-Type: application/json" -X POST -d "$JSON_PAYLOAD" $GRAFANA_API

    # Print a message to indicate that the service account has been created
    echo "Service account created: $NAME"
done
```

this successfully creates 20 service accounts locally and in the grafana cloud instance. making more of the assumption that there is something in the provider or grafana-api-client that makes the creation of multiple service accounts through the API unresponsive or in a state that is not desired.

**Comment by eleijonmarck** [comment]
--
assumption: potentially the `for_each` method in terraform makes async calls to the APIs which could cause it to be unresponsive. Making another script but for calling it async with the creation of multiple accounts.

**Comment by eleijonmarck** [comment]
@hairyhenderson and I talked around how the shared db are causing congestion in our dbs. Basically the terraform provider uses unlimited number of HTTP connections per host (which is fine for API calls) but if the API calls are creating db sessions it will want to allocate that amount of sessions on our shared db instance.

Grafana cloud instances share a db instance and the free/enterprise tiers each have a default of 5 open db connections as a limit, if we have more than that the db starts congesting.



We would probably need to investigate a bit further but one solution might be too add a limit on the number of concurrent connections in the transport configuration - https://github.com/grafana/terraform-provider-grafana/blob/6394575917a26e2d6e95f415227bf6e841c195c5/internal/provider/provider.go#L342

```go
func createGrafanaClient(d *schema.ResourceData) (string, *gapi.Config, *gapi.Client, error) {
	auth := strings.SplitN(d.Get("auth").(string), ":", 2)
	cli := cleanhttp.DefaultClient()
	transport := cleanhttp.DefaultTransport()
//      + transport.MaxConnsPerHost = 2
	transport.TLSClientConfig = &tls.Config{}

	// TLS Confi
```

**Comment by eleijonmarck** [comment]
we were able to solve the issue by allowing the grafana-cloud instance to have 100 db connections (not preferable for obvious reasons)

see - https://ops.grafana-ops.net/d/BqokFhx7z/hg-instance-debugging?orgId=1&var-datasource=ops-cortex&var-lokidatasource=Grafana%20Logging&var-cluster=prod-eu-west-0&var-slug=eleijonmarck&from=1677521438277&to=1677522636525

**Comment by eleijonmarck** [comment]
@julienduchesne let me know if you wanna setup a meeting and discuss this change with me @hairyhenderson

**Comment by IevaVasiljeva** [comment]
PR to improve service account creation logic: https://github.com/grafana/grafana/pull/63884

**Comment by eleijonmarck** [comment]
one of the things we could do is to implement a PUT endpoint for service account creation and if we can identify a `for_each` we would call that PUT endpoint
