### ISSUE TITLE
 Datasource Type: Google Cloud Monitoring creation is not working correctly

### ISSUE THREAD

**Issue by ctsanjuan** [grafana/terraform-provider-grafana#828]
### Terraform Version
* Terraform: v1.1.9
* Terraform Grafana Provider: v1.35.0.
* Grafana: Grafana Cloud [v9.3.2-67a213dc85 (67a213dc85)]

### Affected Resource(s)
Please list the resources as a list, for example:
* grafana_data_source

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "grafana_data_source" "google-stack-driver-test" {
  provider            = grafana.stack
  type                = "stackdriver"
  name                = "StackDriver-test"
  json_data_encoded = jsonencode({
    "tokenUri"           = "https://oauth2.googleapis.com/token"
    "authenticationType" = "jwt"
    "defaultProject"     = "<project>"
    "clientEmail"        = "<client_email>"
  })

  secure_json_data_encoded = jsonencode({
    "privateKey" = "-----BEGIN PRIVATE KEY-----\n<private_key>\n-----END PRIVATE KEY-----\n"
  })
}
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
New datasource of type "Google Monitoring" creation with all information

### Actual Behavior
Datasource with name "google-stack-driver-test" created but WITHOUT jwt token information

### Steps to Reproduce

1. `terraform apply`

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

### References
N/A

**Comment by julienduchesne** [comment]
I tried the latest version with the exact same configuration that you posted here and it worked. Can you try again with the latest version?

**Comment by julienduchesne** [comment]
Closing this for now. Please reopen if it's still an issue
