### ISSUE TITLE
Setting the alert notification channel uid

### ISSUE THREAD

**Issue by yzargari** [grafana/terraform-provider-grafana#83]
Hello,

According to [grafana API docs](https://grafana.com/docs/grafana/latest/http_api/alerting_notification_channels/), an alert notification channel can be set with a UID. I'd be happy to be able to set that with the grafana_alert_notification resource or for the very least get the auto-generated UID pulled and made available for me to refer to (as in id).

The reason for that is that when I create a dashboard that contains an alert, I need to refer to the alert by that uid - and there's no way for me to tell what the uid of the notification channel I created otherwise.

Thanks,
Yosi

**Comment by tonglil** [comment]
Closed by https://github.com/terraform-providers/terraform-provider-grafana/pull/87
