### ISSUE TITLE
Team_id is not found when used with on call resources

### ISSUE THREAD

**Issue by project0** [grafana/terraform-provider-grafana#843]
### Terraform Version
* Terraform: 1.3.5
* Terraform Grafana Provider: 1.35.0
* Grafana: grafana cloud (pro)

### Affected Resource(s)

* grafana_team
* data.grafana_oncall_team
* grafana_oncall_schedule (actually all on-call resources with team_id)

### Terraform Configuration Files
```hcl
# either looked up via data, as like mentioned in the docs
data "grafana_oncall_team" "team" {
  name = "test-on-call"
}

# or with a fresh group
resource "grafana_team" "test-team" {
  name  = "Test Team"
  email = "teamemail@example.com"
  members = [
    "member"
  ]
}

locals {
  oncall_team_id = grafana_team.test-team.team_id # or id, does not matter, whatever the difference is...
 # or with data lookup
  oncall_team_id = data.grafana_oncall_team.id
}

# it leads to same issue
resource "grafana_oncall_schedule" "platform_oncall" {
  provider = grafana.oncall
  team_id  = local.oncall_team_id
  time_zone  = "Europe/Paris"
  name = "Platform"
  type = "calendar"
  shifts = [
    #grafana_oncall_on_call_shift.platform_oncall.id
  ]
}
```

### Debug Output
[Debug Log](https://gist.github.com/project0/3b0bc71f33724982e7dad50b81e11a80)

### Expected Behavior
Deploy resources assigned to the specified team_id.

### Actual Behavior

```
╷
│ Error: POST https://oncall-prod-us-central-0.grafana.net/oncall/api/v1/schedules/: 400 {team_id: [Object does not exist]}
│ 
│   with grafana_oncall_schedule.platform_oncall,
│   on on_call.tf line 150, in resource "grafana_oncall_schedule" "platform_oncall":
│  150: resource "grafana_oncall_schedule" "platform_oncall" {
│ 
╵

```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
grafana cloud

**Comment by julienduchesne** [comment]
Duplicate of https://github.com/grafana/terraform-provider-grafana/issues/540

**Comment by Konstantinov-Innokentii** [comment]
@project0 I just was able to apply following tf configuration:
```
data "grafana_oncall_team" "test" {
  provider = grafana.oncall
  name = "test-on-call"
}



resource "grafana_oncall_schedule" "platform_oncall" {
  provider = grafana.oncall
  team_id  = data.grafana_oncall_team.test.id
  time_zone  = "Europe/Paris"
  name = "Platform"
  type = "calendar"
  shifts = [
  ]
}
```
Please, use oncall datasource id, when passing it as team_id argument to oncall resources. If grafana_oncall_team datasource read fails with 404 just retry `terraform apply` in a minute, sometimes oncall needs time to sync teams with grafana. We are working on more "smooth" process for that.
