### ISSUE TITLE
Issue providing X-Disable-Provenance header

### ISSUE THREAD

**Issue by phyzical** [grafana/terraform-provider-grafana#845]
### Terraform Version
* Terraform: v1.4.0
* Terraform Grafana Provider: 1.32.0
* Grafana: v9.3.0
### Affected Resource(s)
Please list the resources as a list, for example:
* grafana_rule_group

### Terraform Configuration Files
```hcl
provider "grafana" {
  url    = "https://some_url"
  auth   = var.grafana_api_token
  org_id = 1
  http_headers = {
    "X-Disable-Provenance" = "disabled"
  }
}
```

### Expected Behavior
Created resource shouldnt be marked as provisioned in the ui

### Actual Behavior
Resource is still uneditable and marked as provisioned

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
According to https://github.com/grafana/grafana/pull/58410#issuecomment-1456137594 

we should be able to provide the header `"X-Disable-Provenance" = "disabled"`  and the ui should still allow the created resource to be editable. one user has confirmed this as working via a manually json post but adding this custom header via the provider seems to have no effect?

**Comment by phyzical** [comment]
i tried looking at references to where the http headers are compiled and i couldn't see any obvious logic as to why this header would have no effect so im not sure why it wouldn't work 🤔

**Comment by julienduchesne** [comment]
Are you specifying a `folder_uid`? This could be the issue: https://github.com/grafana/terraform-provider-grafana/issues/697#issuecomment-1444610937

**Comment by phyzical** [comment]
Ah thank you, yes i am specifying the folder uuid as its required on the resource, is there something ive missed here? 
![image](https://user-images.githubusercontent.com/5182053/224190247-36e84a85-c10b-4849-a80f-bd28b9355f48.png)

**Comment by ishworg** [comment]
hey folks any way to mitigate this as of today? thanks

**Comment by smiller-dn** [comment]
FWIW I expect that this works against Grafana 9.5.1, per https://github.com/grafana/grafana/issues/63047.  As far as I know, the only way to make that work for 9.3 would be to upgrade to 9.5.1 (or later, if there is a later).

I'd also looked at the code in `main` and wondered why it was only working for alert rules, as in "why in the hell doesn't this work, the code is *right there*!"  I then realized that if I looked at the code as of earlier release tags (even 9.4.X), the code to support that header for other alert-provisioning endpoints wasn't yet there. 😄

**Comment by mucahitkantepe** [comment]
We are hitting the same issue as @smiller-dn mentioned. It works for alert-groups but fails for contact points with 

```text
cannot change provenance from 'api' to ''"
```

**Comment by smiller-dn** [comment]
@mucahitkantepe I expect the only way to fix this is to upgrade to 9.5.1 or later (though it works fine then, at least for me).

**Comment by mfmbarros** [comment]
Fails for me on 9.5.1 when trying to change an already provisioned contact point:

cannot change provenance from 'api' to ''


Grafana provider: 1.36.1

**Comment by mucahitkantepe** [comment]
didn’t work with the 9.5.1, I ended up deleting and creating them again

**Comment by julienduchesne** [comment]
This is a duplicate of https://github.com/grafana/terraform-provider-grafana/issues/697. I will close it for now. From what I've seen, this is set to be fixed in Grafana 10
