### ISSUE TITLE
Empty requests sent to Grafana.com API, 400/409 errors

### ISSUE THREAD

**Issue by monodot** [grafana/terraform-provider-grafana#853]
### Terraform Version
* Terraform: 1.3.7
* Terraform Grafana Provider: 1.36.1
* Grafana: Cloud

### Affected Resource(s)
* grafana_cloud_stack
* grafana_cloud_api_key

These are the resources I've seen affected so far, will share if there are others.

### Terraform Configuration Files
Configuration is too large to share here, can share privately.

### Debug Output
Will share privately

### Expected Behavior
Resources should be created successfully.

### Actual Behavior
Intermittently, error messages like this are seen in the log:

```
╷
│ Error: status: 409, body: {
│   "code": "InvalidArgument",
│   "message": "Field is required: name",
│   "requestId": "acbbb170-7122-4f6c-a58f-41564a94feaa"
│ }
│ 
│   with module.workshop_infra.module.student_grafana_cloud_stack["user10@example.com"].grafana_cloud_stack.stack,
│   on ../../../../field-eng-infra/terraform/modules/services/grafana-cloud-stack/main.tf line 17, in resource "grafana_cloud_stack" "stack":
│   17: resource "grafana_cloud_stack" "stack" {
│ 
╵
╷
│ Error: status: 409, body: {
│   "code": "InvalidArgument",
│   "message": "Field is required: name",
│   "requestId": "d797df39-0410-422f-8b87-63b69fc155e2"
│ }
│ 
│   with module.workshop_infra.module.student_grafana_cloud_stack["user04@example.com"].grafana_cloud_api_key.publisher,
│   on ../../../../field-eng-infra/terraform/modules/services/grafana-cloud-stack/main.tf line 51, in resource "grafana_cloud_api_key" "publisher":
│   51: resource "grafana_cloud_api_key" "publisher" {
│ 
╵
```

It seems that some requests are being sent to the Grafana.com API with empty request bodies. I ran a simple proxy (mitmproxy) and directed all Terraform requests through it. I saw this - the screenshot shows a request from the provider to the Grafana.com API, but the request is empty. You can see the `409` response code at the top:

![image](https://user-images.githubusercontent.com/1423165/225003130-cbcffcf1-524d-4087-8cfe-63508740309a.png)

### Steps to Reproduce
1. Create a Terraform configuration which deploys many Grafana Cloud stacks and creates an API key for each
2. Run Terraform with the default parallelism (10)
3. Run `terraform apply`

The behaviour is seen intermittently.

### Important Factoids
No

### References
N/A

**Comment by cinaglia** [comment]
@monodot We believe we have addressed this issue in [v1.40.1](https://github.com/grafana/terraform-provider-grafana/releases/tag/v1.40.1) (thanks to @inkel). Would you mind giving it a try and reporting back? Much appreciated.
