### ISSUE TITLE
Update team id at oncall resources are not effective

### ISSUE THREAD

**Issue by project0** [grafana/terraform-provider-grafana#854]
### Terraform Version
* Terraform: 1.4.1
* Terraform Grafana Provider: 1.36.1
* Grafana: cloud

### Affected Resource(s)
Please list the resources as a list, for example:
* grafana_oncall_escalation_chain
* grafana_oncall_on_call_shift
* grafana_oncall_schedule

### Terraform Configuration Files
```hcl
data "grafana_oncall_team" "team" {
  name = "Switch team"
}

resource "grafana_oncall_on_call_shift" "platform_oncall" {
  team_id  = data.grafana_oncall_team.team.id
 ....
}
```

### Expected Behavior
Force replace resources or update the team.

### Actual Behavior

When updating the team id it never updates.
The plan keeps changing on every run and the resource is never updated with the new team.

```
  # grafana_oncall_schedule.platform_oncall will be updated in-place
  ~ resource "grafana_oncall_schedule" "platform_oncall" {
        id                 = "SLIWJS4X2UWCE"
        name               = "Platform"
      + team_id            = "TNW1ZIT5HWI1Y"
        # (4 unchanged attributes hidden)
    }
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by prajith-nair** [comment]
Your current configuration looks like below : 

```
data "grafana_oncall_team" "team" {
  name = "Switch team"
}

resource "grafana_oncall_on_call_shift" "platform_oncall" {
  team_id  = data.grafana_oncall_team.id
 ....
}
```

Are you missing below in your config ? 

`team_id   = data.grafana_oncall_team.**team**.id` as opposed to 
`team_id  = data.grafana_oncall_team.id`

**Comment by project0** [comment]
@prajith-nair true, the example was not correct. I have updated the example.
