### ISSUE TITLE
Grafana provider ENV variables as preferred

### ISSUE THREAD

**Issue by tcondeixa** [grafana/terraform-provider-grafana#88]
Hi there,

I would like to ask why ENV variables are used as default and not as the 1st preference for url and auth?

Use-case:
I would like to keep grafana url defined through load balancers for when I need to apply terraform from our local laptops, but having a CD/CD running inside kubernetes I would like it uses the services address instead. If we define the ENV variable I would expect that could be the preferred option instead of being only the default. So, I would only need to set the GRAFANA_URL variable in my CI/CD, and it would run smoothly without any more terraform resources with if conditions. 
I would say that most of the services always use ENV variables as the preferred method if they are defined, otherwise they check files and other sources.

Thanks a lot and keep the good work

**Comment by mlclmj** [comment]
Hey @tcondeixa, I think it's expected behavior that enumerated values within the provider configuration will always take precedence over ones specified in the environment--I think most other providers follow this pattern as well i.e. GitHub, Vault, etc.

Is there a reason you're unable to specify them in the environment and leave the options unset in the provider config?

**Comment by tcondeixa** [comment]
> Hey @tcondeixa, I think it's expected behavior that enumerated values within the provider configuration will always take precedence over ones specified in the environment--I think most other providers follow this pattern as well i.e. GitHub, Vault, etc.
> 
> Is there a reason you're unable to specify them in the environment and leave the options unset in the provider config?

Hi @mlclmj, I would like to keep the options set when applying terraform from local laptops and only force to use the kubernetes svc when applying from CI/CD (Jenkins). The setting of the grafana provider are coming from a initi terraform module, so I don't force everyone to know and set the terraform provider through environmental variables.

**Comment by mlclmj** [comment]
have you tried doing this through [Terraform variables](https://www.terraform.io/docs/configuration/variables.html)? I don't think this is a behaviour change we can make to the provider, but Terraform offers other ways that should work to accomplish this

**Comment by tcondeixa** [comment]
> have you tried doing this through [Terraform variables](https://www.terraform.io/docs/configuration/variables.html)? I don't think this is a behaviour change we can make to the provider, but Terraform offers other ways that should work to accomplish this

yes, we are using variables but we set them as default to use the load balancers outside of the k8s cluster. When we run that in k8s jenkins we need to change the provider to the k8s SVC. We have an workaround with a data external reading the env variable but It would be much cleaner just to set the ENV variables.

**Comment by mlclmj** [comment]
Ah, I see. I understand the use case, but again would strongly suggest looking into Terraform variables (which can be overridden by environment variables!).

Given what I understand here, I still believe the provider is functioning as expected, but please let me know if I've misunderstood.
Changing this behavior would be both: a breaking change to the provider, and deviate from common configuration patterns in my opinion.
