### ISSUE TITLE
grafana_rule_group - rule group name cannot contain slash but it should

### ISSUE THREAD

**Issue by bursztyn-pl** [grafana/terraform-provider-grafana#883]
### Terraform Version
* Terraform: 1.4.5
* Terraform Grafana Provider: 1.37.1
* Grafana: 9.4.7

### Affected Resource(s)
Please list the resources as a list, for example:
* grafana_rule_group

### Terraform Configuration Files
```hcl
resource "grafana_rule_group" "alertrule" {
  provider = grafana.asdf
  folder_uid       = "l-vi4qY4k"
  interval_seconds = 60
  name             = "Test/Group" # <--- Here is an issue
  org_id           = "1"
  ...
}
```

### Expected Behavior
Resource to be created

### Actual Behavior
Error: status: 404, body: {"message":"Not found"}

### Steps to Reproduce
1. Provide name of rule group with slash in it, eg. "Test/Group"
2. `terraform apply`

In general, creating alert rule and providing group name with slash is allowed when user creates it in GUI or directly via API call.
When using terraform provider it throws an error provided above. When slash is removed from name, resource is created successfully.

**Comment by julienduchesne** [comment]
The UI follows a different structure than Terraform. The UI is rule-first and Terraform is group-first.

In the UI, it's also impossible to create a group with a slash in it:
![image](https://github.com/grafana/terraform-provider-grafana/assets/29210090/2bd7096c-d1aa-4f25-a622-9b305f9ed626)


A rule with a slash in it is possible but it would be further embedded in terraform:
```
resource "grafana_rule_group" "alertrule" {
  provider = grafana.asdf
  folder_uid       = "l-vi4qY4k"
  interval_seconds = 60
  name             = "group"
  org_id           = "1"
  rule {
     name = "test/rule"
     ...
  }
}
```

Let me know if that doesn't work. In the meantime, I'll close the issue (easier to manage this way). But feel free to re-open
