### ISSUE TITLE
Garafana cloud datasource version is now 2, resulting in provisioning flakiness

### ISSUE THREAD

**Issue by mindw** [grafana/terraform-provider-grafana#887]
### Terraform Version
* Terraform: 1.3.x
* Terraform 1.37.1
* Grafana: CLOUD Grafana v9.5.0-cloud.4.a016665c (57d4bf9f7e)

### Affected Resource(s)
* grafana_datasource

### Terraform Configuration Files
```hcl
resource "grafana_data_source" "stack" {
  provider = grafana.stack

  name                = "${var.stack_name}-stack-prom"
  type                = "prometheus"
  url                 = "https://${aws_route53_record.monitoring_ingress.name}"
  basic_auth_enabled  = true
  basic_auth_username = "monitoring"

  json_data_encoded = jsonencode({
    httpMethod        = "POST"
    prometheusType    = "Prometheus"
    prometheusVersion = "2.40.0"
    timeInterval      = "30s"
    queryTimeout      = "120s"
  })

  secure_json_data_encoded = jsonencode({
    basicAuthPassword = random_password.monitoring_ingress.result
  })
}
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
Datasource provisioned correctly.

### Actual Behavior
Datasource is provisioned with success, but when accessed via GUI shows empty:
![image](https://user-images.githubusercontent.com/578872/232739207-8a4c0210-ecea-4dce-aef7-d1f9ad2f3631.png)

It takes considerable time for it to be converted by the cloud to v2.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
This is a regression in Grafana Cloud - it seems the `version` field hard coded in the provider to 1 is now 2. Grafana API docs still lists 1 as the version to use.

**Comment by julienduchesne** [comment]
Can you try with the latest provider version? The `version` field is not something that we send to the API, it represents how many updates were made to that datasource. It is incremented on every PUT

**Comment by mindw** [comment]
The issue can no longer be reproduced. 
Thank you for looking into this!
