### ISSUE TITLE
MetricsPublisher role on `grafana_cloud_stack_service_account ` ?

### ISSUE THREAD

**Issue by mloiseleur** [grafana/terraform-provider-grafana#888]
### Terraform Version
* Terraform: 1.4.5
* Terraform Grafana Provider: 1.37.2
* Grafana Cloud

### Affected Resource(s)

* Sending metrics, logs or traces

### Terraform Configuration Files
```hcl
resource "grafana_cloud_stack_service_account" "writer" {
  stack_slug = var.grafana_cloud_stack_slug
  name       = "tf-test-writer"
  role       = "MetricsPublisher"
}

resource "grafana_cloud_stack_service_account_token" "writer" {
  name               = "tf-test-writer"
  service_account_id = grafana_cloud_stack_service_account.writer.id
}

output "service_account_token_writer_key" {
  value     = grafana_cloud_stack_service_account_token.writer.key
  sensitive = true
}

```

### Expected Behavior

Since v1.37, there is a deprecation notice on `grafana_cloud_api_key`. 
I tried to switch to service account token with sample code provided in [the doc](https://registry.terraform.io/providers/grafana/grafana/latest/docs/resources/cloud_stack_service_account_token).

I encountered two issues:
1. There is no documentation on this in **Grafana Cloud** API doc:  https://grafana.com/docs/grafana-cloud/api-reference/cloud-api/
2. There is no MetricsPublisher role

### Actual Behavior

An error message on the role:
![image](https://user-images.githubusercontent.com/97035654/232791205-200d6b5a-0906-4f4b-8d83-f3a8556fe684.png)

=> How am can I migrate and keep rights restricted to metrics publishing only ?

**Comment by julienduchesne** [comment]
The deprecation notice on cloud_api_key was an error. It has been removed. See: https://registry.terraform.io/providers/grafana/grafana/latest/docs/resources/cloud_api_key. It's actually `cloud_stack_api_key`: https://registry.terraform.io/providers/grafana/grafana/latest/docs/resources/cloud_stack_api_key that's deprecated
