### ISSUE TITLE
Sporadic error 407 when creating folders on Azure Grafana

### ISSUE THREAD

**Issue by rdvansloten** [grafana/terraform-provider-grafana#893]
### Terraform Version
* Terraform: 1.3.8
* Terraform Grafana Provider: 1.37.2
* Grafana: Azure Managed Grafana (9.3.8)

### Affected Resource(s)
Please list the resources as a list, for example:
* grafana_dashboard
* grafana_folder

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "grafana_folder" "main" {
  for_each = var.dashboards
  title    = each.key

  depends_on = [time_sleep.wait_seconds]
}

# Get local json files to put into dashboards
data "local_file" "main" {
  for_each = local.dashboards
  filename = "${path.root}/${each.key}"
}

resource "grafana_dashboard" "main" {
  for_each = local.dashboards

  config_json = data.local_file.main[each.key].content
  folder      = grafana_folder.main[each.value.folder].id
  message     = grafana_folder.main[each.value.folder].title
  overwrite   = true
}
```

### Panic Output
https://gist.github.com/rdvansloten/6c3645ce4b589d02a79b5667b0e6f448

### Expected Behavior
Folders should have been created.

### Actual Behavior
Errro 407 is thrown -sometimes-. 

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
I have tried this from a laptop to a personal Azure Grafana instance, from a CICD pipeline to a company Azure Grafana instance. The Azure Grafana instance is created from scratch each run, so there is no "bad egg" in play here.

Retrying the deployment of the folders usually works. Also, if there is a list of folders, the first one will 407, but the rest will usually be created. Perhaps an optional/built-in retry would resolve this issue. I have already put a sleep timer of 20 minutes on the folder creation, so that it ensures a the instance of Grafana to be ready for traffic, but this does not help at all. I have no indication that Grafana is unreachable (logging in manually works, all other resources are created even though 1 fails)

**Comment by julienduchesne** [comment]
It's now possible to specify custom status codes to retry: https://github.com/grafana/terraform-provider-grafana/pull/940

```
provider "grafana" {
  url                = "http://localhost:3000"
  auth               = "admin:admin"
  retry_status_codes = [407, 429, "5xx"]
}
```
