### ISSUE TITLE
PagerDuty Contact Point inconsistent with UI

### ISSUE THREAD

**Issue by 80kk** [grafana/terraform-provider-grafana#901]
It looks like not all options available for PagerDuty Contact Point are available in Terrafrom resource. According to GUI Client URL JSON model should be `client_url` but it doesn't work:
```
│   on ../modules/grafana/main.tf line 42, in resource "grafana_contact_point" "contact_point_pagerduty":
│   42:     client_url             = "{{ template \"pd.clientURL\" . }}"
│ 
│ An argument named "client_url" is not expected here.
```

**Comment by julienduchesne** [comment]
Added here: https://github.com/grafana/terraform-provider-grafana/pull/919
