### ISSUE TITLE
The terraform-provider-grafana_v1.39.0 plugin crashed

### ISSUE THREAD

**Issue by vladimirjaric** [grafana/terraform-provider-grafana#903]
### Terraform Version
* Terraform: v1.4.5
* Terraform Grafana Provider: v1.39.0
* Grafana: Cloud

### Affected Resource(s)
Please list the resources as a list, for example:
* grafana_cloud_stack
* grafana_api_key
* grafana_cloud_stack_service_account
* grafana_cloud_stack_service_account_token

### Terraform Configuration Files
```hcl
provider "grafana" {
  alias = "cloud"
  auth  = data.aws_ssm_parameter.grafana_token.value
}

resource "grafana_cloud_stack" "stack" {
  provider = grafana.cloud

  name        = "${var.environment}"
  slug        = "${var.environment}"
  region_slug = "au"
}

resource "grafana_cloud_stack_service_account" "terraform" {
  stack_slug = grafana_cloud_stack.stack.slug

  name        = "terraform"
  role        = "Admin"
}

resource "grafana_cloud_stack_service_account_token" "terraform" {
  stack_slug = grafana_cloud_stack.stack.slug

  name               = "terraform"
  service_account_id = grafana_cloud_stack_service_account.terraform.id
}

provider "grafana" {
  alias = "stack"

  url   = grafana_cloud_stack.stack.url
  auth  = grafana_cloud_stack_service_account_token.terraform.key
}
```

### Panic Output
https://gist.github.com/vladimirjaric/77401cebd71be5659e25c51c095212e0

### Expected Behavior
To delete the stack API key and create a service account with a token

### Actual Behavior
The terraform-provider-grafana_v1.39.0 plugin crashed

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`

Let me know if you need any other information.

Thank you,
Vlad

**Comment by julienduchesne** [comment]
@IevaVasiljeva fyi. Seems to be in the new temp service account token

**Comment by IevaVasiljeva** [comment]
Hi @vladimirjaric and sorry for the slow response!

I've just tested this, and unfortunately could not reproduce it. Here are the steps that I took (collapsed, as they take up a lot of space):
<details>
  <summary>Attempted repro steps</summary>

1. Use the below config and import my Grafana stack using `terraform import grafana_cloud_stack.my_stack <id>`

```
terraform {  
  required_providers {  
    grafana = {  
      source = "grafana/grafana"
      version = "1.39.0"  
    }  
  }  
}  

provider "grafana" {
  alias         = "cloud"
  cloud_api_key = <cloud_API_key>
}

resource "grafana_cloud_stack" "my_stack" {
  provider = grafana.cloud

  name        = <stack_name>
  slug        = <stack_slug>
  region_slug = "eu"
}
```

2. After a successful import, create an API key and use that for provider auth. Additional config:

```
resource "grafana_api_key" "management-api" {
  provider = grafana.cloud

  cloud_stack_slug = grafana_cloud_stack.my_stack.slug
  name             = "management-key"
  role                = "Admin"
}

provider "grafana" {
  alias = "stack"
  url    = grafana_cloud_stack.my_stack.url
  auth = grafana_api_key.management-api.key
}
```

3. When API key has been created, add config for Cloud stack service account and service account token and create those. Additional config:

```
resource "grafana_cloud_stack_service_account" "terraform" {
  provider = grafana.cloud

  stack_slug = grafana_cloud_stack.my_stack.slug
  name          = "terraform"
  role             = "Admin"
}

resource "grafana_cloud_stack_service_account_token" "terraform" {
  provider = grafana.cloud

  stack_slug                = grafana_cloud_stack.my_stack.slug
  name                         = "terraform"
  service_account_id = grafana_cloud_stack_service_account.terraform.id
}
```

4. Now remove the `grafana_api_key` resource and use the service account for provider auth. Config at this point:

```
resource "grafana_cloud_stack_service_account" "terraform" {
  provider = grafana.cloud

  stack_slug = grafana_cloud_stack.my_stack.slug
  name          = "terraform"
  role             = "Admin"
}

resource "grafana_cloud_stack_service_account_token" "terraform" {
  provider = grafana.cloud

  stack_slug                = grafana_cloud_stack.my_stack.slug
  name                         = "terraform"
  service_account_id = grafana_cloud_stack_service_account.terraform.id
}

provider "grafana" {
  alias = "stack"
  url    = grafana_cloud_stack.my_stack.url
  auth = grafana_cloud_stack_service_account_token.terraform.key
}
```
</details>

The API key got removed successfully, and the service account is created and can be used for provider auth. I didn't experience any crashes.

Do you have a repro case that you could share with me so that I can investigate this further?

**Comment by philyang07** [comment]
@IevaVasiljeva I believe for the Grafana cloud provider if you use the `auth` attribute instead of the `cloud-api-key` attribute then the error will occur.

**Comment by vladimirjaric** [comment]
Hi @IevaVasiljeva, thank you for looking into this issue. Unfortunately, the only way we could avoid the crash was to manually convert a Grafana stack from using API keys to service accounts, and remove `grafana_api_key` from the terraform state.

We also had to manually remove `grafana_folder`, `grafana_team`, and all `grafana_data_source` objects from the terraform state and let terraform recreate them.

**Comment by IevaVasiljeva** [comment]
Sorry to hear that you had to do it all manually @vladimirjaric, that does sound painful 😞 

@philyang07 what do you use for Cloud auth? Username and password or cloud API key?

**Comment by julienduchesne** [comment]
The client for this has completely changed. Please open a new issue if this is still occurring
