### ISSUE TITLE
Unable to Create Orgs with Admin Token

### ISSUE THREAD

**Issue by m1kewu** [grafana/terraform-provider-grafana#904]
### Terraform Version
* Terraform: 1.3.9
* Terraform Grafana Provider: 1.39.0
* Grafana: 9.4.7

### Affected Resource(s)
Please list the resources as a list, for example:
* grafana_organization

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.

# main.tf
resource "grafana_organization" "miketest" {
  name         = "Mike Test Org"
  admin_user   = "admin"
  create_users = true
  admins = [
    "admin@example.com"
  ]
  editors = [
    "editor@example.com"
  ]
  viewers = [
    "viewer@example.com"
  ]
}

# provider.tf
terraform {
  required_providers {
    grafana = {
      source  = "grafana/grafana"
      version = "1.39.0"
    }
  }
}

provider "grafana" {
  auth = "<admin-token>"
  url  = "http://localhost:3000"
}

```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

https://gist.github.com/mikewu-tl/d44d4f5643c1f9f33d4bf552f5005cb6

### Expected Behavior
What should have happened?
An Grafana org should be created. I could create one manually at localhost:3000 as admin.

### Actual Behavior
Threw error see above debug output gist.
Note that I am able to create other Grafana resource in Terraform, such as `grafana_service_account`.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Starting Grafana locally
2. Create `provider.tf` and `main.tf` as specified above, replacing with an admin token (generate one with default Grafana Server admin)
3. run `terraform apply -auto-approve`

**Comment by julienduchesne** [comment]
I just documented it. The issue is that orgs are instance-scoped while service accounts are org-scoped and cannot act outside of the org (ex: creating another org)
