### ISSUE TITLE
The details portion of the PagerDuty contact_point is not configurable

### ISSUE THREAD

**Issue by bschaeffer** [grafana/terraform-provider-grafana#911]
Hi!

I am trying to set the `details` part of the PagerDuty contact point like you can via the UI:

![image](https://user-images.githubusercontent.com/74099/236318913-a72f24d1-1cc5-4558-8cc4-bfc2b94bde6c.png)

How are people setting this in TF now?

### Terraform Version
* Terraform: 1.4.4
* Terraform Grafana Provider: 1.39
* Grafana: ENT

### Affected Resource(s)
Please list the resources as a list, for example:
* [grafana_contact_point](https://registry.terraform.io/providers/grafana/grafana/latest/docs/resources/contact_point)

**Comment by bschaeffer** [comment]
Actually... looks like it comes back as `map[string]interface` if you do a `terraform import`.. I am still unsure how to set this value in TF.

No matter what I do I get this error:

```
{
  "message":"invalid object specification: failed to validate receiver of type \"pagerduty\": failed to unmarshal settings: json: cannot unmarshal string into Go struct field Config.details of type map[string]string",
  "traceID":"3ab9284103150741"
}
```

**Comment by bschaeffer** [comment]
Looks to me like [config_test.go](https://github.com/grafana/alerting/blob/main/receivers/pagerduty/config_test.go) is testing that the `Config` can unmarshal a string and not testing that TF actually supports configuring it that way. If you configure the contact point `details` like in the test cases, ie https://github.com/grafana/alerting/blob/main/receivers/pagerduty/config_test.go#L226-L233

You get this error:
```
│ Error: Incorrect attribute value type
│ 
│   on grafana.tf line 8, in resource "grafana_contact_point" "pagerduty":
│    8:     settings = {
│    9:       "details": {
│   10:         "cluster" : each.key,
│   11:         "owner"   : "{{ index .Labels \"owner\" }}",
│   12:         "app"     : "{{ index .Labels \"app\" }}",
│   13:       }
│   14:     }
│     ├────────────────
│     │ each.key is a string
│ 
│ Inappropriate value for attribute "settings": element "details": string required.
╵
```

**Comment by alexweav** [comment]
Implemented by https://github.com/grafana/terraform-provider-grafana/pull/912
