### ISSUE TITLE
Add support for creating subfolders using terraform

### ISSUE THREAD

**Issue by suntala** [grafana/terraform-provider-grafana#935]
Subtask of the [Nested Folders epic](https://github.com/grafana/terraform-provider-grafana/issues/935). This is not a GA feature. It is only supported if the `nestedFolders` feature flag is enabled.

- [ ] Make sure tests are running: https://github.com/grafana/terraform-provider-grafana/blob/master/internal/resources/grafana/resource_folder_test.go . We'll need to add a resource with parent folder [here](https://github.com/grafana/terraform-provider-grafana/blob/master/examples/resources/grafana_folder/resource.tf) because we'll need it for the next step.
- [ ] Add a test to make sure the terraform provider is working with subfolders e.g. https://github.com/grafana/grafana/blob/d3546558f3c89e80706a48ee3c496b5dd64fa4d7/pkg/services/folder/folderimpl/folder_test.go#L719
- [ ] Update the terraform provider docs: https://github.com/grafana/terraform-provider-grafana/blob/master/docs/resources/folder.md. Shows up with changes [here](https://registry.terraform.io/providers/grafana/grafana/latest/docs/resources/folder)
- [ ] Test the changes to the terraform provider in a grafana cloud dev instance. We can create a dev instance (todo: find guide/use pre-existing stack). Maybe there's a way to create the whole stack through terraform. Enable the feature flag by overriding the configuration ([guide](https://github.com/grafana/deployment_tools/tree/master/ksonnet/environments/hosted-grafana/waves/feature-toggles#add-a-feature-toggle-to-your-instance)).

Acceptance Criteria
- Able to create folder with subfolder via terraform resource in a dev instance.

[Slack context](https://raintank-corp.slack.com/archives/C045Y3PLNET/p1685608822982559)

**Comment by danielthedm** [comment]
@danielthedm to sync with the as-code squad to inform them of the new generated go client work.  Also to sync on who can complete the terraform provider work to support the nested folders work.
