### ISSUE TITLE
can not create annotation with dashboard_uid

### ISSUE THREAD

**Issue by Macaber** [grafana/terraform-provider-grafana#946]
### Terraform Version
* Terraform: v1.4.6
* Terraform Grafana Provider: 1.40.1
* Grafana: 8.3.2

### Affected Resource(s)
Please list the resources as a list, for example:
* grafana_annotataion

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Debug Output
![截屏2023-06-20 09 18 40](https://github.com/grafana/terraform-provider-grafana/assets/33544320/6098b58c-f7cc-4027-9cd3-19c17ed369d3)

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
What should have happened?

### Actual Behavior
can not create annotation with dashboard_uid，only can create annotation successful with dashboard_id

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
```
resource "grafana_annotation" "begin" {
  text          = "test 222 begin init file"
  #dashboard_uid = "balancer-overview"
  dashboard_id = 12
  panel_id      = 101
  tags          = ["accesser"]
}

resource "local_file" "foo3" {
  for_each   = { for instance in local.accesser_nodes : instance.hostname => instance }
  content    = jsonencode(each.value)
  filename   = "${path.module}/result3/test${each.value.pod_name}.json"
  depends_on = [grafana_annotation.begin]
}

resource "grafana_annotation" "after" {
  text          = "test 333 init file finish"
  #dashboard_uid = "balancer-overview"
  dashboard_id = 12
  panel_id      = 101
  tags          = ["accesser"]
  depends_on    = [local_file.foo3]
}
```
### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-1234

**Comment by julienduchesne** [comment]
Managing annotations with dashboard UIDs was added in Grafana 9.0. This is more of a case of https://github.com/grafana/terraform-provider-grafana/issues/661 where we should validate that the feature is actually available
