### ISSUE TITLE
Cannot create grafana_datasource with type postgres

### ISSUE THREAD

**Issue by KacperLegowski** [grafana/terraform-provider-grafana#947]
### Terraform Version
* Terraform: 1.5.0
* Terraform Grafana Provider: 1.41.0
* Grafana: 9.5.1

### Affected Resource(s)
* grafana_datasource

### Terraform Configuration Files
```hcl
resource "grafana_data_source" "postgres" {
  name     = "PostgreSQL"
  type     = "postgres"
  url      = "databse_url"
  username = "user_name"
  json_data_encoded = jsonencode({
    database         = "db_name"
    postgres_version = 1400
    max_idle_conns   = 100
    max_open_conns   = 100
    ssl_mode         = "disable"
  })
  secure_json_data_encoded = jsonencode({
    password = data.google_secret_manager_secret_version.xxx
  })
}
```
### Expected Behavior
Datasource is added to Grafana.

### Actual Behavior
Error: status: 400, body: {"message":"bad request data","traceID":""}

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Use above code to create datasource

**Comment by julienduchesne** [comment]
Going from a request payload: 
![image](https://github.com/grafana/terraform-provider-grafana/assets/29210090/bdeed3d7-61ba-4769-b846-18b3a1595c37)


Your resource should look like:
```
resource "grafana_data_source" "postgres" {
  name     = "PostgreSQL"
  type     = "postgres"
  url      = "databse_url"
  username = "user_name"
  json_data_encoded = jsonencode({
    database         = "db_name"
    postgresVersion = 1400
    maxIdleConns   = 100
    maxOpenConns   = 100
    sslmode         = "disable"
  })
  secure_json_data_encoded = jsonencode({
    password = data.google_secret_manager_secret_version.xxx
  })
}
```

**Comment by KacperLegowski** [comment]
@julienduchesne Isn't it being mapped camelCase to snak_case from the json_data in the provider code? 
See example: https://github.com/grafana/terraform-provider-grafana/blob/804625f664e2b96e69d6869ac6b345c3596a0a6b/internal/resources/grafana/resource_data_source.go#L814-L815
Additionally, if camelCase is valid for the provider - please update the documentation https://registry.terraform.io/providers/grafana/grafana/latest/docs/resources/data_source#json_data
