### ISSUE TITLE
Add SNS to grafana_contact_point 

### ISSUE THREAD

**Issue by archi-jusi** [grafana/terraform-provider-grafana#953]
I've seen that there a lot of different type of contact point but SNS is missing, is it any reason for that ? (hard to implemented, email already there ? ) 

Thanks

**Comment by julienduchesne** [comment]
`sns` is not supported by Grafana Alerting yet. You could create an issue here: https://github.com/grafana/grafana/issues. When this is supported in Grafana, then we can add support in the provider
