### ISSUE TITLE
custom_metrics_namespaces not working for datasource grafana

### ISSUE THREAD

**Issue by archi-jusi** [grafana/terraform-provider-grafana#954]
### Terraform Version
* Terraform: .v1.3.9
* Terraform Grafana Provider: 1.40.1
* Grafana: AWS Managed Grafana 9.4

### Affected Resource(s)
Please list the resources as a list, for example:
* grafana_data_source

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl

resource "grafana_data_source" "external_cloudwatch_test" {
  type = "cloudwatch"
  name = "Cloudwatch-test"

  json_data_encoded = jsonencode({
    defaultRegion = var.aws_default_region
    authType      = "default"
    assumeRoleArn = "arn:aws:iam::xxxxxxxxxx:role/service-role/AmazonGrafanaServiceRole-MgNMTdGzH"
    custom_metrics_namespaces = "jmx"
    externalID = "xxxxxxxxx"
  })
```
AccountID was hidden 

### Expected Behavior
The Datasource is created with Custom metrics namespace added in the datasource 

### Actual Behavior
The Datasource is created but Custom metrics namespace is NOT added in the datasource 

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Used AWS Grafana 9.4 

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
-

**Comment by julienduchesne** [comment]
The key is `customMetricsNamespaces`

![image](https://github.com/grafana/terraform-provider-grafana/assets/29210090/4247c143-ad0e-4de0-a4fb-94f918dc3795)
