### ISSUE TITLE
Add ability to configure SAML based authentication

### ISSUE THREAD

**Issue by loesak** [grafana/terraform-provider-grafana#957]
I don't see a means for configuring a Grafana instance (stack) with SAML based authentication.

**Comment by julienduchesne** [comment]
Duplicate of https://github.com/grafana/terraform-provider-grafana/issues/560

**Comment by loesak** [comment]
@julienduchesne the mentioned duplicate ticket is about OAuth, not SAML. Does it cover this feature request? If so, should that be explained in that ticket? To be more specific, I'd like to use Terraform to configure this aspect of Grafana:

![image](https://github.com/grafana/terraform-provider-grafana/assets/711415/e0bd8ab3-bd7c-4b2c-9db8-0e3622a7b8f2)

Additional documentation or reference: https://grafana.com/docs/grafana/next/setup-grafana/configure-security/configure-authentication/saml-ui/
