### ISSUE TITLE
Expose the influxdb URL on stacks

### ISSUE THREAD

**Issue by loesak** [grafana/terraform-provider-grafana#958]
I'm trying to create a new HTTP connection to write metrics into the system. I'm assuming the UI is actually hiding how this is really organized underneath the covers. I suspect I need to create an access policy with a token, but I cannot seem to find out, via this provider, what the already available influx endpoint is. I tried pulling in the provided InfluxDB data source as a data source to see if i could find the URL that way, but no luck. I tried the following:

```
data "grafana_data_source" "influxdb_by_name" {
  name = "influxdb"
}

data "grafana_data_source" "influxdb_by_name_case" {
  name = "InfluxDB"
}

data "grafana_data_source" "influxdb_by_id" {
  id = "influxdb"
}

data "grafana_data_source" "influxdb_by_uid" {
  uid = "influxdb"
}
```

I suspect that maybe there isn't a specific already provided data source but rather just a missing URL attribute on the `grafana_cloud_stack` resource that points to the influx url (e.g. https://influx-blah-blah-0.grafana.net/api/v1/push/influx/write)?

**Comment by julienduchesne** [comment]
There is no InfluxDB provisioned with Grafana Cloud by default from what I can see. If there were, its URL would be provided as an attribute to `grafana_cloud_stack`. 

`grafana_data_source` queries datasources that are configured in the instance. They should all be visible at https://<stack>.grafana.net/datasources. There are no hidden datasources, if it's not there, it doesn't exist

**Comment by loesak** [comment]
This is from a fresh stack creation. Navigate to "Add new connection" under "Connections" in the Grafana menu. From there, select "HTTP Metrics". Scroll down and see documentation outlined in step 4 "Send a Prometheus metric from your application code.". There you see a URL (https://influx-prod-13-prod-us-east-0.grafana.net/api/v1/push/influx/write) to use that is specific to the stack. How do I get this URL via this Terraform provider?

![image](https://github.com/grafana/terraform-provider-grafana/assets/711415/f7ed4b12-8a89-4975-9f3f-1001a2ac257d)

**Comment by julienduchesne** [comment]
You'll have to request it with a Grafana Cloud ticket. It's not exposed in the API: https://grafana.com/docs/grafana-cloud/api-reference/cloud-api/#list-stacks so we can't expose it in Terraform

**Comment by loesak** [comment]
I'll make the request. In the meantime, does it make sense to leave this ticket open pending the completion of the other ticket once it's created?

**Comment by julienduchesne** [comment]
I'll reopen it and mark it as blocked

**Comment by loesak** [comment]
Given that Grafana Cloud is proprietary, I'm not sure if there is a GitHub repo where a feature request can be made. In the meantime, I submitted a support ticket to see where I get.

**Comment by loesak** [comment]
Support ticket submitted. They are passing it to the "Voice of Customer" team for consideration. I'll follow up here if I get any updates.
