### ISSUE TITLE
Error: invalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by iculda** [grafana/terraform-provider-grafana#962]
### Terraform Version
* Terraform: 1.3.8
* Terraform Grafana Provider: 1.42.0
* Grafana: 9.4.7

### Affected Resource(s)
Please list the resources as a list, for example:
* grafana_folder
* i think all resources

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
provider "grafana" {
  url  = "url/"
  auth = "key"
}

resource "grafana_folder" "test_folder" {
  title = "Terraform Test Folder"
}
```

### Debug Output
[Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.](https://www.terraform.io/docs/internals/debugging.html)

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
What should have happened?

### Actual Behavior
I tried to create a folder in a oss grafana that runs in aks
i got the following error Error: invalid character '<' looking for beginning of value

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
On top of the kube grafana instance there is an app registration so i'm not sure that i need to provide anything to auth excepting the key

**Comment by iculda** [comment]
2023-07-04T12:34:58.305Z [ERROR] provider.terraform-provider-grafana_v1.42.0: Response contains error diagnostic: @caller=github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/diag/diagnostics.go:55 @module=sdk.proto diagnostic_severity=ERROR tf_resource_type=grafana_folder tf_rpc=ApplyResourceChange diagnostic_detail= diagnostic_summary="invalid character '<' looking for beginning of value" tf_proto_version=5.3 tf_provider_addr=registry.terraform.io/grafana/grafana tf_req_id=71232c34-6d38-2163-7422-55942a5464e7 timestamp=2023-07-04T12:34:58.305Z
2023-07-04T12:34:58.309Z [ERROR] vertex "grafana_folder.test_folder" error: invalid character '<' looking for beginning of value

**Comment by julienduchesne** [comment]
I would say that your url is not actually pointing to a Grafana instance. This looks like JSON trying to unmarshal HTML markup

**Comment by riupie** [comment]
I got the same issue. Been trying switch the version of terraform and provider.
```
Terraform v1.3.7
Terraform Grafana Provider: 1.28.2
Grafana 9.5.3
```

```
resource "grafana_folder" "rule_folder" {
  title = "My Alert Rule Folder"
}

terraform {
  required_providers {
    grafana = {
      source  = "grafana/grafana"
      version = "1.28.2"
    }
  }
}

provider "grafana" {
  url  = "https://grafana.example.com/"
  org_id = 1
  auth = "xxxxxxxx"
}

```

**Comment by iculda** [comment]
You were right, there was an auth proxy redirect and tf did not reach grafana
Thanks
