### ISSUE TITLE
New upstream release, can we get a new provider release?

### ISSUE THREAD

**Issue by sethbacon** [grafana/terraform-provider-grafana#97]
New release of [go-grafana-api](https://github.com/nytm/go-grafana-api/releases/tag/v0.5.0). Looks like some work finally being done upstream...can we get a new release of the provider based on this?

**Comment by tonglil** [comment]
We are planning on it soon!

**Comment by sethbacon** [comment]
@tonglil @mlclmj Thanks for all your efforts recently!!!
