### ISSUE TITLE
Migrating from provider-based org_id to new org_id option

### ISSUE THREAD

**Issue by adkinsjd** [grafana/terraform-provider-grafana#986]
Given the completion of adding the org_id option to all of the resources, I have been attempting to migrate from having the org_id in the provider block to specifying org_id as a resource option.

When I do this, all resources that are switched are not found and are therefore slated to be recreated upon running `terraform apply`. Is this expected? Specifically I getting this warning for all resources:

> resource with ID XXX is in Terraform state, but no longer exists in Grafana

**Comment by adkinsjd** [comment]
As a follow up on this, as you would expect, when you proceed to apply and attempt to recreate the resource it throws an error because the resource already exists.

**Comment by adkinsjd** [comment]
And if I import the resource before applying everything works as expected, however this is not feasible across hundreds of resources.

**Comment by julienduchesne** [comment]
Can you try applying once with the old config and the new version (upgrading the provider but keeping the deprecated global org ID) and then converting your resources to the new config (removing the global org ID)?

**Comment by adkinsjd** [comment]
I attempted this and ran into #994 

Perhaps in the coming days I could remove those resources to continue debugging this issue in parallel.
